### ISSUE TITLE
Методы объекта, "this" - Пропущена ; в примере

### ISSUE THREAD

**Issue by saavaage** [javascript-tutorial/ru.javascript.info#1020]
Методы объекта, "this" раздел про "Внутренняя реализация: Ссылочный тип"
Пример:
`let user = {
  name: "Джон",
  hi() { alert(this.name); }
}

// разделим получение метода объекта и его вызов в разных строках
let hi = user.hi;
hi(); // Ошибка, потому что значением this является undefined`

пропустили после объекта ';'

**Comment by radionov018** [comment]
https://github.com/javascript-tutorial/ru.javascript.info/pull/1025

**Comment by szhigunov** [comment]
#1025 уже замержен, можно закрывать.
