### ISSUE TITLE
Неработающие ссылки

### ISSUE THREAD

**Issue by haritonov-roman** [javascript-tutorial/ru.javascript.info#1024]
Добрый день в разделе Юникодные свойства, на странице: https://learn.javascript.ru/regexp-unicode присутствуют неработающие ссылки.

**Comment by radionov018** [comment]
![image](https://user-images.githubusercontent.com/42506537/89421661-ff552080-d73c-11ea-9dc4-9adcfd9fd401.png)

**Comment by Roman120991** [comment]
Да, о них идет речь.

**Comment by onicat** [comment]
Обе ссылки рабочие

![image](https://user-images.githubusercontent.com/52637988/94924945-1d35cc00-04c7-11eb-9c3f-93f5ae3f8298.png)

**Comment by Alexandre887** [comment]
Все ссылки в статье рабочие.
