### ISSUE TITLE
Не отображается текст кода документа в приложении Книги

### ISSUE THREAD

**Issue by creatorspiritus** [javascript-tutorial/ru.javascript.info#1030]
День добрый!

Не отображается пример кода в epub-версии документа "Язык программирования JavaScript"

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/12198122/89698079-e52b6600-d927-11ea-9210-0b0ad244cb62.png">

**Comment by Alexandre887** [comment]
Здравствуйте. Проблема ещё актуальна?
