### ISSUE TITLE
Progress bar is not responsive when resizing window

### ISSUE THREAD

**Issue by sematgt** [javascript-tutorial/ru.javascript.info#1042]
![image](https://user-images.githubusercontent.com/42732906/90386810-c8143700-e08d-11ea-946d-7c7ab8c910be.png)
![image](https://user-images.githubusercontent.com/42732906/90386919-ed08aa00-e08d-11ea-9a83-837bd3c03ae6.png)

**Comment by iliakan** [comment]
@GSemikozov глянь плиз?

**Comment by GSemikozov** [comment]
либо уже поправили, либо проблемы нет:
<img width="577" alt="Screenshot 2020-09-26 at 12 27 35" src="https://user-images.githubusercontent.com/6191270/94337527-ab0b4600-fff3-11ea-8e06-fd101a99ae7a.png">

**Comment by sematgt** [comment]
сейчас проблема не повторяется, спасибо
