### ISSUE TITLE
Вероятно, смысловая ошибка в уроке "Дата и время"

### ISSUE THREAD

**Issue by maslaff** [javascript-tutorial/ru.javascript.info#1050]
https://learn.javascript.ru/date#sozdanie
В конце есть строка - "Минимальная точность – 1 мс (1/1000 секунды):"
Исходя из того что точность бывает высокой и низкой, здесь она должна быть максимальной. Либо нужно говорить о значении - "минимально возможное значение"

**Comment by iliakan** [comment]
Пришлите PR? ;)

**Comment by maslaff** [comment]
Не понял, что нужно прислать?
Я что то не так понял?

**Comment by iliakan** [comment]
Pull Request =)

**Comment by maslaff** [comment]
Оу. Что то даже не подумал.
