### ISSUE TITLE
Блок кода

### ISSUE THREAD

**Issue by dmitrij-v** [javascript-tutorial/ru.javascript.info#1052]
Несколько раз натыкался на понятие блок кода, но четкого определения нет. 
Оно есть на старой версии: https://javascript.ru/blok
Оно есть на MDN: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/%D0%91%D0%BB%D0%BE%D0%BA

Имеет смысл добавить его?

**Comment by iliakan** [comment]
https://javascript.info/closure#code-blocks в EN, хорошо бы перенести изменения.

**Comment by dmitrij-v** [comment]
@iliakan я могу сделать перевод. Но в новом варианте нет IIFE. Оно было перенесено куда-то в другое место?

**Comment by iliakan** [comment]
Да, в https://javascript.info/var

В современной разработке, с появлением `let`, необходимость в IIFE резко снизилась. 
Хорошо бы обе статьи обновить.

**Comment by Alexandre887** [comment]
https://learn.javascript.ru/closure#bloki-koda
https://learn.javascript.ru/var#iife
