### ISSUE TITLE
Scroll bug in "Drag heroes" task.

### ISSUE THREAD

**Issue by Ledorub** [javascript-tutorial/ru.javascript.info#1057]
If hero is dragged up after scrolling down, scrolling down continues until _newBottom <= documentElement.clientHeight_.

[Task](https://learn.javascript.ru/mouse-drag-and-drop#tasks)
[Plunker](https://plnkr.co/edit/uhMuh5wwnsQzaJyD?p=preview&preview)

![bug](https://user-images.githubusercontent.com/19720324/91486307-bd8b4600-e8b4-11ea-9711-89af62d9ceb5.gif)

**Comment by iliakan** [comment]
Что там именно не так, поясните?

**Comment by Ledorub** [comment]
При перемещении изображения героя увеличивается координата нижнего края изображения относительно окна.
`let newBottom = newY + dragElement.offsetHeight`

Прокрутка срабатывает когда нижний край изображения перемещается за нижнюю границу окна.
`if (newBottom > document.documentElement.clientHeight) {...}` (1)

Поскольку отсчет положения нижней границы изображения происходит относительно изначального положения окна, то `newBottom` может значительно превышать `document.documentElement.clientHeight`.

Если после прокрутки вниз, не отпуская изображение, потянуть его вверх, то `newBottom` в первое время будет больше `document.documentElement.clientHeight`. В связи с чем выполнится условие (1) и произойдет прокуртка вниз.
