### ISSUE TITLE
Ошибка в статье

### ISSUE THREAD

**Issue by ViktoriLisa** [javascript-tutorial/ru.javascript.info#1058]
https://learn.javascript.ru/coordinates#getCoords
В данной статье в функции getCoords() отсутствует слово window перед pageXOffset/pageXOffset, т.е. написано `top: box.top + pageYOffset, left: box.left + pageXOffset` вместо `top: box.top + window.pageYOffset, left: box.left + window.pageXOffset`. Этот же код используется в песочницах к решениям 2-ч последних заданий "Покажите заметку около элемента (абсолютное позиционирование)" и "Расположите заметку внутри элемента (абсолютное позиционирование)", из-за чего поведение решения не соответствует ожиданиям.

**Comment by mikitachyzhyk** [comment]
Думаю в данном случае это не обязательно. По крайней мере это не ошибка. Window это глобальный объект, доступный из любой области видимости. Т.е. между window.pageYOffset и pageYOffset нету никакой разницы. Если вы не собираетесь перекрывать эти переменные локальными (чего делать не стоит), то не вижу ничего в этом страшного.
