### ISSUE TITLE
Уточнение в уроке о встроенных прототипах

### ISSUE THREAD

**Issue by SayoBye** [javascript-tutorial/ru.javascript.info#1067]
В уроке о прототипах - [Встроенные прототипы
](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/08-prototypes/03-native-prototypes/article.md) есть строка "Это позволяет эффективно использовать память". Возможно неплохим решение было бы описание того почему это позволяет эффективно использовать память, иначе у читателя возникает вполне резонный вопрос, ответа на который он в итоге не получает.

**Comment by iliakan** [comment]
Там не очевидно, что память экономится за счет того, что методы в prototype?

**Comment by SayoBye** [comment]
Как мне кажется раздел учебника "Прототипы" и без того часто запутывает читающего своей сложностью (при первых прочтениях). Несформировавшееся представление о всех этих ссылках на объекты не дает понять в чем же здесь оптимизации. А вот объяснение оптимизации возможно поможет в принципе лучше понять прототипы.
