### ISSUE TITLE
https://learn.javascript.ru/intl в примерах везде var

### ISSUE THREAD

**Issue by ase444ka** [javascript-tutorial/ru.javascript.info#1068]
Здравствуйте! наверно, надо let..

**Comment by iliakan** [comment]
PR?

**Comment by maria-arsenkova** [comment]
> Добрый день, а почему мы отдаем предпочтение let? Не было бы более уместно использовать const?

Попробую ответить на твой вопрос: 
1) Для единства стиля 
2) Для начинающих распространено let 
3) Если посмотреть глобально, дальше уже в зависимости от проекта/стиля кода/ установок команды используют const, к примеру в проектах React: 
   
Оставлю тут для кругозора (следующим):  
let позволяет обновить переменную/объект целиком за раз 
     
Если const в виде: 
—  переменной — обновить (переопределить) не получится, только для чтения
—  объекта/массива —  можно изменять внутренне составляющие, к примеру обновить свойства объекта (ключ) или удалить ключ, но **не** перезаписать (переопределить  ссылку ) за раз весь объект/массив

**Comment by Alexandre887** [comment]
Исправлено.
