### ISSUE TITLE
Утверждение вводит в заблуждение.

### ISSUE THREAD

**Issue by Cerneaga-Denis** [javascript-tutorial/ru.javascript.info#1078]
https://learn.javascript.ru/property-descriptors

В статье есть, такая строчка, которая по моему мнению не корректна и может вводить в заблуждение. 

Цитата:> Неконфигурируемое свойство не может быть удалено или изменено с помощью defineProperty.

На сомом деле свойство с флагом `configurable: false` может быть изменено с помощью defineProperty или посредством прямого обращения к свойству при условии, что флаг  #`writable: true`.

**Comment by iliakan** [comment]
Да, не могли бы перевести правильный вариант с английского и сделать PR? http://javascript.info/property-descriptors

**Comment by vsemozhetbyt** [comment]
Closed in #1089
