### ISSUE TITLE
Переопределение элементов псевдомассива arguments

### ISSUE THREAD

**Issue by Tsyrkull** [javascript-tutorial/ru.javascript.info#1079]
В статье [rest_spread](https://learn.javascript.ru/rest-parameters-spread-operator) ничего не сказано о том, что элементы псевдомассива arguments, можно переопределять, и тогда теряется его первоначальное значение и значение параметров: 
```
function func(a, b) {
    console.log(arguments); // 1, 2
    arguments[0] = b;
    arguments[1] = 13;
    console.log(arguments); // 2, 13
    console.log(a, b); // 2, 13
}
func(1, 2);
```

Думаю, неплохо было бы добавить пару строчек об этом, для лучшего понимания темы.

Спасибо

**Comment by iliakan** [comment]
Есть много способов убить себя об стену, боюсь мы не сможем их все перечислить.
