### ISSUE TITLE
Не ставьте тестовые базы данных на гитхаб, он не передает Content-Length 

### ISSUE THREAD

**Issue by azizhakberd** [javascript-tutorial/ru.javascript.info#1081]
Не ставьте тестовые базы данных на github, он не передает Content-Length. Почему они у вас на github, а на на вашем домене learn.javascript.ru. Так вы бы смогли бы получать все заголовки и особенно ваш Content-Length не пустовал бы

**Comment by iliakan** [comment]
?

**Comment by iliakan** [comment]
Не понимаю проблему

**Comment by azizhakberd** [comment]
Просто в темах с fetch при загрузке json файлов появляется загружено 13457
из 0 нет content length. Это требует cors в гитхабе. Не считаю проблемой
вместо гитхабовских json использовать свои так для наглядности можно
сделать еще и полосу загрузки

сб, 12 сент. 2020 г., 21:06 Ilya Kantor <notifications@github.com>:

**Comment by iliakan** [comment]
Ага, уже яснее, а где конкретно эту проблема в наших примерах вы нашли?

**Comment by azizhakberd** [comment]
в теме fetch  ход загрузки во всех примерах кодов fetch посылает запрос на
github и выводит Content-length вот так
console.log('Загружено ${chunks} из ${+headers.get("Content-length")}');
Здесь github не вернул content length и в консоли 0
Можно просто сменить ссылку с гитхаба на свой домен
learn.javascript.ru/example.json

чт, 17 Сен 2020, 17:35 Ilya Kantor notifications@github.com:

**Comment by iliakan** [comment]
Не могу найти, а вы не даете ссылку.

**Comment by azizhakberd** [comment]
https://learn.javascript.ru/fetch-progress
При запуске кода (там только один запусаемый пример) alert показывает ваше
имя - это нормально json загружен, но в консоли (инструменты разработчика)
выводится прогресс загрузки, там пишется Получено <число> из 0 (всегда 0)

пт, 18 Сен 2020, 21:21 Ilya Kantor notifications@github.com:
