### ISSUE TITLE
Is this translation still maintained?

### ISSUE THREAD

**Issue by vsemozhetbyt** [javascript-tutorial/ru.javascript.info#1084]
Хотелось бы знать, есть ли смысл присылать сейчас пулл-реквесты. Новых коммитов не было уже почти месяц, много открытых пулл-реквестов без ревью, структура разделов и заданий перевода отдаляется от структуры оригинала. Не хочется плодить пулл-реквесты, которые или будут просто накапливаться, или вскоре обрастут конфликтами из-за какого-нибудь коммита с генеральной синхронизацией, или будут конфликтовать друг с другом.

**Comment by iliakan** [comment]
Разгрёб pull request'ы. Твои хорошие, поэтому добавил в мейнтейнеры =)

**Comment by vsemozhetbyt** [comment]
Спасибо. К сожалению, письма я пока не получил, и роль моя пока не поменялась, так что пока продолжу просто создавать пулл-реквесты, если найду, что предложить)

**Comment by iliakan** [comment]
А сейчас?

**Comment by vsemozhetbyt** [comment]
Да, спасибо, сейчас получил. Есть ли какое-то руководство для мейнтейнеров? Например, о правилах ревью, способе слияния пулл-реквестов?

**Comment by iliakan** [comment]
Есть для перевода + небольшой глоссарий: https://github.com/javascript-tutorial/ru.javascript.info/blob/master/TRANSLATION.md

**Comment by vsemozhetbyt** [comment]
Я имел в виду скорее что-то вроде: сколько положительных ревью нужно получить, чтобы принять пулл-реквест? Или их может принимать только создатель репозитория? Каким способом они принимаются — можно ли через интерфейс GitHub-а? Нужно ли что-то исправлять в заголовках коммитов при принятии? И т.п) Или тут нет особых правил и всё либерально)

**Comment by iliakan** [comment]
Принимать можно как угодно. Описание неважно, главное текст.

Ещё хорошо бы если какое-то важное изменения, то сделать его и в английской версии тоже :) Впрочем, ряд ошибок связано с тем что русская версия где-то отстала от английский.

**Comment by vsemozhetbyt** [comment]
Ок. Я просто какое-то время занимался документацией в Node.js, и там всё было расписано до мелочей — сколько минимум дней ждать до принятия пулл-реквеста, оставляя время другим для ревью, сколько одобрений нужно, чтобы принять чужой реквест, и сколько — для слияния собственного, какие должны быть заголовки коммитов для ясной истории и т.п. Поэтому теперь всё время боюсь нарушить протоколы)

То есть, для окончательной ясности, я могу создать реквест и тут же его слить? Или мои реквесты должны быть одобрены перед этим другим участником?

**Comment by iliakan** [comment]
Ну, у нас проще. Если правки очевидно не требуют ревью, то можно тут же их влить.

Если что-то сомнительное, то конечно лучше на ревью оставить.

**Comment by vsemozhetbyt** [comment]
Спасибо.
