### ISSUE TITLE
pointer-events

### ISSUE THREAD

**Issue by mk1020** [javascript-tutorial/ru.javascript.info#1090]
"К настоящему времени спецификация Pointer Events Level 2 поддерживается всеми основными браузерами, а Pointer Events Level 3 находится в разработке и почти полностью совместима с Pointer Events Level 3."
Имеется ввиду что Pointer Events Level 3 совместима с Pointer Events Level 2 как я понимаю, но написано не понятно..

**Comment by vsemozhetbyt** [comment]
[В оригинале всё, как вы и предположили](https://github.com/javascript-tutorial/en.javascript.info/blob/master/2-ui/3-event-details/6-pointer-events/article.md#the-brief-history). Сделаете пулл-реквест?
