### ISSUE TITLE
В статье ФУНКЦИИ alert( 'Доступ закрыт' ) никогда не выведется

### ISSUE THREAD

**Issue by AnnaVoloshina** [javascript-tutorial/ru.javascript.info#1096]
В статье ФУНКЦИИ alert( 'Доступ закрыт' ) никогда не выведется.
При вводе age < 18 функция возвращает confirm('А родители разрешили?') и выводится alert( 'Доступ получен' ).
Нужно, по идее, просто вывести confirm('А родители разрешили?'), а затем вернуть false в блоке ELSE.

function checkAge(age) {
  if (age > 18) {
    return true;
  } else {
    return confirm('А родители разрешили?');
  }
}

let age = prompt('Сколько вам лет?', 18);

if ( checkAge(age) ) {
  alert( 'Доступ получен' );
} else {
  alert( 'Доступ закрыт' );
}

**Comment by TravellerOnline** [comment]
confirm('А родители разрешили?') может вернуть false, если нажмем кнопку Отмена
и тогда alert( 'Доступ закрыт' ) сработает
