### ISSUE TITLE
Возможно опечатка

### ISSUE THREAD

**Issue by pashinskiy** [javascript-tutorial/ru.javascript.info#1097]
Глава Классы
Тема Класс: базовый синтаксис
Свойство классов
"Вместо этого оно создаётся оператором new перед запуском конструктора, это именно свойство **объекта**."

**Comment by vsemozhetbyt** [comment]
Спасибо за замечание. В чём именно вы видите ошибку? Как бы вы предложили исправить? Пока что перевод вроде бы отвечает оригиналу (оригинал уже немного ушёл вперёд, он чуть полнее, но этот фрагмент по сути совпадает: https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/09-classes/01-class/article.md#class-fields). Возможно, оригинал тоже нуждается в уточнении.

**Comment by pashinskiy** [comment]
Возможно ошибаюсь,это именно свойство объекта Не правильнее ли это именно свойство класса18 сент. 2020 г. 16:40 пользователь Vse Mozhe Buty <notifications@github.com> написал:
Спасибо за замечание. В чём именно вы видите ошибку? Как бы вы предложили исправить? Пока что перевод вроде бы отвечает оригиналу (оригинал уже немного ушёл вперёд, он чуть полнее, но этот фрагмент по сути совпадает: https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/09-classes/01-class/article.md#class-fields). Возможно, оригинал тоже нуждается в уточнении.

**Comment by vsemozhetbyt** [comment]
Судья по https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields или https://github.com/tc39/proposal-class-fields, это таки свойства экземпляра, а не прототипа или класса, если вы это имеете в виду. Например:

```js
class User {
  name = "John";

  sayHi() {
    alert(`Hello, ${this.name}!`);
  }
}

console.log(Object.getOwnPropertyNames(User.prototype)); // [ 'constructor', 'sayHi' ]
```

**Comment by pashinskiy** [comment]
Так это свойство экземпляра класса? Так и подумал(выразился некорректно изначально), у вас написано свойство объекта, это и смутило18 сент. 2020 г. 17:29 пользователь Vse Mozhe Buty <notifications@github.com> написал:

Судья по https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields или https://github.com/tc39/proposal-class-fields, это таки свойства экземпляра, а не прототипа или класса, если вы это имеете в виду. Например:

class User {

  name = "John";



  sayHi() {

    alert(`Hello, ${this.name}!`);

  }

}



console.log(Object.getOwnPropertyNames(User.prototype)); // [ 'constructor', 'sayHi' ]

**Comment by vsemozhetbyt** [comment]
Ну, экземпляр ведь и является объектом с нужным прототипом, так что формально вроде правильно. Но если это слишком общее название путает читателя, попробуйте предложить пулл-реквест, лучше даже сразу в оригинал, чтобы автор смог решить, менять или нет)
