### ISSUE TITLE
Опечатка в статье "Настройка стилей теневого DOM"

### ISSUE THREAD

**Issue by Maksimchikm** [javascript-tutorial/ru.javascript.info#1113]
В этой статье в разделе "Каскадирование" после примера кода добавлена лишняя буква "в"
![image](https://user-images.githubusercontent.com/47310149/94331565-d9365900-ffe6-11ea-9a99-4aaeac27a595.png)

**Comment by lex111** [comment]
Спасибо, исправлено в https://github.com/javascript-tutorial/ru.javascript.info/commit/e44e1132555fedac7c941fda667dd5e1755b01a4#diff-e9ac84503163765941e0e6312557c137
