### ISSUE TITLE
Блок сдвигается вправо из-за margin-right

### ISSUE THREAD

**Issue by sqlzzy** [javascript-tutorial/ru.javascript.info#1119]
На [странице](https://learn.javascript.ru/) в мобильной версии первый блок сдвигается вправо из-за свойства margin-right.
![Screenshot at 18-26-03](https://user-images.githubusercontent.com/34161990/94829912-aee40180-0413-11eb-8398-5fb451cfbde4.png)

![Screenshot at 18-26-38](https://user-images.githubusercontent.com/34161990/94829935-b4414c00-0413-11eb-9878-d3dd6bcb6262.png)

**Comment by Alexandre887** [comment]
Неактуально.
