### ISSUE TITLE
Ошибка в статье "Свойство outline".

### ISSUE THREAD

**Issue by mikitachyzhyk** [javascript-tutorial/ru.javascript.info#1145]
В этой статье есть ошибка:
https://learn.javascript.ru/outline

"Все браузеры, кроме IE9-, также поддерживают свойство outline-offset, задающее отступ outline от внешней границы элемента:"

Caniuse и MDN пишет, что поддержка начинается с 15го Edge:
https://caniuse.com/mdn-css_properties_outline-offset

**Comment by lex111** [comment]
Если есть желание/возможность, пришлите, пожалуйста, пулреквест с исправлением.

**Comment by mikitachyzhyk** [comment]
Хорошо, я попробую.

**Comment by mikitachyzhyk** [comment]
Прислал пулреквест. Странно только вышло с третьим изменением, ничего не менял, да и ничего вроде бы не изменилось, но оно есть. Не знаю, в чем проблема.
https://github.com/javascript-tutorial/ru.javascript.info/pull/1151
