### ISSUE TITLE
пунктуационные ошибки

### ISSUE THREAD

**Issue by Aigul9** [javascript-tutorial/ru.javascript.info#1155]
https://learn.javascript.ru/function-basics
Как сейчас:
Благодаря префиксам, при первом взгляде на имя функции становится понятным что делает её код, и какое значение она может возвращать.
Имя функции должно понятно и чётко отражать, что она делает. Увидев её вызов в коде, вы должны тут же понимать, что она делает, и что возвращает.
Как должно быть:
Благодаря префиксам(1) при первом взгляде на имя функции становится понятным,(2) что делает её код(3) и какое значение она может возвращать.
Имя функции должно понятно и чётко отражать, что она делает. Увидев её вызов в коде, вы должны тут же понимать, что она делает(4) и что возвращает.

https://learn.javascript.ru/function-expressions
В результате(5) функции, созданные(6) как Function Declaration, (7) могут быть вызваны раньше своих определений.
Это позволяет более гибко организовывать код(8) и улучшает его читаемость.
Мы рассмотрели несколько таких примеров в этой главе(9) и рассмотрим их ещё больше в будущем.

https://learn.javascript.ru/coding-style
Однако в JavaScript бывают случаи, когда перенос строки не интерпретируется(10) как точка с запятой, что может привести к ошибкам.

https://learn.javascript.ru/comments
Вы думаете: «Каким глупым я раньше был и насколько умнее стал сейчас» -(11) и переписываете его на «более правильный и оптимальный» вариант.
Которые объясняют, как работает код(12) и что он делает.
Вы даже смутно припоминаете(13) почему, так как в прошлый раз вы уже его пробовали. Вы возвращаетесь к правильному варианту, потратив время зря.

https://learn.javascript.ru/ninja-code
Мало(14) кто преуспел.

https://learn.javascript.ru/testing-mocha
Обычно, когда мы пишем функцию, мы легко можем представить, что она должна делать(15) и как она будет вести себя в зависимости от переданных параметров.
Однако(16) такие «ручные перезапуски» – не лучшее решение.
Вроде бы(17) всё хорошо, не так ли?
Однако(18) мы забыли заново протестировать f(1)
Перед тем(19) как начать писать код функции pow, мы можем представить себе, что она должна делать, и описать её.
Помимо этого,(20) есть одно хорошее правило, которому стоит следовать.
Однако(21) перед этим стоит сгруппировать вспомогательную функцию makeTest и цикл for. 
Или же(22) если наказание за ошибки в коде серьёзное, то люди просто побоятся вносить изменения в такие функции

https://learn.javascript.ru/object
Но есть особый случай, когда оно не подходит(23) и нужно использовать "in".

https://learn.javascript.ru/object-copy
Остальные аргументы src1, ..., srcN (может быть столько, сколько нужно) (24) являются исходными объектами

https://learn.javascript.ru/object-methods
Так что(25) в приведённом примере это user или admin.
Для работы вызовов типа user.hi() (26) JavaScript использует трюк – точка '.' возвращает не саму функцию, а специальное значение «ссылочного типа», называемого Reference Type.
Когда скобки () применяются к значению ссылочного типа (происходит вызов), то они получают полную информацию об объекте и его методе (27) и могут поставить правильный this (=user в данном случае, по base).

https://learn.javascript.ru/constructor-new
Заглавная буква в названии функции является всеобщим соглашением по именованию, она как бы подсказывает разработчику, что данная функция является функцией-конструктором(28) и её нужно вызывать через new.
При вызове return с объектом(29) будет возвращён объект, а не this.
При вызове return с примитивным значением(30) примитивное значение будет отброшено.
Можно передавать конструктору параметры, определяющие, как создавать объект(31) и что в него записывать.
?. проверяет левую часть выражения на равенство null/undefined(34) и продолжает дальнейшее вычисление, только если это не так.

https://learn.javascript.ru/operators
"Прежде чем(32) мы двинемся дальше"

https://learn.javascript.ru/nullish-coalescing-operator
"В этой статье мы будем говорить, что значение выражениЯ"(33)

**Comment by Alexandre887** [comment]
Ошибки исправлены. 
В следующий раз, если захотите сделать какие-либо корректировки, присылайте Pull Request, чтобы мы смогли нормально рассмотреть правки.
