### ISSUE TITLE
Дописать, что var записывает переменные в window

### ISSUE THREAD

**Issue by higimo** [javascript-tutorial/ru.javascript.info#1175]
```js
var hello = 42
console.log(window.hello)
```

**Comment by higimo** [comment]
> Есть ещё одно небольшое отличие, относящееся к глобальному объекту, мы рассмотрим его в [следующей главе](https://learn.javascript.ru/global-object).

Может, хотя бы так?=)

**Comment by Alexandre887** [comment]
![image](https://user-images.githubusercontent.com/74434545/186753619-d9fde1f0-64d1-4623-abf1-6074af52d1c2.png)
