### ISSUE TITLE
Копирование объектов и ссылки/Вложенное клонирование

### ISSUE THREAD

**Issue by KanatovChingis01** [javascript-tutorial/ru.javascript.info#1176]
Извиняюсь если этот вопрос окажется слишком глупым.
Я не понял куда нужно вписать user[key] в последнем примере что-бы получить глубокое клонирование.

**Comment by Alexandre887** [comment]
Добрый вечер,
Понимаю, что скорее всего, спустя почти два года, для вас этот вопрос больше не актуален, но всё же:
- Если вам непонятен материал из какой-либо статьи учебника (или же, есть проблемы с какой-то определенной темой), — вы можете уточнить все интересующие вас вопросы на [официальном Discord-сервере learn.javascript.ru](https://discord.com/invite/X8yWNWpTQs). 

  Issue же, в свою очередь, нужно создавать, если у вас есть вопросы/уточнения по учебнику в целом: где-то указана 
  неточная/неактуальная информация; присутствуют опечатки в тексте; некорректно отображаются какие-либо 
  элементы на самом сайте; есть предложения по улучшению качества материала, и т.д.
