### ISSUE TITLE
В задаче к статье Методы массивов код решения отображается дважды

### ISSUE THREAD

**Issue by stas-dolgachov** [javascript-tutorial/ru.javascript.info#1187]
Чтобы воспроизвести, нужно открыть вот эту задачу и кликнуть по "Решению":
https://learn.javascript.ru/array-methods#sozdat-rasshiryaemyy-kalkulyator

Код решения отобразится дважды
![image](https://user-images.githubusercontent.com/9461925/101283783-5b13e100-37e5-11eb-8d54-d9d332184b89.png)

**Comment by Alexandre887** [comment]
### Исправлено:
![image](https://user-images.githubusercontent.com/74434545/186464773-9438182f-f513-4883-beaf-db536e891380.png)
