### ISSUE TITLE
Возможно неверный ответ

### ISSUE THREAD

**Issue by maxamon** [javascript-tutorial/ru.javascript.info#1210]
Если проверять этот вопрос в консоле то правильный ответ `undefined`
<img width="859" alt="Screen Shot 2021-01-11 at 19 38 09" src="https://user-images.githubusercontent.com/2377782/104218145-fcc1ca00-5444-11eb-8e1c-069421887efe.png">

**Comment by DaniilGorokhov** [comment]
В описании к тесту написано, что весь код исполняется в строгом режиме (use strict), где данный код вызовет ошибку
![image](https://user-images.githubusercontent.com/49070059/104220343-68f5fb00-5450-11eb-9f7f-5a496a64aaf0.png)

**Comment by maxamon** [comment]
Точно! Ошибочка вышла
