### ISSUE TITLE
Глава Базовые операторы, Оператор «запятая». Неверный синтаксис.

### ISSUE THREAD

**Issue by Pavel-Latyshov** [javascript-tutorial/ru.javascript.info#1213]
Без них в a = 1 + 2, 3 + 4 сначала выполнится +, суммируя числа в a = 3, 7, затем оператор присваивания = присвоит a = 3, а то, что идёт дальше, будет игнорировано. Всё так же, как в (a = 1 + 2), 3 + 4

a = 1 + 2, 3 + 4 - данный код работать не будет

**Comment by Xardas225** [comment]
Данный пример прекрасно работает и отражает то, что у оператора "," очень низкий приоритет. Ниже, чем у "=".
Пример работает так, как описано.

**Comment by Alexandre887** [comment]
> a = 1 + 2, 3 + 4 - данный код работать не будет

Данный код будет работать, но, только в нестрогом режиме (без использования `"use strict"`).

В комментариях под главой тоже видел недоумения (некоторые даже запускали `let a = 1 + 2, 3 + 4`), поэтому добавил конкретизацию в этот раздел:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/e360e1a2-772a-4c50-9316-fe82ff77b77c)

Спасибо за фидбэк!
