### ISSUE TITLE
Вопрос по задаче

### ISSUE THREAD

**Issue by Akim-boyarin** [javascript-tutorial/ru.javascript.info#1224]
Здравствуйте! Возник вопрос по задаче в данной главе:
https://learn.javascript.ru/primitives-methods

Сама задача:
<pre>
let str = "Привет";

str.test = 5; 

alert(str.test);
</pre>
"Как вы думаете, это сработает? Что выведется на экран?"

Запустив код в консолях Chrome и Mozilla в строгом режиме, я увидел следующее: 
=> TypeError: Cannot create property 'test' on string 'Привет'

В самой главе написано: 
"Получается, что примитивы могут предоставлять методы, и в то же время оставаться «лёгкими».

Движок JavaScript сильно оптимизирует этот процесс. Он даже может пропустить создание специального объекта. Однако, он всё же должен придерживаться спецификаций и работать так, как будто он его создаёт."

Я это понял так: оптимизация позволяет не создавать объект при вызове на строке <code>str.test = 5; </code>, в нестрогом режиме это работает, а строгий ругается. 
Но в главе написано: 
"В момент обращения к свойству str создаётся «объект-обёртка».
В строгом режиме, попытка изменения этого объекта выдаёт ошибку."

Проясните пожалуйста этот момент.

**Comment by Alexandre887** [comment]
Так как

**Comment by Alexandre887** [comment]
Так как прошло уже более года с момента публикации данной issue, полагаю, что эта тема для вас больше неактуальна и я могу закрыть её. 
Во всяком случае — если появятся какие-либо непонятности, трудности, — обращайтесь на официальный Discord-сервер [learn.javascript.ru](https://learn.javascript.ru) (приглашение на него есть на главной странице сайта, справа). Github предназначен для обсуждения самого проекта — опечатки в тексте, неточности, дополнения материала, и т.д.
