### ISSUE TITLE
Есть ли планы на Typescript ?

### ISSUE THREAD

**Issue by fellz** [javascript-tutorial/ru.javascript.info#1225]
Привет, учебник по JS стал де факто стандартом для изучения языка, однако сейчас многие проекты переезжают на Typscript и, вероятно, через несколько лет останется только Typescript в подавляющем кол-ве проектов. Есть ли планы сделать учебник по Typescript ? @iliakan

**Comment by iliakan** [comment]
А нужен? Может быть, есть хорошие учебники уже на русском или английском?

**Comment by fellz** [comment]
> А нужен? Может быть, есть хорошие учебники уже на русском или английском?

Такого уровня как ваш ресурс, не видел. На сайте https://www.typescriptlang.org/docs есть доки, но они на английском, без задач и по уровню контента попроще, чем learn.javascript.ru. Можно устроить голосование.

**Comment by iliakan** [comment]
Давайте внимательно посмотрим, что есть. 

Мы можем сделать учебник, если он реально нужен.

**Comment by fellz** [comment]
> Давайте внимательно посмотрим, что есть.
> 
> Мы можем сделать учебник, если он реально нужен.

Я посмотрел внимательно, что выдает по 'typescript' и 'typescript tutorial' google- ничего более толкового, чем https://www.typescriptlang.org/docs/ не нашел. Разве что вот этот https://www.typescripttutorial.net, но там нет задачек и версионности ( ссылки на гитхаб), то есть материал может просто устареть.
Предлагаю сделать заготовку типа javascript.info, назвать typescript.info ( learn.typescript.ru) и добавить задачки к теоретическому материалу, посмотреть, как публика это все воспримет. Готов поучаствовать в наполнении контентом в каком то объеме ( будет зависеть от свободного времени). @iliakan

**Comment by iliakan** [comment]
@igornepipenko

**Comment by fellz** [comment]
@iliakan коллега ваш молчит, вы что-то решили уже Илья )?

**Comment by iliakan** [comment]
@fellz Интерес есть. Можем обсудить подробно и сделать такой проект, если вы готовы активно такой учебник писать.

**Comment by fellz** [comment]
> @fellz Интерес есть. Можем обсудить подробно и сделать такой проект, если вы готовы активно такой учебник писать.
Я надеюсь все же на вашу помощь ) и поэтому слово вы, заменил бы на мы... У меня есть время на выходных пока что, мог бы в это время и добавлять по топику ( 1 или 2 топика за выходные).

**Comment by iliakan** [comment]
Какой будет план учебника (оглавление)?

**Comment by iliakan** [comment]
Мой телеграм iliakan

**Comment by iliakan** [comment]
Закрыто по неактивности.
