### ISSUE TITLE
Базовые операторы, математика

### ISSUE THREAD

**Issue by Den0702** [javascript-tutorial/ru.javascript.info#1229]
https://learn.javascript.ru/operators#prisvaivanie-po-tsepochke
![ice_screenshot_20210216-181910](https://user-images.githubusercontent.com/30319035/108098399-9a7f6900-7083-11eb-8a89-4fb4fdc9670f.png)

a = **b**, а не c

**Comment by TravellerOnline** [comment]
OMG, какая разница

**Comment by Alexandre887** [comment]
Не думаю, что ваша правка целесообразна, т.к к концу выполнения данного кода все три переменные всё равно будут иметь одинаковые значения.
