### ISSUE TITLE
Под ссылкой нет страницы

### ISSUE THREAD

**Issue by LawyerLawyer** [javascript-tutorial/ru.javascript.info#1231]
Типы данных
Строки
В абзаце ниже есть ссылка на страницу MDN, но такая страница отсутствует. Выделил ссылку жирным текстом.

Обратные кавычки также позволяют задавать «шаблонную функцию» перед первой обратной кавычкой. Используемый синтаксис: func`string`. Автоматически вызываемая функция func получает строку и встроенные в неё выражения и может их обработать. Подробнее об этом можно прочитать **в документации**. Если перед строкой есть выражение, то шаблонная строка называется «теговым шаблоном». Это позволяет использовать свою шаблонизацию для строк, но на практике теговые шаблоны применяются редко.

**Comment by Alexandre887** [comment]
Исправлено.
