### ISSUE TITLE
Опечатка на странице описание курса Vue.js

### ISSUE THREAD

**Issue by invinsible** [javascript-tutorial/ru.javascript.info#1234]
В блоке Курсовой проект опечатка в слове 'управление'.

Сейчас на сайте: 'Работа с формами: генерация, управлеине, свои интерфейсы.'
https://learn.javascript.ru/courses/vue

**Comment by Alexandre887** [comment]
### Исправлено:

![image](https://user-images.githubusercontent.com/74434545/187051730-5f4dfb59-bd36-4198-a847-7ae1925584db.png)
