### ISSUE TITLE
Возможно стоит изменить пример в статье про декораторы

### ISSUE THREAD

**Issue by MaxMls** [javascript-tutorial/ru.javascript.info#1235]
https://learn.javascript.ru/call-apply-decorators#method-borrowing

```
function hash() {
  alert( [].join.call(arguments) ); // 1,2
}

hash(1, 2);
```
на

```
function hash() {
  alert( Array.prototype.join.call(arguments) ); // 1,2
}

hash(1, 2);
```

Данный подход исключает создание лишнего неиспользуемого массива

**Comment by Alexandre887** [comment]
Насчёт создания лишнего неиспользуемого массива — вы правы, второй вариант больше бы подошел в этом случае. Только есть одно «но» — план изучения материала в учебнике построен таким образом, что в статьях используются только те языковые возможности, которые были описаны в учебнике ранее (в предыдущих главах, либо описываются в текущей статье). 

В конкретно этом примере используется массив, который был [описан ранее](https://learn.javascript.ru/array); используется метод .join(), который был [описан ранее](https://learn.javascript.ru/array-methods); используется `.call`, который описывается в текущей статье; и также используется псевдомассив arguments, который был [описан ранее ](https://learn.javascript.ru/rest-parameters-spread-operator#the-arguments-variable)в учебнике.

С [прототипами](https://learn.javascript.ru/prototypes) читатель познакомится только через один раздел, поэтому в указанной статье воспользоваться `Array.prototype` мы не можем.
