### ISSUE TITLE
https://learn.javascript.ru/logical-operators - Проверка логина - некорректное решение

### ISSUE THREAD

**Issue by spiderVS** [javascript-tutorial/ru.javascript.info#1236]
Решение задачи "Проверка логина", как мне кажется, не совсем верно.
Условие: 
_" Пароль проверять так:
    Если введён пароль «Я главный», то выводить «Здравствуйте!»,
    Иначе – «Неверный пароль»,
    При отмене – «Отменено»."_ 

<pre>
if (pass == 'Я главный') {
    alert( 'Здравствуйте!' );
  } else if (pass == '' || pass == null) {
    alert( 'Отменено' );
  } else {
    alert( 'Неверный пароль' );
</pre>

В данном случае пустая строка <code>pass == ''</code> не является условием для вывода "Отменено". При пустой строке должно выводится сообщение "Неверный пароль".

**Comment by spiderVS** [comment]
Моё решение:
```
if (pass == 'Я главный') {
    alert( 'Здравствуйте!' );
  } else if (pass == '') {
    alert( 'Неверный пароль' );
  } else if (pass == null) {
    alert( 'Отменено' );
	} else {
		alert( 'Неверный пароль' );
		}
```

**Comment by Alexandre887** [comment]
> Если посетитель вводит «Админ», то `prompt` запрашивает пароль, <ins>**если ничего не введено или нажата клавиша <kbd>Esc</kbd>**</ins> – показать «Отменено», в противном случае отобразить «Я вас не знаю».

Под «ничего не введено» подразумевается пустая строка `""`, т.е пользователь ничего не записал в `prompt` и нажал «Ок»
