### ISSUE TITLE
Ошибка: Преобразование типа из нуля

### ISSUE THREAD

**Issue by OlegOrlovskiy** [javascript-tutorial/ru.javascript.info#1247]
В Блоке “основы JS - преобразование типов» в  конце темы в Итого в логическом преобразовании ошибка в таблице:
0, null, undefined, NaN, "" - false
Пени нуле будет true

**Comment by TravellerOnline** [comment]
что такое "пени нуле"????

**Comment by Permogortsev** [comment]
!!0 - false / Boolean(0) - false
В чем ошибка?? где там true, и что еще за 'Пени нуле'???

**Comment by Alexandre887** [comment]
Некорректная issue, вынужден закрыть.
