### ISSUE TITLE
https://learn.javascript.ru/types-intro

### ISSUE THREAD

**Issue by portowyi** [javascript-tutorial/ru.javascript.info#1252]
https://learn.javascript.ru/types-intro
В секции ИТОГО:
Есть 5 «примитивных» типов: number, string, boolean, null, undefined и 6-й тип – объекты object.
Статья изменена, секция итого нет - все таки уже 7 "примитивных" типов, нужно добавить Symbol и bigint.

**Comment by ruslauz** [comment]
Устаревшая версия страницы.
