### ISSUE TITLE
Функции: разница между параметрами и аргументами

### ISSUE THREAD

**Issue by Shamann** [javascript-tutorial/ru.javascript.info#1268]
В главе [Функции](https://learn.javascript.ru/function-basics#parametry) сказано:

> Мы можем передать внутрь функции любую информацию, используя параметры (также называемые аргументами функции).

Строго говоря, есть разница в определениях параметров и аргументов функции:
* https://developer.mozilla.org/en-US/docs/Glossary/Parameter
* https://codeburst.io/parameters-arguments-in-javascript-eb1d8bd0ef04

Возможно, в текст учебника стоит внести поясняющее дополнение или переписать процитированное предложение.

**Comment by Alexandre887** [comment]
Спасибо за замечания — уточнения были добавлены:

![Screenshot](https://user-images.githubusercontent.com/74434545/199287327-00a5fa35-6bea-4422-95b6-1f0fe1a05e1b.png)
