### ISSUE TITLE
Ошибка в тесте Язык JavaScript

### ISSUE THREAD

**Issue by DjailinVasu** [javascript-tutorial/ru.javascript.info#1270]
Столкнулась с небольшой ошибкой при прохождении тестов.  Дальше все понятно по скринам:
![image](https://user-images.githubusercontent.com/49210736/116078979-f546c980-a69f-11eb-933f-95edd49912d8.png)

![image](https://user-images.githubusercontent.com/49210736/116079710-ce3cc780-a6a0-11eb-9a80-c6a1d0d57153.png)

___________________

Life вызов все равно происходит в задуманном месте кода, после создания переменной с let. 

P.S.: Огромное спасибо за вашу работу!

**Comment by TravellerOnline** [comment]
там же написано посмотрите на пример внимательно!
после объявление массива нет точки с запятой, поэтому получается []( function(){} )() , массив функцией не является, поэтому будет ошибка

**Comment by DjailinVasu** [comment]
> там же написано посмотрите на пример внимательно!
> после объявление массива нет точки с запятой, поэтому получается () , массив функцией не является, поэтому будет ошибка

Хах. Спасибо)) Блин, вдвоем смотрели тут и не видели. Разработчики блин. И главное тестили, и везде на автомате сами проставляли эту точку с запятой. Круто конечно)
