### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by damir7287** [javascript-tutorial/ru.javascript.info#1273]
В статье учебника приводится 2 примера кода,первый при объяснении работы директивы continue,должен выводить только нечётные числа,второй в задачах только четные,я не могу понять,ведь они по сути одинаковые,сломал себе голову,подскажите в чем разница,почему один выводит нечётные,а второй четные?
Вот примеры:
1) выводит нечётные for (let i = 0; i < 10; i++) { if (i % 2) { alert( i ); } }
2) выводит четные for (let i = 2; i <= 10; i++) { if (i % 2 == 0) { alert( i ); } }

**Comment by ilyachalov** [comment]
Ну вы нашли место для такого вопроса... Вообще, здесь пишут про ошибки в учебнике. Этот вопрос нужно было задать в комментариях от Disqus на сайте или на форуме сайта учебника. Я бы на вашем месте закрыл бы здесь эту тему.

По сути вопроса:

Вам нужно понять, как работает операция (i % 2), она возвращает остаток от деления. Например:

0 % 2 = 0
1 % 2 = 1
2 % 2 = 0
3 % 2 = 1
4 % 2 = 0
5 % 2 = 1
и так далее

Как видно из этого примера, эта операция возвращает число 1 в случае нечетных чисел и число 0 — в случае четных. В первом случае из двух описанных вами условие if (i % 2) примет значение true (истина) только для нечетных чисел, поэтому на экран будут выведены только они. Во втором случае условие if (i % 2 == 0) примет значение true (истина) только для четных чисел и на экран выведутся только они.
