### ISSUE TITLE
Неточность в главе 2.7 "Преобразование типов"

### ISSUE THREAD

**Issue by AlexShyshko** [javascript-tutorial/ru.javascript.info#1291]
При описании численного преобразования string не упоминается обрезание символов "\n" и "\t" в начале и в конце строки.  От этого задача на преобразование типов из следующей главы 2.8 "Базовые операторы, математика" вгоняет в ступор своим 15 пунктом.
![2 7](https://user-images.githubusercontent.com/82448723/118272031-b2bc2400-b4ca-11eb-96ae-0514b752541f.jpg)
![2 8](https://user-images.githubusercontent.com/82448723/118272032-b3ed5100-b4ca-11eb-94a8-6313632bbfb2.jpg)

**Comment by ilyachalov** [comment]
Понятие «пробельный символ» включает в себя не только пробел, но и перенос строки, и горизонтальную табуляцию. Так что в учебнике тут всё правильно написано.

Другое дело, что, возможно, в этом подразделе учебника авторам стоило бы подробно остановиться на том, что такое «пробельный символ», чтобы не было таких вопросов.

**Comment by AlexShyshko** [comment]
Спасибо за разъяснение
