### ISSUE TITLE
Опечатка в разделе События указателя

### ISSUE THREAD

**Issue by aschyolokov** [javascript-tutorial/ru.javascript.info#1295]
Опечатка на странице https://learn.javascript.ru/pointer-events в блоке Итого.

_При обработке переносов и сложных касаний, которые браузер может попытаться обработать сам, не забывайте отменять действие браузера и ставить `touch-events: none` в CSS для элементов..._

Вместо **touch-events** должно быть **touch-action**.

**Comment by Alexandre887** [comment]
Добрый вечер. Спасибо за помощь, опечатка исправлена.
