### ISSUE TITLE
Клавиатура: keydown и keyup

### ISSUE THREAD

**Issue by Den0702** [javascript-tutorial/ru.javascript.info#1301]
Здравствуйте, 
в [этой](https://learn.javascript.ru/keyboard-events) статье 
![image](https://user-images.githubusercontent.com/30319035/119158047-15c33300-ba56-11eb-883f-c5b6b683056b.png)
здесь необходимо писать: "А что если клавиша **не буквенная или цифровая**". Потому что F1 это как раз клавиша буквенно-цифровая, не так ли?

**Comment by TravellerOnline** [comment]
нет, ты не прав
есть буквенно-цифровые клавиши, и F1  к ним не относится
https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%8F_%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D0%B0

**Comment by Alexandre887** [comment]
К **буквенно-цифровым** клавишам относятся клавиши, предназначенные для ввода _букв, цифр, знаков пунктуации (; : " , .), символов основных арифметических операций (+, -, =), а также некоторых специальных символов_.

Клавиши от `F1` до `F12`, в свою очередь, относятся к категории **функциональных** клавиш.
