### ISSUE TITLE
Тесты знаний. Существует ли такое значение X, что после присваивания a = X вызов alert(a == X) выдаст false?

### ISSUE THREAD

**Issue by ivanchurkin** [javascript-tutorial/ru.javascript.info#1303]
Добрый день! Вопрос, наверное, к @iliakan.

В первую очередь, хочется сказать спасибо, что нет пояснений в самих «карточках» это мотивирует на поиск ответа и изучение темы глубже. Но для меня исключением стал следующий вопрос:

<img width="799" alt="Screen Shot 2021-05-22 at 19 52 48" src="https://user-images.githubusercontent.com/9108717/119234641-ac1b5580-bb37-11eb-8b2b-55f6e56537de.png">

Возможно, я усложняю, но я мыслю следующим образом:

 ```js
let X = {{ здесь должно быть значение }};
let a = X;
alert( a == X ); // false
 ```

Или всё проще и автор имел ввиду следующее?

 ```js
let a = [];
alert( a == [] ); // false
 ```

Если всё-таки первый вариант, то я продолжу поиск.

**Comment by iliakan** [comment]
NaN?

**Comment by ivanchurkin** [comment]
> NaN?

Блин, не внимательно читал. Спасибо!

Оставлю здесь:
https://learn.javascript.ru/comparison

> NaN – это специальное числовое значение, которое возвращает false при любых сравнениях.
