### ISSUE TITLE
Опечатка на странице покупки учебника

### ISSUE THREAD

**Issue by lattelix** [javascript-tutorial/ru.javascript.info#1304]
Адрес страницы для скорости)
Сама опечатка:
![image](https://user-images.githubusercontent.com/65864204/119239339-1391cf00-bb51-11eb-9a50-cd95f113b0fb.png)
незачем, обращайтесь..

**Comment by lattelix** [comment]
Beginning issue

**Comment by DemX86** [comment]
Прошло больше двух месяцев, а опечатка на коммерческой странице так и не исправлена.
В моё желание приобрести платный курс начинают закрадываться сомнения…

**Comment by lattelix** [comment]
А ведь всего лишь опечатка..

**Comment by NazarCoder** [comment]
действительно, опечатка.
