### ISSUE TITLE
Proxy и Reflect

### ISSUE THREAD

**Issue by Igor492** [javascript-tutorial/ru.javascript.info#1310]
Защищенньіе свойства с ловушкой "deleteProperty" и другими

Касательно идеи, что метод самого об'ьекта должен иметь доступ к свойству  _password:

((((   в  месте кода с ловушкой GET привязка к контексту value.bind(target) расположена в блоке ELSE. Значит, контекст привязьівается для свойств, не начинающихся с подчеркивания. То есть, предполагаемое обращение собственного метода user.checkPassword() в етом случае происходит к обьічньім незащищенньім свойствам. Для корректности изложения идеи следует расположить проверку typeof и привязку value.bind(target) в начальном блоке IF ловушки GET (блоке обработки свойств с подчеркиванием), а не в блоке ELSE (обработка свойств без подчеркивания)  ))))

ИЗВИНЯЮСЬ, НЕ РАЗОБРАЛСЯ. В ЕТОМ СЛУЧАЕ ИМЯ МЕТОДА И ПРИНИМАЕТСЯ КАК ИМЯ СВОЙСТВА (и, следовательно, начинаясь не с подчеркивания, попадает, как и нужно, во второй блок ELSE)

**Comment by TravellerOnline** [comment]
1)при вызове метода user.checkPassword() идет сначала обращение к user.checkPassword, и срабатывает ловушка get
2) возвращается функция с фиксированным оригинальным объектом user в роли контекста
3) эта функция вызывается
4) внутри функции обращаемся к this._password, где this === оригинальный объект (не прокси), поэтому ловушка get повторно не срабатывает

если разобрался, закрывай тему
