### ISSUE TITLE
ошибка в коде в примере (функции)

### ISSUE THREAD

**Issue by RomanNV** [javascript-tutorial/ru.javascript.info#1338]
function showPrimes(n) {

  for (let i = 2; i < n; i++) {
    if (!isPrime(i)) continue;

    alert(i);  // простое
  }
}

function isPrime(n) {
  for (let i = 2; i < n; i++) {
    if ( n % i == 0) return false;
  }
  return true;
}
Этот код не работает, во второй функции вместо i надо вставить другую переменную, например j

**Comment by TravellerOnline** [comment]
все работает!
циклы вообще в разных функциях, можно спокойно использовать одну переменную
