### ISSUE TITLE
Координаты относительно окна: getBoundingClientRect

### ISSUE THREAD

**Issue by Chambo015** [javascript-tutorial/ru.javascript.info#1351]
в [Координаты относительно окна: getBoundingClientRect](https://learn.javascript.ru/coordinates#koordinaty-otnositelno-okna-getboundingclientrect)
(могут быть отрицательными)  top/bottom
а не width/height

**Comment by TravellerOnline** [comment]
width/height могут быть отрицательными
прочитайте еще раз лекцию..
