### ISSUE TITLE
Стрелочные функции не имеют «arguments»

### ISSUE THREAD

**Issue by EvgeniySaschenko** [javascript-tutorial/ru.javascript.info#1361]
Добрый день,
Если при вызове `sayHiDeferred("John")` не передать `window`, то "use strict" режиме, вместо `this` будет `undefined`.
Можно заменить на такой вызов `sayHiDeferred.apply(window, ["John"])`.

[https://learn.javascript.ru/arrow-functions#strelochnye-funktsii-ne-imeyut-arguments](https://learn.javascript.ru/arrow-functions#strelochnye-funktsii-ne-imeyut-arguments)

```
function defer(f, ms) {
  return function() {
    setTimeout(() => f.apply(this, arguments), ms)
  };
}

function sayHi(who) {
  alert('Hello, ' + who);
}

let sayHiDeferred = defer(sayHi, 2000);
sayHiDeferred("John");
```

```
function defer(f, ms) {
  return function(...args) {
    let ctx = this;
    setTimeout(function() {
      return f.apply(ctx, args);
    }, ms);
  };
}

```

**Comment by TravellerOnline** [comment]
1) this в браузере ссылается на window, в другой среде выполнения может быть undefined
2) даже если this === undefined внутри функции(вызвана в глобальном контексте), ничего страшного, это значит, что в этой функции скорее всего нам контекст не нужен и this не используется.  Логично предположить, что когда в функции используется this, тогда функция будет вызываться в контексте конкретного объекта и контекст будет важен
3) нет смысла передавать window как контекст куда-либо, его свойства/методы и так видны в любой точке программы
