### ISSUE TITLE
Две части учебника не загружаются в Google Play Books с ошибкой Processing Failed

### ISSUE THREAD

**Issue by eyenalxai** [javascript-tutorial/ru.javascript.info#1371]
Пробовал загружать как с телефона, так и через сайт с десктопа. 
С другими книгами таких проблем не было еще 😕

В Apple Books все хорошо.
![yikes](https://user-images.githubusercontent.com/40147710/128927123-cd3cde9a-3748-4719-9f1b-734e82e6f41b.png)

**Comment by Alexandre887** [comment]
Здравствуйте. Проблема еще актуальна?
