### ISSUE TITLE
SameSite cookies have default value Lax

### ISSUE THREAD

**Issue by doctorvanya** [javascript-tutorial/ru.javascript.info#1372]
Inside chapter [Cookies, document.cookie](https://javascript.info/cookie) is written:

> **samesite=strict (same as samesite without value)**

This behaviour was changed inside new browsers.
The cookie is sending SameSite=Lax if it wasn't specified. 

- [SameSite cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)
- [Updated for SameSite](https://www.chromium.org/updates/same-site)

**Comment by Alexandre887** [comment]
Hi. Please send this issue to the [repository of the English version of the tutorial.](https://github.com/javascript-tutorial/en.javascript.info)
