### ISSUE TITLE
Неверный перевод 

### ISSUE THREAD

**Issue by anastasia-son** [javascript-tutorial/ru.javascript.info#1376]
https://learn.javascript.ru/private-protected-properties-methods
В блоке, который начинается на "Защищённые поля наследуются" неверный перевод. Не методы, а поля (см. скриншот).

![image](https://user-images.githubusercontent.com/45445714/129834183-9d801154-c310-4d94-920d-2c3997d1e362.png)

**Comment by ruslauz** [comment]
@anastasia-son создайте пожалуйста ПР
