### ISSUE TITLE
Замечение по примеру с четными числами

### ISSUE THREAD

**Issue by MhSav** [javascript-tutorial/ru.javascript.info#1386]
В указанном примере логичнее и эффективнее делать такой инкремент в цикле: i+=2

**Comment by Alexandre887** [comment]
На будущее — если открываете issue касательно материала в этом учебнике, обязательно указывайте статью и раздел в статье, чтобы issue могла быть рассмотрена. Сейчас же непонятно, о чем собственно идет речь, поэтому закрываю эту тему.
