### ISSUE TITLE
Книга пдф js

### ISSUE THREAD

**Issue by IrshatS** [javascript-tutorial/ru.javascript.info#1394]
Спасибо за книгу приобрел две части.
Из пожеланий: при распечатке обнаружил что нет нумерации страниц.
Желательно бы пронумеровать страницы.

**Comment by Alexandre887** [comment]
### Нумерация присутствует:

![image](https://user-images.githubusercontent.com/74434545/187094797-ef148bc7-efef-4dab-b799-ae9cb3459a00.png)
