### ISSUE TITLE
не нашёл информацию

### ISSUE THREAD

**Issue by lgick** [javascript-tutorial/ru.javascript.info#1396]
Здравствуйте!

В учебнике на странице

https://learn.javascript.ru/object-methods#sokraschyonnaya-zapis-metoda

написано про сокращенную и обычную записи методов объекта:

"Нужно отметить, что эти две записи не полностью эквивалентны. Есть тонкие различия, связанные с наследованием объектов (что будет рассмотрено позже), но на данном этапе изучения это неважно. В большинстве случаев сокращённый синтаксис предпочтителен."

так чем же они отличаются? Не нашёл информацию в учебнике

**Comment by mikitachyzhyk** [comment]
Плохо искал) Вот:
https://learn.javascript.ru/class-inheritance#metody-a-ne-svoystva-funktsii
