### ISSUE TITLE
Психологическое восприятие примера "Недостижимый остров" учебника

### ISSUE THREAD

**Issue by Wulf305** [javascript-tutorial/ru.javascript.info#1403]
Добрый день. Прошу прощения заранее, но считаю некорректным пример с удалением понятия "family" в параграфе "управление памятью" в учебнике. Язык - не только способ описания данных и способ информационного обмена, язык прежде всего - способ мышления того, кто использует его. Программист изучающий JS спокойно воспринимает такой пример, для мозга он помечается как нормальный, далее начинается габитуация этого представления с общежитейской логикой, т.е. происходит процесс организации нейронов таким образом, что они объединяются в устойчивые цепочки по понятиям, одновременно с этим получается, что такой пример, воспринимаемый корректно запечатлевается мозгом, суммируясь с нейронным облаком представления о семье. Можно как-нибудь поменять "family" на что-то другое?

**Comment by NazarCoder** [comment]
Классный троллинг)

**Comment by Wulf305** [comment]
Это не троллинг, а вопрос этики. Представьте себе азбуку, в которой будет пример "Уберем понятие "семья" - убьём все семьи, а трупы сложим в кучку". Для мозга нет разницы между классами входной информации, а этот пример воспринимается программистами, изучающими это учебное пособие нормально. Следовательно, через некоторое время мозг прекратит фильтрацию такого действия, как негативный образец, затем начнёт объединять нейроны с нейротрансмиссией образцов социального поведения. Данный учебник подлежит чтению и рецензированию специалистов по профессиональной этике, в комиссию из которых уже направлен запрос на наложение вето на это пособие.

**Comment by NazarCoder** [comment]
хорошо, но врядли в учебнике это исправят. Авторы учебника не обратят внимания на такую "мелочь".
