### ISSUE TITLE
Тестирование знаний (DOM, работа на странице)

### ISSUE THREAD

**Issue by soulshon** [javascript-tutorial/ru.javascript.info#1407]
При прохождении теста: выглядит как опечатка, если смотреть через (ul li .length) то получим ответ 2... Можете предоставить развернутый ответ по  данному вопросу пожалуйста, в случае если это не опечатка.
![IMG_20211005_120743_675](https://user-images.githubusercontent.com/73664330/135994357-2f4464c9-9fdd-4cdf-a310-dfe57db78cc4.jpg)

**Comment by TravellerOnline** [comment]
Вас спрашивают количество не элементов, а узлов (nodes). Это разные вещи
а узлов там действительно 5
