### ISSUE TITLE
Неточности в статье "Автоматическое тестирование c использованием фреймворка Mocha"

### ISSUE THREAD

**Issue by lazo77** [javascript-tutorial/ru.javascript.info#1416]
Понятно, что статья не об этом и общий смысл данные неточности не искажают, но в таком замечательном проекте как ваш думаю им не место (особенно там где идет проверка целое или дробное, а результат от проверки число - не число)

![screenshot](https://user-images.githubusercontent.com/29665074/138248194-28c256f2-8af3-414f-958b-482e6d5176e0.jpg)
![screenshot (1)](https://user-images.githubusercontent.com/29665074/138248191-6e1a8a9a-58a0-4075-af22-a49856815576.jpg)
![screenshot (2)](https://user-images.githubusercontent.com/29665074/138248186-246f46d9-1652-475d-b2ed-769d27be3eed.jpg)

**Comment by OKitel** [comment]
https://github.com/javascript-tutorial/ru.javascript.info/pull/1408/files
