### ISSUE TITLE
Уточнение в статье Map and Set

### ISSUE THREAD

**Issue by SymphonyNineth** [javascript-tutorial/ru.javascript.info#1420]
https://learn.javascript.ru/map-set#map
Можно сразу вначале статьи указать, что new Map() принимает Iterable object, как это сделано в секции "Итого"
![Screenshot 2021-10-28 1 01 49 PM](https://user-images.githubusercontent.com/63275027/139224196-7584aa69-d93b-41f0-beab-820c4597c2bc.png)
 
![Screenshot 2021-10-28 1 02 13 PM](https://user-images.githubusercontent.com/63275027/139224192-d475c9f9-b318-4fd9-b2cd-1207ad9f22bb.png)

**Comment by ashtaev** [comment]
+1
