### ISSUE TITLE
Неверно указан правильный ответ на вопрос квиза "Что выведет alert?"

### ISSUE THREAD

**Issue by alexvlife** [javascript-tutorial/ru.javascript.info#1425]
В квизе для вопроса "Что выведет alert?":

> let str = "Hello";
> str.something = 5;
> alert(str.something); // ?

Cайт показывает правильный ответ 'Будет ошибка.' (см. скрин ниже)
https://github.com/javascript-tutorial/ru.javascript.info/blob/34065d746c26b89d315af0cb5a4205db946c5734/quiz/quiz-js.yml#L472

Но, в таком кейсе ошибки не будет. В данном случае переменная объявлена и ей присвоено значение (строка). У строк имеются методы. А если обращаться к свойствам или методам, которых не существует, то результатом будет undefined, а не ошибка.

![image](https://user-images.githubusercontent.com/32933888/139654898-c67a7d5f-9d20-409e-8ba2-f6a57531f472.png)

**Comment by TravellerOnline** [comment]
ошибка будет, редакторы кода подтверждают
консоль работает без use strict, поэтому и ответ неточный
вруби use strict  и увидишь ошибку

**Comment by ruslauz** [comment]
Да, примеры по умолчанию подразумевают строгий режим к сожалению явно это не указано.

**Comment by iliakan** [comment]
Да, всего лишь большими буквами до начала тестов сказано.

**Comment by iliakan** [comment]
Надо в каждом таком вопросе - в ответе прописывать явно.
