### ISSUE TITLE
Тёмная тема 🌚

### ISSUE THREAD

**Issue by LeBrick-Studio** [javascript-tutorial/ru.javascript.info#1442]
Заголовок описывает проблему на 2000%. 

Ночью чёрный текст на белом фоне читать, мягко говоря, _неприятно_, а все существующие тёмные темы либо заброшены, либо делают часть контента нечитабельной (в случае с аддонами типа Dark Reader)

**Comment by kilokid** [comment]
согласен на все 100000%

**Comment by NazarCoder** [comment]
+

**Comment by Kramgres** [comment]
Темная тема уже есть на сайте

**Comment by LeBrick-Studio** [comment]
Спасибо! :)
