### ISSUE TITLE
Темная тема

### ISSUE THREAD

**Issue by HukakHePak** [javascript-tutorial/ru.javascript.info#1447]
День добрый, господа! Наверняка вам уже известно (а может и нет ( а может и я что-то не сильно понимаю)), что темная тема очень приятна для посиделок за ноутбуком в кромешной тьме. А еще лучше, когда читаешь что-то познавательное в это время. Как вы относитесь к идее добавить это на сайт? 
А еще, было бы классно, если бы была возможность скрывать комментарии других пользователей. 
В любом случае, спасибо за ваш труд <3

**Comment by Kramgres** [comment]
Темная тема уже есть на сайте
