### ISSUE TITLE
Иконки в мобильной версии(старый браузер хромовского типа)

### ISSUE THREAD

**Issue by Den0702** [javascript-tutorial/ru.javascript.info#1453]
Добрый день,

у меня недавно в мобильной версии сайта пропали иконки(типа информация), восклицательный знак в оранжевом треугольнике, иконка выпадающего меню, и иконки запуска примеров. Возможно ли это исправить? В принципе сайт работает те при нажатии кнопки работают. И фон иконок(hover) иконки видны при нажатии

**Comment by Den0702** [comment]
Одна кнопка все-таки не работает - кнопка аккаунта. Она как-бы нажимается, но страница аккаунта не загружается

**Comment by Alexandre887** [comment]
Добрый вечер. Проблема еще актуальна?
