### ISSUE TITLE
9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags

### ISSUE THREAD

**Issue by drDramen** [javascript-tutorial/ru.javascript.info#1454]
сказано:

>Не может быть: [b][b]текст[/b][/b]

Но в ответе регулярка не выполняет это условие.

---

И если взять за исходник такую строку:
`"[quote][quote]текст[/b]    [quote]  jkj [/quote]"`

на выходе получим` "[quote]текст[/b]    [quote]  jkj [/quote]"`, а логично бы получить
`"[quote]  jkj [/quote]" `
Но это уже как бы мелочи.

**Comment by Alexandre887** [comment]
> BB-коды могут быть вложенными. Но сам в себя тег не может быть вложен, например:

Речь идёт не о требованиях к результирующей регулярке, а о «функционале» самого BBCode. Он попросту не допускает существование вложенных в самих себя тегов, таких как `[b][b][/b][/b]` и т.п.
Это означает, что регулярка не должна учитывать подобные конструкции и работать с ними корректно. 

В описании всё написано правильно, правки не требуются.
