### ISSUE TITLE
Неправильно подано информация (Исправить информацию)

### ISSUE THREAD

**Issue by ruzadorov** [javascript-tutorial/ru.javascript.info#1461]
https://learn.javascript.ru/closure#funktsiya-v-if

В этом задаче код который вы написали работает нормально!

Но если вместо: function sayHi(){}
Поставить: let sayHi = () => {}  или let sayHi = function() {} 
То оно выдаст ошибку

Исправьте это, пожалуйста, для будущих читателей

**Comment by ruslauz** [comment]
Все верно, sayHi доступна вне блока if.

**Comment by TravellerOnline** [comment]
> Все верно, sayHi доступна вне блока if.

Все в учебнике верно, функция не видна вне блока if, не вводите людей в заблуждение
А когда проверяете код, не забывайте указывать 'use strict'

**Comment by ruslauz** [comment]
Скопируйте код из примера и запустите его в консоле хотя бы. В примере нет use strict, в том варианте, что он указан в примере функция доступна вне блока.

**Comment by TravellerOnline** [comment]
Вам нужно перечитать лекцию про use strict
Вырезки из нее:
++++
В дальнейшем, когда вы будете использовать консоль браузера для тестирования функций, обратите внимание, что use strict по умолчанию в ней выключен.

Все примеры в этом учебнике подразумевают исполнение в строгом режиме, за исключением случаев (очень редких), когда оговорено иное.
++++

**Comment by ruslauz** [comment]
Спасибо. Вы правы, этот момент я упустил.
