### ISSUE TITLE
Проблема с отображением текста в демках.

### ISSUE THREAD

**Issue by n4ks** [javascript-tutorial/ru.javascript.info#1471]
Судя по всему в css переменной задан некорректный цвет текста, пример:
1. Открываем статью https://learn.javascript.ru/mutation-observer;
2. Запускаем первую демку с `<div contentEditable id="elem">Отредактируй <b>меня</b>, пожалуйста</div>;`
3. Меняем текст ("Отредактируй меня, пожалуйста");
4. Цвет текста в "консоли" сливается с фоном.
![image](https://user-images.githubusercontent.com/30715874/149478684-1b99585f-4c3d-4c8a-9a27-0bc8db4d4378.png)

Тестил в Chrome Version 97.0.4692.71 (Official Build) (64-bit) и Safari 15.2

**Comment by Alexandre887** [comment]
Исправлено:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/fd8470ad-6234-4add-97f1-5541770b6f94)
