### ISSUE TITLE
Приоритет оператора "??"

### ISSUE THREAD

**Issue by Artist109** [javascript-tutorial/ru.javascript.info#1476]
На странице https://learn.javascript.ru/nullish-coalescing-operator указано - https://prnt.sc/26hnp3p, но на MDN иной приоритет - https://prnt.sc/26hnpj9.

**Comment by alexeyinn** [comment]
> На странице https://learn.javascript.ru/nullish-coalescing-operator указано - https://prnt.sc/26hnp3p, но на MDN иной приоритет - https://prnt.sc/26hnpj9.

Спасибо за наводку. Исправлено - https://github.com/javascript-tutorial/ru.javascript.info/pull/1487

**Comment by ruslauz** [comment]
https://github.com/javascript-tutorial/ru.javascript.info/pull/1487
