### ISSUE TITLE
Регулярные выражения: Альтернация (или) |

### ISSUE THREAD

**Issue by YuriyGit** [javascript-tutorial/ru.javascript.info#1480]
В задаче №2 "Найдите пары BB-кодов" решение не соответствует условиям задачи. Предложенное регулярное выражение ( /\[(b|url|quote)].*?\[\/\1]/gs ) не решает проблеме одинаковых вложенных тегов ( [b][b]текст[/b][/b] )

**Comment by iliakan** [comment]
в условии явно сказано "сам в себя тег не может быть вложен"
