### ISSUE TITLE
Неверно указан тип вывода в задаче к уроку "Базовые операторы, математика"

### ISSUE THREAD

**Issue by FaninIS** [javascript-tutorial/ru.javascript.info#1483]
В решении последней задачи не верно указан тип вывода: число 12
, а должна быть строка со значением "12"

let a = "1"; // prompt("Первое число?", 1);
let b = "2"; // prompt("Второе число?", 2);

alert(a + b); // 12

**Comment by alexeyinn** [comment]
Принципе да, typeof a + b => 'string'
Но по факту, модальное окно alert'a выводит именно 12, а не '12'
Так что... не знаю.. считается это ошибкой, или нет...
