### ISSUE TITLE
Маленькое изменение в главе с циклами while and for

### ISSUE THREAD

**Issue by rnbsov** [javascript-tutorial/ru.javascript.info#1490]
На месте с табличкой изменить begin  **i = 0**, на **let i = 0** 

https://learn.javascript.ru/while-for#tsikl-for

### Вот место с таблицей из англиской версии
https://javascript.info/while-for#the-for-loop

**Comment by alexeyinn** [comment]
MR - https://github.com/javascript-tutorial/ru.javascript.info/pull/1494

**Comment by alexeyinn** [comment]
Изменения влиты на прод.
