### ISSUE TITLE
Правка разметки таблицы в "Циклы while и for"

### ISSUE THREAD

**Issue by alexeyinn** [javascript-tutorial/ru.javascript.info#1496]
В данной статье - https://learn.javascript.ru/while-for#tsikl-for , в пункте "Цикл 'for'", в таблице с разбором примера, после добавления 'let' во втором столбике, первого ряда, произошел перенос строки.
![Screenshot_1](https://user-images.githubusercontent.com/69390951/153023194-a19e4cca-c20c-408f-b942-a937ba4f288c.png)

**Comment by Alexandre887** [comment]
Исправлено:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/6bca69cb-f42e-494f-8c27-07264e74ff68)

Большое спасибо за обращение.
