### ISSUE TITLE
Отсутствие картинки

### ISSUE THREAD

**Issue by StaneKoz** [javascript-tutorial/ru.javascript.info#1530]
Уважаемые разработчики сайта,  обратите внимание на урок "Размеры и прокрутка элементов". В нём в абзаце с заголовком "clientTop/Left" отсутствуют поясняющие картинки. Эта проблема возникла не у меня одного. Если что, я использую браузер Opera.

**Comment by Rnbsov** [comment]
Спасибо, что сообщили 😀👍 
Если найдете еще что-нибудь, пишите

**Comment by iliakan** [comment]
Fixed!
