### ISSUE TITLE
2-ui/2-events/01-introduction-browser-events/article.md 

### ISSUE THREAD

**Issue by stas-dolgachov** [javascript-tutorial/ru.javascript.info#154]
Add translation for 2-ui/2-events/01-introduction-browser-events/article.md

**Comment by stas-dolgachov** [comment]
I have already started working on that.

**Comment by oonufrienko** [comment]
Hey :)
I have finished this article with all the tasks here https://github.com/javascript-tutorial/ru.javascript.info/pull/184

As you can see lex111 accepted to translate this article 13 days ago
![image](https://user-images.githubusercontent.com/17405483/57759972-76029a00-7703-11e9-9167-7c64c78df9d1.png)
