### ISSUE TITLE
Ошибка-опечатка 

### ISSUE THREAD

**Issue by KostinIlia** [javascript-tutorial/ru.javascript.info#1544]
Приветствую! 
У вас не правильно(опечатка ) указан синтаксис <code> element.addEventListener(event, handler[, options]); </code> Должно быть вот так:  <code> element.addEventListener(event, handler, [options]); </code> как в официальной документации на английском языке ( в переводе на MDN, также перевели с опечаткой). https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener   
Вот этот вот отрезок <code>handler, [options]</code> исправьте .
С наилучшими пожеланиями !

**Comment by KostinIlia** [comment]
https://learn.javascript.ru/introduction-browser-events#addeventlistener 
Ссылка на страницу учебника .

**Comment by Rnbsov** [comment]
Хорошая работа, спасибо 😃👍
