### ISSUE TITLE
Изменился приоритет операторов

### ISSUE THREAD

**Issue by aleksanderantropov** [javascript-tutorial/ru.javascript.info#1550]
Сложение - 13
Возведение в степень - 15
Унарный плюс - 16

**Comment by Rnbsov** [comment]
В какую статью нужно внести изменения?

**Comment by aleksanderantropov** [comment]
https://learn.javascript.ru/operators#prioritet-operatorov

**Comment by aleksanderantropov** [comment]
В соответствие с этой таблицей: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table

**Comment by aleksanderantropov** [comment]
И у оператора присваивания тоже вырос приоритет до 3. Это дальше упоминается в тексте статьи.

**Comment by Rnbsov** [comment]
Очень странно

 в английской документации MDN этих изменений нет

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

**Comment by aleksanderantropov** [comment]
Создал issue в MDN. Пока предлагаю или поменять ссылку на английскую версию или поменять текст в статье, чтобы не было расхождений

**Comment by Rnbsov** [comment]
Полагаю эту `issue` можно закрывать

Мне сообщили что эту проблему на mdn пофиксят, так что это уже не проблема учебника
