### ISSUE TITLE
Проблемы с отображением содержимого страниц на телефоне

### ISSUE THREAD

**Issue by JkloP93** [javascript-tutorial/ru.javascript.info#1576]
Кнопки оглавления и карты сайта мешают посмотрю содержимого страницы мобильной версии сайта. Телефон: honor 8x
![Screenshot_20220409_193145](https://user-images.githubusercontent.com/35508973/162583009-6910ef41-89ba-49f6-b3cd-e0999e266d8e.jpg)

**Comment by Alexandre887** [comment]
Проблема еще актуальна?
