### ISSUE TITLE
Объясните значение this. Альтернативное объяснение

### ISSUE THREAD

**Issue by Den0702** [javascript-tutorial/ru.javascript.info#1589]
Добрый день, хотел бы предложить альтернативное объяснение по поводу задания [Объясните значение this](https://learn.javascript.ru/object-methods#obyasnite-znachenie-this). И просил бы оценить правильность такого объяснения. Т.е это проба объяснения без вникания в нюансы ссылочного типа.

Пункт 3: `(method = obj.go)( )`;

Объяснение: Результат вызова метода `go( )` присваивается переменной `method`. В свою очередь, эта переменная ничего не возвращает(возвращает undefined)
![ice_screenshot_20220418-122307](https://user-images.githubusercontent.com/30319035/163795233-7208fd30-c03a-45b2-b833-2e25d2049a26.png)

Пункт 4: `(obj.go || obj.stop)( );`

Объяснение: Результатом вызова метода stop( ) является undefined, т.к. нет такого метода в объекте obj. В свою очередь, obj.go ничего не возвращает (возвращает undefined). В результате, выражение undefined || undefined возвращает undefined

**Comment by Alexandre887** [comment]
Здравствуйте.

Не уверен, что для вас эта issue всё еще актуальна (даже задача «Объясните значение this» уже была перенесена в новую статью «[Ссылочный тип](https://learn.javascript.ru/reference-type)»), но, всё равно отвечу.

Вы пишите: `Т.е это проба объяснения без вникания в нюансы ссылочного типа.` — без вникания в нюансы ссылочного типа объяснить поведение указанных двух выражений невозможно. Чтобы понимать, почему оба выражения в итоге приводят к `undefined`, нужно понимать, как работает ссылочный тип. Эта задача как раз про него. 

Оба ваши альтернативные решения — некорректные.


Каким образом при вызове метода объекта JavaScript понимает, что подставить вместо `this`? При вызове через точку `obj.method()` или квадратные скобки `obj[method]()`, возвращается не сама функция, а значение ссылочного типа. Как выглядит значение ссылочного типа:

### (объект, имя свойства, режим выполнения <с использованием "use strict" или без>)

Исходя из этого «набора», JavaScript может установить определенный `this` (`this` = объект). 

Какие выражения считаются «нормальными» и возвращают значение ссылочного типа:

1. `obj.method();`
2. `obj[method]();`
3. `(obj.method)();`

**Всё**. При использовании **абсолютно любых других выражений** внутри скобок, например, присваивания `(obj.method1 = obj.method2)()` или логических операторов `(obj.method1 || obj.method2)()`, `this` будет «потерян». Почему? Потому что при использовании любых других выражений, будет возвращено не значение ссылочного типа, а обычная функция. 

```javascript
function f() {
  alert(this) // в строгом режиме будет undefined, в нестрогом — объект window (или global, если в Node.js);
  // для привязки this используется метод func.bind()
}
```
