### ISSUE TITLE
CSS-анимации

### ISSUE THREAD

**Issue by amoonnra** [javascript-tutorial/ru.javascript.info#1595]
В разеделе [transition-timing-function](https://learn.javascript.ru/css-animations#transition-timing-function) в конце можно добавить к 

> Как сделать кривую Безье необходимую для конкретной задачи? Существует множество инструментов, например можно использовать с сайта http://cubic-bezier.com/.

Или можно сделать это прямо в панели для разработчиков в Chrome:

![Screenshot_4](https://user-images.githubusercontent.com/104252639/164887739-d17fca89-de67-4171-9a8a-037301abf0e1.jpg)

**Comment by Rnbsov** [comment]
Отличная идея, она уже на рассмотрении 😃👍

Если есть ещё предложения не стесняйтесь сообщать

**Comment by Alexandre887** [comment]
> Отличная идея, она уже на рассмотрении 😃👍
> 
> Если есть ещё предложения не стесняйтесь сообщать

@Rnbsov, скиньте ссылку на PR, пожалуйста.
