### ISSUE TITLE
Опечатка в статье про дебагинг

### ISSUE THREAD

**Issue by iddqdbpbbi** [javascript-tutorial/ru.javascript.info#1615]
Добрый день в статье [https://learn.javascript.ru/debugging-chrome](https://learn.javascript.ru/debugging-chrome
) опечатка в слове "команда" в параграфе "Если сравнить, то **_кманда_** «Step» переходит во вложенный вызов функцию и приостанавливает выполнение в первой строке, в то время как «Step over» выполняет вызов вложенной функции незаметно для нас, пропуская её внутренний код."

**Comment by Rnbsov** [comment]
Спасибо, хорошая работа 😃👍
