### ISSUE TITLE
5.2 Числа

### ISSUE THREAD

**Issue by KuznecovDenis** [javascript-tutorial/ru.javascript.info#1639]
В статье 5.2 Числа в "Итого" не указано о таких методах как isNan и isFinite, хотя они являются важным моментом. Добавьте пожалуйста их в подитог статьи если есть возможность

**Comment by Rnbsov** [comment]
Ваш запрос уже на рассмотрении, как примут внесу изменения 👾

**Comment by Alexandre887** [comment]
### __Добавлено:__
![do](https://user-images.githubusercontent.com/74434545/186463940-4ec4e1f6-7f24-4bee-8fdd-a2d52beee784.png)
