### ISSUE TITLE
Пара небольших замечаний

### ISSUE THREAD

**Issue by RamanKandratchyk** [javascript-tutorial/ru.javascript.info#1647]
Добрый день. Отличные статьи, написаны грамотно, даже очень. Поэтому каждая мелочь бросается в глаза: на зеркале заметен даже муравей :))
Сделаем javascript.info ещё лучше...
1. В статье "Методы RegExp и String" в разделе regexp.exec(str) есть текст "В прошлом, до появления метода str.matchAll в JavaScript, вызов regexp.exec в цикле использовали для получения всех совпадений с их позициями и группами скобок в цикле:"
Слова "в цикле" встречаются два раза. Может лучше один случай оставить, например, первый? а?
2. В этой же статье, в разделе regexp.test(str) в первом же примере есть комментарий в коде: // эти два теста делают одно и же
Правильно "// эти два теста делают одно и то же"
Спасибо. За колоссальный труд.

**Comment by Rnbsov** [comment]
Большое спасибо за то что уведомили нас об этих опечатках 😃👍

Если найдёте ещё что-нибудь, сообщайте)
