### ISSUE TITLE
Отображение номеров глав

### ISSUE THREAD

**Issue by ImmaxvelSolbeg** [javascript-tutorial/ru.javascript.info#1650]
Добрый день, браузер Google Chrome Version 102.0.5005.61, номера глав отображаются следующим образом:
<img width="1154" alt="Screenshot 2022-05-29 at 18 04 41" src="https://user-images.githubusercontent.com/95210945/170876459-33a9b3dc-b427-407c-8ce4-f43699fa987f.png">

**Comment by ruslauz** [comment]
👍
