### ISSUE TITLE
мои замечания видны на скриншотах

### ISSUE THREAD

**Issue by kosten20** [javascript-tutorial/ru.javascript.info#1651]
![Снимок экрана от 2022-06-05 17-27-39](https://user-images.githubusercontent.com/96771947/172048376-e6e3b457-ec00-4b64-b779-a95d83825538.png)
![Снимок экрана от 2022-06-05 17-28-25](https://user-images.githubusercontent.com/96771947/172048378-e5e64d9d-52f1-4460-bffb-79e0a929f4af.png)
![Снимок экрана от 2022-06-05 17-28-55](https://user-images.githubusercontent.com/96771947/172048380-9e285187-5372-437a-91ca-f3211b43cbc4.png)
![Снимок экрана от 2022-06-05 17-28-32](https://user-images.githubusercontent.com/96771947/172048382-5abfad52-836a-453c-abe1-0942c31d87a0.png)
![Снимок экрана от 2022-06-05 17-28-46](https://user-images.githubusercontent.com/96771947/172048386-2d6c3583-b8e7-4e49-b3ec-b3a73b30045e.png)

**Comment by iliakan** [comment]
Вроде давно исправлено.
