### ISSUE TITLE
Задача "Я JavaScript!", проблемы с кодировкой: козябры

### ISSUE THREAD

**Issue by Ripple-activator** [javascript-tutorial/ru.javascript.info#1655]
Если тренироваться на своём хостинге, а не в песочнице, то нужно указывать кодировку и код в песочнице должен выглядеть так: 
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>

  <script>
    alert( "Я JavaScript!" );
  </script>

</body>
</html>
```

Саму страницу в редакторе перед загрузкой на хостинг тоже нужно перевести в UTF-8.

**Comment by Alexandre887** [comment]
Дополнительные html-теги не указываются в целях поддержания лаконичности отрывков кода. В песочнице русские буквы прекрасно отображаются.
Если кто-либо из новичков в программировании всё же столкнётся с подобной проблемой, он сможет решить её сделав 1 запрос в гугл, или задав вопрос в комментариях/на других ресурсах.
