### ISSUE TITLE
Циклы while и for

### ISSUE THREAD

**Issue by Ripple-activator** [javascript-tutorial/ru.javascript.info#1659]
Нигде не описан пример иного шага цикла: 
`for (let i=2; i<=10; i=i+2)`

**Comment by Alexandre887** [comment]
Здравствуйте. Как вы могли заметить, в статье о циклах присутствует следующая таблица:

![53](https://user-images.githubusercontent.com/74434545/186214494-79c36adb-50bd-4681-91f0-2ef3f93782df.png)
...где описано, какая часть цикла за что отвечает. А также имеется "алгоритм работы цикла":

![image](https://user-images.githubusercontent.com/74434545/186214828-ebd746b1-e8d6-4bea-897e-6e7fee04d588.png)
...который интуитивно указывает на то, что и условие, и тело, и шаг могут выглядеть совершенно по-разному, т.е нету привязанности к каким-либо определенным выражениям. Исходя из этого, подробное описание каждой части цикла в этом разделе не требуется. Но, если вы желаете добавить какое-либо уточнение по этому поводу, — вы всегда можете отправить Pull Request с исправлениями. Он будет рассмотрен, и, если правки действительно окажутся полезными, — ваши коррективы будут внесены в статью.
