### ISSUE TITLE
Расхождения в материале 

### ISSUE THREAD

**Issue by Tayan21** [javascript-tutorial/ru.javascript.info#1679]
Добрый день я не изучал тему про сокращение нулей буквой е но у вас расхождения в статье и в итоге. В статье вы пишете 1.23е-6 это 0.00000123. А в итоге - 0.000123. Я думаю что правильный это вариант итога. Можете проверить статью?

**Comment by Alexandre887** [comment]
В итоге указано не **1.23e-6**, а **123e-6**, поэтому всё правильно.

**1.23e-6** — это _ноль целых сто двадцать три стомиллионных_.
**123e-6** — это _ноль целых сто двадцать три миллионных_.
