### ISSUE TITLE
Ошибка в примере Группировка «case»

### ISSUE THREAD

**Issue by Diananeedle** [javascript-tutorial/ru.javascript.info#1685]
1. В переменную a положить 4 для правильного вывода сообщения.
2. При нажатии на вопросительный знак при вводе комментария "ИЛИ ЧЕРЕЗ DISQUS" остается рамка тултипа

![Снимок](https://user-images.githubusercontent.com/6080489/178577031-c86af0dc-0957-4db9-ba6c-fd943bda4dd9.PNG)

**Comment by Alexandre887** [comment]
Ошибок в примере нет, т.к демонстрируется именно вариант использования группировки «case». Присвоив переменной `a` значение `4`, вы приведете в действие код, который совсем не относится к теме этой части статьи. А вот если записать в `a` `+prompt("2 + 2 = ?", "");`, код ниже станет интуитивно понятным.
