### ISSUE TITLE
Абсолютный путь - уточнение

### ISSUE THREAD

**Issue by IvanSemenov82** [javascript-tutorial/ru.javascript.info#1692]
Подскажите, что за абсолютный путь такой у вас?
src="/path/to/script.js"
Если я правильно понял то должен быть указан от корня диска, тогда бы это был абсолютным, если запускаем локально. Или я ошибаюсь?

https://learn.javascript.ru/hello-world

**Comment by KhokhlovKirill** [comment]
Абсолютный путь указывается от корня диска если страница запускается локально. Но для сервера (nginx и др.) абсолютный путь начинается от корня сайта.
