### ISSUE TITLE
Правка в главу "Проверка класса: "instanceof""

### ISSUE THREAD

**Issue by veronika1002** [javascript-tutorial/ru.javascript.info#1696]
Предлагаю правку в главу Проверка класса: "instanceof"

Вместо этого:
Оператор instanceof позволяет проверить, какому классу принадлежит объект, с учетом прототипного наследования.

Правильнее будет:
Оператор instanceof позволяет проверить, принадлежит ли данный объект указанному классу, с учетом прототипного наследования.

**Comment by sFlcn** [comment]
Да, меня тоже слегка смутила текущая формулировка, когда читал эту главу.
Создал Pull request с правкой. Но вместо "данный объект" предлагаю писать просто "объект":
`позволяет проверить, принадлежит ли объект указанному классу,`
так будет ещё яснее, мне кажется.
