### ISSUE TITLE
Замечание по примеру в главе: MutationObserver

### ISSUE THREAD

**Issue by miptleha** [javascript-tutorial/ru.javascript.info#1698]
Когда запускаем первый пример из главы (с отредактируй <b>меня</b>, пожалуйста), то вывод консоли на экран делается невидимым цветом. 
![изображение](https://user-images.githubusercontent.com/13675134/181892304-d84ea395-5374-4030-bf74-65f2e0efd5ce.png)
Приходится выделять текст, чтобы увидеть его содержимое

**Comment by ruslauz** [comment]
[Duplicate](https://github.com/javascript-tutorial/ru.javascript.info/issues/1471)
