### ISSUE TITLE
Устаревшая информация по firefox в главе: Открытие окон и методы window

### ISSUE THREAD

**Issue by miptleha** [javascript-tutorial/ru.javascript.info#1699]
>Запустим код:
>// откроется через 3 секунды
>setTimeout(() => window.open('http://google.com'), 3000);
>Попап откроется в Chrome, но будет заблокирован в Firefox.

в Firefox (103.0) окно открывается

**Comment by Alexandre887** [comment]
Добрый вечер.
Большое спасибо за информацию, статью откорректировали.
