### ISSUE TITLE
Хелп. Урок "Опциональная цепочка", вопросы по примерам 🙏

### ISSUE THREAD

**Issue by Belobrova** [javascript-tutorial/ru.javascript.info#1701]
🙏 Объясните, пожалуйста: 
1. Почему в примере
" alert(user.address ? user.address.street ? user.address.street.name : null : null); "
синтаксис не соответствует тому, что был указан в главе про условный оператор? А именно (если несколько условий):
условие 1 ? true : условие 2 ? true : условие N ? true : false;
2. Почему в примере
" let user = {}; // пользователь без адреса
alert( user.address && user.address.street && user.address.street.name ); "
alert выводит "undefined"?
Оператор && конвертирует все значения в true/false и выводит первый ложный операнд. Как тут получается в результате undefined?

Спасибо всем, кто найдёт время ответить.

**Comment by Vkube** [comment]
Привет,  можешь глянуть это видео https://www.youtube.com/shorts/fcS4azdSR_0

**Comment by Alexandre887** [comment]
Добрый вечер. Для подобных вопросов существует официальный Discord-сервер [learn.javascript.ru](https://learn.javascript.ru):
https://discord.com/invite/X8yWNWpTQs
Можете спрашивать обо всем, что вам непонятно, — вам обязательно ответят на все вопросы :)
