### ISSUE TITLE
Нерабочий код на learnJS в разделе fetch глава 1

### ISSUE THREAD

**Issue by ChuckShuleyq** [javascript-tutorial/ru.javascript.info#1707]
Пример 1
let url = 'https://api.github.com/repos/javascript-tutorial/en.javascript.info/commits';
let response = await fetch(url);

let commits = await response.json(); // читаем ответ в формате JSON

alert(commits[0].author.login);
Пример 2
let response = await fetch('https://api.github.com/repos/javascript-tutorial/en.javascript.info/commits');

let text = await response.text(); // прочитать тело ответа как текст

alert(text.slice(0, 80) + '...');

Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules

Проверено на codepen и локальном сервере.

**Comment by Alexandre887** [comment]
Переводим ошибку:

> await is only valid in async functions and the top level bodies of modules

> await действует только в асинхронных функциях и на верхнем уровне тел модулей

Делаем соответствующий вывод: чтобы примеры заработали, нужно поместить их в асинхронную функцию:
```js
// с использованием 2 примера // 

async function showText() {
  let response = await fetch('https://api.github.com/repos/javascript-tutorial/en.javascript.info/commits');

  let text = await response.text();
  
  alert(text.slice(0, 80) + '...');
}

showText();

// или //

(async function() {
  let response = await fetch('https://api.github.com/repos/javascript-tutorial/en.javascript.info/commits');

  let text = await response.text();

  alert(text.slice(0, 80) + '...');
})();

// или //

(async () => {
  let response = await fetch('https://api.github.com/repos/javascript-tutorial/en.javascript.info/commits');

  let text = await response.text();

  alert(text.slice(0, 80) + '...');
})();
```

В примерах кода отсутствуют подобные обертки в виде асинхронных функций исключительно из эстетических соображений. Тем более статья "Fetch" находится в последней части учебника ("Тематические разделы"), поэтому полагается, что если вы ее читаете, значит у вас уже присутствует какая-то база знаний — вы знаете, что такое промисы, как с ними работать, и что такое async/await.
