### ISSUE TITLE
Не понятно

### ISSUE THREAD

**Issue by VinDenBecK** [javascript-tutorial/ru.javascript.info#1712]
Здравствуйте!
После первого рисунка есть непонятное предложение: "Забегая вперёд, заметим, что вместо всего скрипта "use strict" можно поставить в начале большинства видов функций." на этой странице: 
https://learn.javascript.ru/strict-mode

Что можно поставить вместо "use strict" ? Способ группировки команд или?

**Comment by VinDenBecK** [comment]
извините, я имел в виду на этой странице:
https://learn.javascript.ru/strict-mode

**Comment by sFlcn** [comment]
Имеется в виду, что строку `'use strict'` можно поставить как в начале всего скрипта (например, в первой строчке файла script.js) — тогда _весь JS_ будет выполняться в "строгом режиме", так и в начале тела функции — включив режим только для неё.

**Comment by VinDenBecK** [comment]
Спасибо Павел!

Отправлено с iPhone

16.08.2022, в 12:13, Pavel Sokolovskii ***@***.***> написал(а):

﻿

Имеется в виду, что строку 'use strict' можно поставить как в начале всего скрипта (например, в первой строчке файла script.js) — тогда весь JS будет выполняться в "строгом режиме", так и в начале тела функции — включив режим только для неё.

**Comment by sFlcn** [comment]
> Спасибо Павел!

Пожалуйста :slightly_smiling_face: рад помочь.
Можно закрыть Issue — у вас слева от кнопки "Comment" [должна быть "Close"](https://docs.github.com/assets/cb-14354/images/help/issues/close-issue-with-reason.png).

**Comment by VinDenBecK** [comment]
Конечно можно!) Закрыл!
________________________________
Von: Pavel Sokolovskii ***@***.***>
Gesendet: Dienstag, 16. August 2022 18:48
An: javascript-tutorial/ru.javascript.info ***@***.***>
Cc: VinDenBecK ***@***.***>; Author ***@***.***>
Betreff: Re: [javascript-tutorial/ru.javascript.info] Не понятно (Issue #1712)


Спасибо Павел!

Пожалуйста 🙂 рад помочь.
Можно закрыть Issue — у вас слева от кнопки "Comment" должна быть "Close"<https://docs.github.com/assets/cb-14354/images/help/issues/close-issue-with-reason.png>.
