### ISSUE TITLE
ошибка в задаче "Создайте новый объект с помощью уже существующего"

### ISSUE THREAD

**Issue by segremelnikov** [javascript-tutorial/ru.javascript.info#1724]
(в главе "F.prototype")

"Наконец срабатывает let user2 = new Object('Pete'), но конструктор Object игнорирует аргументы, он всегда создаёт пустой объект: let user2 = {} – это как раз то, чему равен user2 в итоге."

М.б. раньше работало так, но сейчас user2 -- объект-обертка строки 'Pete', alert или console.log выводят Pete

**Comment by Alexandre887** [comment]
Добрый день!
Спасибо за замечание, описание решения этой задачи было откорректировано.


![Screenshot110955](https://user-images.githubusercontent.com/74434545/199969210-4b53cb17-7096-4421-9f3c-f791a6c26234.png)
