### ISSUE TITLE
Неправильное отображение новых задач

### ISSUE THREAD

**Issue by Alexandre887** [javascript-tutorial/ru.javascript.info#1727]
@iliakan 
При добавлении новых задач к любой из статей, по какой-то причине они начинают неправильно отображаться.
Пример (относительно недавно добавленная задача к статье "Методы массивов", в соответствии с англ. редакцией):

![image](https://user-images.githubusercontent.com/74434545/188323344-6301ea28-890c-4299-9632-4bbca94f4118.png)

1. Заглавие задачи отображается большим шрифтом (+ не там, где нужно)
2. Поле "важность" не отображается
3. Слетает кнопка открытия задачи в новой вкладке

Каким образом это можно исправить?

**Comment by iliakan** [comment]
В учебнике используются везде переводы строк `\n`, а не `\r\n`. Исправил здесь. Запушил.

Не должно быть неверных переводов строк нигде.

Пожалуйста, проверьте у себя, файлы исключительно в linux кодировке везде, может быть, редактор неверно настроен?

Также, как вижу, сбиты отступы - должно быть два пробела (не четыре).

Также проверьте, пожалуйста, редактор, чтобы там было так настроено.

**Comment by Alexandre887** [comment]
Разобрался, спасибо.
