### ISSUE TITLE
  CSS-анимации, Задача #1

### ISSUE THREAD

**Issue by Keller007** [javascript-tutorial/ru.javascript.info#1746]
[Задачи] #1
Проверка на повторное срабатывание не работает.

https://plnkr.co/edit/cKZ0jquvODgbVTSZ?p=preview&preview

**Comment by Alexandre887** [comment]
Добрый вечер! Спасибо за замечание, правки внесены на сайт.
Если найдёте ещё какие-либо ошибки/неточности, обязательно присылайте Issue или Pull Request.
