### ISSUE TITLE
Недоработки в коде примера слайдера во втором разделе: "Интерфейсные события">"События указателя".

### ISSUE THREAD

**Issue by Distom** [javascript-tutorial/ru.javascript.info#1748]
В коде на ползунке не удаляется событие 'pointermove', в связи с чем после 'pointerup' ползунок продолжает следовать за курсором мыши, если курсор находится на ползунке. 
Также в css ползунка отсутствует 'touch-action: none', из за этого на сенсорных экранах тоже не правильно работает.

**Comment by Alexandre887** [comment]
Добрый вечер! Спасибо за замечания, правки внесены на сайт.
