### ISSUE TITLE
Misprint

### ISSUE THREAD

**Issue by Alex-g-h** [javascript-tutorial/ru.javascript.info#1749]
https://learn.javascript.ru/class-inheritance#:~:text=%D0%92%20%D0%BA%D0%BE%D0%B4%D0%B5%20tree.sayHi()%20%D0%B5%D1%81%D1%82%D1%8C%20%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2%20super.sayHi().%20%D0%9E%D0%BD%20%D0%B8%D0%B4%D1%91%D1%82%20%D0%B2%D0%B2%D0%B5%D1%80%D1%85%20%D0%BE%D1%82%20rabbit%20%D0%B8%20%D0%B1%D0%B5%D1%80%D1%91%D1%82%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%20%D0%B8%D0%B7%20animal.

"В коде tree.sayHi() есть вызов super.sayHi(). Он идёт вверх от rabbit и берёт метод из animal." -> 
"В коде rabbit.sayHi() есть вызов super.sayHi(). Он идёт вверх от rabbit и берёт метод из animal."

**Comment by Alexandre887** [comment]
Всё правильно написано, нельзя ничего менять.
