### ISSUE TITLE
Опечатка в условии задачи

### ISSUE THREAD

**Issue by novakovskii** [javascript-tutorial/ru.javascript.info#1750]
Здравствуйте, при изучении материала на сайте learn.javascript.ru заметил опечатку в условии первой задачи по теме 6.6 "Объект функции, NFE". Изначально в задании сказано "чтобы счётчик мог увеличивать и устанавливать значение", хотя далее по условию и исходному коду понятно, что счётчик должен значение уменьшать.

**Comment by Alexandre887** [comment]
### Добрый день! Спасибо за замечание, исправили.

![image](https://user-images.githubusercontent.com/74434545/200121422-2a6f0e5d-02fd-4cdf-ac97-9c2b6cf1aa58.png)
