### ISSUE TITLE
Ошибка в тесте по языку Javascript

### ISSUE THREAD

**Issue by AlexandraSmirnova** [javascript-tutorial/ru.javascript.info#1754]
Обнаружила ошибку в вопросе про this
В нем верного ответа нет, там window, a не User и не undefined

![Screenshot 2022-11-17 124954](https://user-images.githubusercontent.com/9385858/202414817-505fa461-a0d2-4db4-ad98-080b478adc7e.jpg)

**Comment by Alexandre887** [comment]
Здравствуйте.

В вопросе нет ошибок, правильный ответ — `undefined`.

### Объяснение:

1. На странице выбора теста (JavaScript в целом или DOM, работа со страницей) присутствует следующее пояснение:

    ![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/448f7c49-7fe2-4c1b-a2be-f5a7322f584c)
2. Строка `(user.sayBye = user.sayHi)();` из вопроса будет полностью эквивалентна обычному вызову следующей функции:

    ```javascript
    let sayHi = function() {
      alert(this)
    }
    ```
    Почему? Объяснение есть в главе [Ссылочный тип](https://learn.javascript.ru/reference-type).
3. В **нестрогом** режиме (без использования `"use strict"`), при попытке получить `this` внутри обычной функции, вы получите [глобальный объект](https://learn.javascript.ru/global-object) `window` (или `global`, в `Node.js`).

    В **строгом** режиме (с использованием `"use strict"`), при попытке получить `this` внутри обычной функции, вы получите `undefined`. Поскольку на странице выбора теста присутствует пояснение, что **во всех** вопросах будет использоваться строгий режим, ответ `undefined` является полностью правильным. 

    Для привязки определенного `this` к функции, существуют специальные методы, такие как [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind):
    ```javascript
    function showThis() {
      console.log(this.name)
    }
    
    let bindShowThis = showThis.bind({
      name: "Василий"
    });
    
    bindShowThis(); // "Василий"
    ```
