### ISSUE TITLE
Я два раза не повторяю повторяю

### ISSUE THREAD

**Issue by Noliferqt** [javascript-tutorial/ru.javascript.info#1762]
[В данном разделе](https://learn.javascript.ru/map-set#map) есть абзац, который изображен на [скрине](https://clip2net.com/s/4hkt6kf), описывающий главное различие object и map. С первыми 2-умя предложениями все в порядке. Зачем существует 3 - непонятно, оно повторяет то же, что написано выше и усложняет понимание, а ещё увеличивает количество повторений термина 'Object' в 1 абзаце до невообразимых значений.

**Comment by Xardas225** [comment]
Ссылка на скрин нерабочая
Остаётся только доагдываться, о чём идёт речь
