### ISSUE TITLE
задание Загрузка видимых изображений

### ISSUE THREAD

**Issue by DenKuznets** [javascript-tutorial/ru.javascript.info#1765]
https://learn.javascript.ru/onscroll#zagruzka-vidimyh-izobrazheniy
Если высота страницы недостаточна, что бы вместить изображение целиком, то при загрузке страницы в таком положении, когда верхний край изображения находится за верхней границей окна, а нижний край изображения находится за нижней границей окна, изображение загружаться не будет. Если вместо
```
   // верхний край элемента виден?
        let topVisible = coords.top > 0 && coords.top < windowHeight;

        // нижний край элемента виден?
        let bottomVisible = coords.bottom < windowHeight && coords.bottom > 0;
```

в условии указать просто 
`if( elem.getBoundingClientRect().bottom > 0 && elem.getBoundingClientRect().top < window.innerHeight) {
        return true;
      }`

, то изображение будет подгружаться в любом случае когда оно видимо на экране

**Comment by Alexandre887** [comment]
> Если высота страницы недостаточна, что бы вместить изображение целиком, то при загрузке страницы в таком положении, когда верхний край изображения находится за верхней границей окна, а нижний край изображения находится за нижней границей окна, изображение загружаться не будет. Если вместо

В описании задачи отсутствует требование к обращению внимания на это. От читателя ожидается максимально тривиальное решение.
