### ISSUE TITLE
Ошибки в тесте про DOM

### ISSUE THREAD

**Issue by ftoh** [javascript-tutorial/ru.javascript.info#1767]
Chrome 108. Windows 10.
1. Вопрос про задержку setTimeout. По стандарту минимальная задержка устанавливается только во вложенных вызовах, начиная с 5-ого
https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#reasons_for_delays_longer_than_specified
![image](https://user-images.githubusercontent.com/5018813/207504464-3e7a5b1c-2207-4606-abab-5b2fab9d0743.png)
![image](https://user-images.githubusercontent.com/5018813/207504844-bcded260-cc27-4347-ab30-584558b1fee4.png)

2. Вопрос про события в capture и bubble фазах. Capture фаза сработает раньше
![image](https://user-images.githubusercontent.com/5018813/207504892-169a059b-66bb-479a-9466-ba5063544b9c.png)

**Comment by FTOH** [comment]
Я нашёл описание 2-ого теста в файле. Странно, что комментарий не показывается на сайте.
![image](https://user-images.githubusercontent.com/5018813/207506714-4f63f596-b8f5-4bd8-8153-b814fe4de447.png)

Судя по всему, поведение браузера описано неверно. Capture события всегда происходят раньше
![image](https://user-images.githubusercontent.com/5018813/207506980-86c529b1-c66b-4d6c-85e9-038f5929e717.png)
