### ISSUE TITLE
Опечатка?

### ISSUE THREAD

**Issue by Enkratia** [javascript-tutorial/ru.javascript.info#1772]
**Статья**: https://learn.javascript.ru/fetch (в Итого)

"response.json() – преобразовывает ответ **_в_** JSON-объект,"

Преобразование **_из_** JSON?

" ... the result is not JSON but is instead the result of taking JSON as input and parsing it to produce a JavaScript object. " (https://developer.mozilla.org/en-US/docs/Web/API/Response/json).

**Comment by Alexandre887** [comment]
Спасибо за замечания, неточности исправили. В следующий раз, пожалуйста, присылайте Pull Request'ы с исправлениями вместо Issue. Таким образом нам будет намного легче рассмотреть и прокомментировать правки.
