### ISSUE TITLE
Неактуальный редкатор Atom

### ISSUE THREAD

**Issue by proff1991** [javascript-tutorial/ru.javascript.info#1774]
В статье [редакторы кода](https://learn.javascript.ru/code-editors#lyogkie-redaktory) в качестве "лёгкого редактора" первым в списке указан Atom. 15 декабря 2022 года проект Atom прекратил своё существование: [официальная страница](https://github.blog/2022-06-08-sunsetting-atom/).

**Comment by Alexandre887** [comment]
Исправлено. В следующий раз, пожалуйста, присылайте Pull Request с правками, вместо создания Issue.
