### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by DotsenkoArtem** [javascript-tutorial/ru.javascript.info#1780]
Страница: https://learn.javascript.ru/object-copy
Строку:
Мы можем думать _**об**_ переменной объекта, такой как user, как о листе бумаги с адресом объекта на нем.

Исправить на:
Мы можем думать **_о_** переменной объекта, такой как user, как о листе бумаги с адресом объекта на нем.

**Comment by Alexandre887** [comment]
Добрый вечер.
Большое спасибо за замечание, текст исправлен. 
В следующий раз, пожалуйста, присылайте Pull Request, а не Issue. Так будет намного удобнее проверить и утвердить правки.
