### ISSUE TITLE
Опечатка в описании spread оператора.

### ISSUE THREAD

**Issue by OlegGorod** [javascript-tutorial/ru.javascript.info#1782]
> Если ... располагается в конце списка **_аргументов_** функции, то это «остаточные параметры». Он собирает остальные неуказанные аргументы и делает из них массив.

Наверное имелось в виду параметров, а не аргументов, т.к. аргумент функции указывается при её вызове. 
> Если ... встретился в вызове функции или где-либо ещё, то это «оператор расширения». Он извлекает элементы из массива.
[https://learn.javascript.ru/rest-parameters-spread-operator](url)

**Comment by Alexandre887** [comment]
Добрый вечер. 
Спасибо за замечание, текст исправлен. В следующий раз, пожалуйста, присылайте Pull Request вместо Issue. Таким образом будет намного легче проверить и утвердить правки.
