### ISSUE TITLE
Небольшая ошибка в описании действия.

### ISSUE THREAD

**Issue by ValeraFantozziy** [javascript-tutorial/ru.javascript.info#1784]
Здравствуйте! Нашёл небольшую ошибку в описании возведения в степень:

"...В выражении a ** b оператор возведения в степень умножает a на само себя b раз..."
Если 2 умножается на себя 2 раза получается уже 3-я степень...

**Comment by Alexandre887** [comment]
Добрый вечер. Спасибо за замечание, текст перефразирован.

**Comment by ValeraFantozziy** [comment]
Доброе утро, Александр! Похожую ошибку нашёл в последнем задании раздела "функции":
"...Напишите функцию pow(x,n), которая возвращает x в степени n. Иначе говоря, умножает x на себя n раз и возвращает результат..."

**Comment by Alexandre887** [comment]
> Доброе утро, Александр! Похожую ошибку нашёл в последнем задании раздела "функции": "...Напишите функцию pow(x,n), которая возвращает x в степени n. Иначе говоря, умножает x на себя n раз и возвращает результат..."

Исправлено.
