### ISSUE TITLE
Почему планета объявлена через let, а не const

### ISSUE THREAD

**Issue by scffs** [javascript-tutorial/ru.javascript.info#1785]
https://learn.javascript.ru/variables

![изображение](https://user-images.githubusercontent.com/67464545/212448680-260c9125-91dd-4351-938d-cc4b7b075d05.png)

**Comment by Alexandre887** [comment]
Объявлять переменные, которые никогда не будут изменены в коде, с помощью `const` — это всего лишь рекомендация. а не какой-либо строгий стандарт. К данной рекомендации стоит прислушаться, если вы пишите длинный код, выполняющий разные действия, в котором лучше было бы наглядно продемонстрировать, что та или иная переменная никогда не будет изменена. 

В таких случаях это помогает немного улучшить читабельность кода. Если вы работаете совместно с другими разработчиками, при беглом анализе вашего кода, им будет легче понять его концепцию и мелкие детали работы. 

В целом это дело вкуса.  Для неизменяемых переменных кто-то предпочитает использовать `const`, кто-то — `let`.
