### ISSUE TITLE
<pre> Ошибка в коде

### ISSUE THREAD

**Issue by ValeraFantozziy** [javascript-tutorial/ru.javascript.info#1786]
< pre>

function isPrime(n) {
  for (let i = 2; i < n; i++) {
    if ( n % i == 0) return false;
    
    Здравствуйте! В коде, который ищет простые числа с помощью встроенной функции, вы использовали в ней неверные буквы для переменных. Проверьте, пожалуйста.

**Comment by Alexandre887** [comment]
Здравствуйте.
Во встроенной функции всё указано правильно. Объясните подробнее, в чем проблема.

**Comment by ValeraFantozziy** [comment]
Виноват, действительно, всё верно.
