### ISSUE TITLE
Ошибка в решении задачи

### ISSUE THREAD

**Issue by maximlunegov** [javascript-tutorial/ru.javascript.info#1787]
В задаче "[Покажите знак числа](https://learn.javascript.ru/task/sign)" решение неполное. Не хватает проверки на "0", т.к. при таком решении получим "0" и на любой текст.

```
let value = prompt('Введите число', 0);
if (value > 0) {
  alert( 1 );
} else if (value < 0) {
  alert( -1 );
} else if (value == 0)
  alert( 0 );
else {
  alert( 'Неверный ввод' );
}
```

**Comment by Alexandre887** [comment]
Внимательнее прочитайте условие задачи:

> Используя конструкцию if..else, напишите код, который получает число через prompt, а затем выводит в alert:

> • 1, если значение больше нуля,
> • -1, если значение меньше нуля,
> • 0, если значение равно нулю.

> **Предполагается, что пользователь вводит только числа**.
