### ISSUE TITLE
Не правильно выводится значение при вводе значения переменной

### ISSUE THREAD

**Issue by AntonMVl** [javascript-tutorial/ru.javascript.info#1788]
function checkAge(age) {
  if (age > 18) {
    return true;
  } else {
    return confirm('А родители разрешили?');
  }
}

let age = prompt('Сколько вам лет?', 18);

if ( checkAge(age) ) {
  alert( 'Доступ получен' );
} else {
  alert( 'Доступ закрыт' );
}

Если в всплывающем окне ввести значение меньше 18, то выведется сообщение "А родители разрешили", после чего выводится сообщение "Доступ получен", хотя должно выводится "Доступ закрыт"

**Comment by Alexandre887** [comment]
Добрый вечер.

Если в confirm'e "А родители разрешили" ответить "ОК" (т.е да), доступ выдаётся. Если же ответить "Отмена" (т.е нет), доступ не выдаётся — результаты достаточно логичные. Почему вы считаете, что должно выводиться "Доступ закрыт" в обоих случаях?
