### ISSUE TITLE
<code> Замечание по условию из задачи на вычисление степени.

### ISSUE THREAD

**Issue by ValeraFantozziy** [javascript-tutorial/ru.javascript.info#1790]
Здравствуйте!

<code> 
 if (n < 1) {
 
 В задаче на вычисление степени из раздела "функции" почему -то степень почему-то сравнивается с единицей, тогда как для обеспечения попадания в n только натуральных чисел нужно остаток от деления n на 1 (n % 1) сравнивать с нулём...

**Comment by Alexandre887** [comment]
Исправлено:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/d3069798-7f35-43ba-864c-e477a173ec5a)
