### ISSUE TITLE
Преобразование такого вида: Boolean(alert (1)).

### ISSUE THREAD

**Issue by Alexey384** [javascript-tutorial/ru.javascript.info#1795]
Решаю задачу "Что выведет alert (ИЛИ)?" https://learn.javascript.ru/task/alert-or
До этой задачи нигде не нашёл информацию про преобразование такого вида "Boolean(alert (1))". Где можно про это почитать?

**Comment by ovarn** [comment]
В уроке "Взаимодействие: alert, prompt, confirm" действительно не упомянается значение, которое возвращает метод alert. В таких случаях советую прибегать к официальной документации или другим ресурсам. По мере изучения и использования языка это придется делать довольно часто, так как учебник не является исчерпывающим ответом на все вопросы. Поэтому советую приучится себя к этому.

А сам метод, если что, ничего не возвращает (т.е. undefined).

**Comment by Alexandre887** [comment]
Упомянутая задача по большей части рассчитана на смекалку читателя, и умение найти какую-либо информацию в интернете (что очень поможет вам в будущем при разработке различных проектов). Это — основа. То, чему должен учиться каждый программист с самого начала. 

Подобные задачи не раз будут попадаться вам в учебнике, где требуется проявить смекалку и воспользоваться иными источниками информации. Описать все возможные вариации кода в одном ресурсе невозможно. 

План действий по решению конкретно этой задачи таков:

1. Из предыдущих статей мы уже знаем, что `alert` — это функция. Также мы знаем, что эта функция принимает 1 параметр — сообщение, которое будет выведено в браузере.
2. Далее, мы обращаем внимание на то, что вместо привычного значения в круглых скобках, там находится целое выражение. Мы уже знакомы с логическими операторами, поэтому знаем, что оператор ИЛИ **каждый операнд конвертирует в логическое значение. Если результат true, останавливается и возвращает исходное значение этого операнда.**
3. Из предыдущих статей мы также знаем, что функция может что-то возвращать. Но, что возвращает `alert` — в учебнике не сказано. Поэтому нам нужен дополнительный источник информации. Как пример, возьмём [MDN](https://developer.mozilla.org/en-US/). Ищем на сайте описание функции `alert`, листаем чуть ниже и видим, что `alert` ничего не возвращает (т.е `undefined`):
![image](https://user-images.githubusercontent.com/74434545/215267230-379b46fa-f742-47a1-aee3-a0014111ab5e.png)
4. После полученной информации из статьи, а также из других источников, можно легко решить задачу.

**Comment by Alexey-Fedosyuk** [comment]
Так а в чем проблема добавить эту информацию в учебник?

**Comment by Alexandre887** [comment]
> Так а в чем проблема добавить эту информацию в учебник?

Автор учебника решил не указывать эту информацию, видимо, по причинам, которые я изложил в первом комментарии. 

Если вы считаете, что она всё-таки должна присутствовать — отправляйте Pull Request в [репозиторий английской версии учебника](https://github.com/javascript-tutorial/en.javascript.info), который её добавит. После чего, если он будет принят, отправляйте PR и в этот репозиторий. 

Добавляя статьи, либо дополнительную информацию в существующие статьи, мы в основном руководствуемся английской версией, поэтому с лёту выполнить ваши пожелания не могу.
