### ISSUE TITLE
Ошибка в статье про всплытие/погружение

### ISSUE THREAD

**Issue by alwafor** [javascript-tutorial/ru.javascript.info#1800]
[Ссылка на статью](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/2-events/03-event-delegation/article.md)

В коде "улучшенная подсветка ячеек таблицы", в пункте 3 - ошибка. Код следующий:

```js
table.onclick = function(event) {
  let td = event.target.closest('td'); // (1)

  if (!td) return; // (2)

  if (!table.contains(td)) return; // (3)

  highlight(td); // (4)
};
```  

Комментарий к шагу 3 следующий:

*Если таблицы вложенные, event.target может содержать элемент <td>, находящийся вне текущей таблицы. В таких случаях мы должны проверить, действительно ли это <td> нашей таблицы.*

Однако метод `Node.prototype.contains` проверяет на наличие элемента-потомка [(ссылка на MDN)](https://developer.mozilla.org/ru/docs/Web/API/Node/contains), а не на непосредственный дочерний элемент. Таким образом данная проверка всегда будет возвращать `true`, поскольку элемент `td` всегда будет потомком элемента `table`. Следовательно, подсветка также будет срабатывать на элементы вложенной таблицы.

**Comment by Alexandre887** [comment]
Здравствуйте.

Открывать Issue в целях исправления какого-либо материала из учебника — не самое лучшее решение. Для этого существует Pull Request. 

Если вы заинтересованы в контрибьюте, пожалуйста, отправьте PR с исправлением. В описании PR'a опишите, почему вы предлагаете заменить одно на другое, Таким образом нам будет намного легче внести правки в учебник.
