### ISSUE TITLE
Ошибка в статье про события: ontransitionend

### ISSUE THREAD

**Issue by phpcoder2022** [javascript-tutorial/ru.javascript.info#1801]
В [статье про события](https://learn.javascript.ru/introduction-browser-events) говорится, что `transitionend` не работает через атрибут и свойство, а только через `addEventListener`. Это не так: [пример](https://disk.yandex.ru/d/SD2fFFKPXEqqDw)

**Comment by Alexandre887** [comment]
Большое спасибо за замечание, из статьи некорректную информацию убрали.

В следующий раз, пожалуйста, присылайте Pull Request, нам будет намного проще рассмотреть предложения.
