### ISSUE TITLE
Обратная связь к подразделу "Автоматическое тестирование c использованием фреймворка Mocha".

### ISSUE THREAD

**Issue by ValeraFantozziy** [javascript-tutorial/ru.javascript.info#1805]
Здравствуйте! В спецификации приведённого [примера](https://plnkr.co/edit/yOXxvGChgheXAAmF?p=preview&preview) функция должна выдавать NaN, "если n не число". Я думаю, вы имели ввиду "если n - не целое число"...

**Comment by Alexandre887** [comment]
Добрый день!
Большое спасибо за замечание, пример исправлен.
