### ISSUE TITLE
Ошибка в статье: Делегирование событий

### ISSUE THREAD

**Issue by sollidy** [javascript-tutorial/ru.javascript.info#1807]
При попытке запуска кода из подраздела [Применение делегирования: действия в разметке](https://learn.javascript.ru/event-delegation#primenenie-delegirovaniya-deystviya-v-razmetke), конкретно Menu  с методами save, load, search, браузер выдает следующую ошибку:
`Uncaught SyntaxError: Identifier 'Menu' has already been declared
    at codeBox.js:235:11
    at L (codeBox.js:448:7)
    at S.onclick (codeBox.js:75:7)`

**Comment by Alexandre887** [comment]
Исправлено. Большое спасибо за обращение.
