### ISSUE TITLE
Ошибка в тестах "DOM, работа со страницей". Обработчики событий.

### ISSUE THREAD

**Issue by alwafor** [javascript-tutorial/ru.javascript.info#1810]
Кейс следующий:

![image](https://user-images.githubusercontent.com/79059092/218385133-0ce0f047-84a7-4b69-8ca9-8c5ee52936b7.png)

Это неверно. Первым сработает второй обработчик, поскольку он зарегистрирован на фазу захвата.

**Comment by Alexandre887** [comment]
Duplicate of #1767
