### ISSUE TITLE
Ошибка в теме Свойства узлов: тип, тег и содержимое

### ISSUE THREAD

**Issue by qwexplok** [javascript-tutorial/ru.javascript.info#1812]
В разделе "Классы DOM-узлов" схема с изображением основных классов не соответствует описанию этих классов под ней.

**Comment by Alexandre887** [comment]
Здравствуйте.
Спасибо за информацию, статья отредактирована.
<hr>

![image](https://user-images.githubusercontent.com/74434545/219952053-63edb571-726e-4b08-9dc3-019497451a83.png)
