### ISSUE TITLE
operators, сдвиги

### ISSUE THREAD

**Issue by oldGlobula** [javascript-tutorial/ru.javascript.info#1815]
Мне кажется, в статье operators при определении RIGHT SHIFT было бы не лишним указать, что это сдвиг с сохранением знака, а не, например, циклический

**Comment by Alexandre887** [comment]
Здравствуйте.

В указанной статье идёт обычное перечисление существующих побитовых операторов с <ins>указанием их названий</ins>. Этот раздел не должен содержать какие-либо объяснения или уточнения, — для этого есть глава «[Побитовые операторы](https://learn.javascript.ru/bitwise-operators)», в которой приведено подробное описание как RIGHT SHIFT, так и других операторов.

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/637c3837-c0d9-4b8e-83d2-8c2774bc72f1)
