### ISSUE TITLE
function-basics, undefined параметры

### ISSUE THREAD

**Issue by oldGlobula** [javascript-tutorial/ru.javascript.info#1816]
В function-basics не написано прямым текстом, что непередавание функции параметра означает то же самое, что и передача undefined, т.е. о том, что a=undefined; foo(a) равнозначно foo()

**Comment by Alexandre887** [comment]
> В function-basics не написано прямым текстом, что непередавание функции параметра означает то же самое, что и передача undefined

В части статьи "Значения по умолчанию" прямым текстом указывается, что если при вызове функции аргумент не был указан, то его значением становится `undefined`. Также подобное поведение рассматривается на конкретном примере, в этой же части статьи.

> что a=undefined; foo(a) равнозначно foo()

Нет, это очень неточное определение. Достаточно будет проверить псевдомассив `arguments `для подтверждения этому:
```javascript
function arg() {
    console.log([...arguments])
}


arg(undefined) // [undefined] <= аргумент передан
arg() // [] <= аргументов нет
```
