### ISSUE TITLE
Ошибка в статье Циклы while и for

### ISSUE THREAD

**Issue by Alex-allknown** [javascript-tutorial/ru.javascript.info#1817]
В решении задачи "Какие значения выведет цикл while?" ошибки в объяснении :
"Далее 2, 3, 4… Для каждого значения сначала происходит сравнение, а потом – увеличение, и затем срабатывание alert."
и
"Окончание цикла: при i = 4 произойдёт сравнение while (4 < 5) – верно, после этого сработает i++, увеличив i до 5"

По таблице приоритета операторов у постфиксного инкремента приоритет -15 , а у "меньше" -10. Поэтому сначала происходит увеличение, а потом сравнение .

**Comment by Alexandre887** [comment]
Спасибо за замечание. Объяснение перефразировано:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/e0d17e51-0111-4b19-9e17-8a7e3e93a0fa)
