### ISSUE TITLE
Ошибки в консоле на главной странице

### ISSUE THREAD

**Issue by jelasi** [javascript-tutorial/ru.javascript.info#1822]
на главной странице, если зайти в консоль, то у вас летят ошибки, почините пожалуйста)
глаз дергается)))))))))))))

![image](https://user-images.githubusercontent.com/111179374/222931637-c2d8c266-690f-4bb0-acf4-441de1bcceae.png)

**Comment by aslanqwe** [comment]
Они всего лишь переводят статьи на русский, они не смогут изменить как то сам сайт

**Comment by Alexandre887** [comment]
> Они всего лишь переводят статьи на русский, они не смогут изменить как то сам сайт

Нет, мы занимаемся не только переводами статей. Исправление багов/ошибок и прочих недостатков самого сайта так же включается. В случае появления подобных issue, мы подписываем на них автора учебника, который имеет доступ к сайту и может разобраться с проблемой.

**Comment by Alexandre887** [comment]
Подразумеваю, что проблема исчерпана (на главной странице ошибок не вижу).
