### ISSUE TITLE
Описка в тексте (раздел"Объекты")

### ISSUE THREAD

**Issue by Filonych** [javascript-tutorial/ru.javascript.info#1828]
Раздел "Объекты", тема "Свойство из переменной".
В предложении:

_В примере выше название свойств name и age совпадают с **названиями переменных**, которые мы подставляем в качестве значений этих свойств._ 

Вместо "_совпадают с **названиями переменных**_" должно быть  "_совпадают с **параметрами переменной**_"

**Comment by Alexandre887** [comment]
@Filonych, "совпадают с параметрами **переменной**"? Когда это у переменной появились параметры?
