### ISSUE TITLE
text

### ISSUE THREAD

**Issue by Bars026** [javascript-tutorial/ru.javascript.info#1832]
https://learn.javascript.ru/string 
![img-2023-04-05-11-11-23](https://user-images.githubusercontent.com/103095148/230021660-20f670ba-09be-443e-8a00-a9d1a8f2bae9.png)

**Comment by Alexandre887** [comment]
Добрый вечер.
В чем собственно проблема?

**Comment by Bars026** [comment]
нужно дописать под 4 стрелочку " //о " . Для эстетики.
![img-2023-04-15-07-50-22](https://user-images.githubusercontent.com/103095148/232183723-21464161-93bc-44af-a838-94ddc4f2631e.png)
