### ISSUE TITLE
Новый флаг в регулярках

### ISSUE THREAD

**Issue by alexandroppolus** [javascript-tutorial/ru.javascript.info#1833]
https://learn.javascript.ru/regexp-introduction#flagi

Время не стоит на месте, всё меняется, и js тоже. В дополнение к 6 упомянутым флагам (g, i, m, s, u, y) появился новый флаг "d", который позволяет получить индексы найденного матча и его скобочных групп. Весьма полезная фича для всяких парсингов.

**Comment by ilya-rodin** [comment]
сделаю

**Comment by ilya-rodin** [comment]
#1845
