### ISSUE TITLE
В разделе "Навигация по DOM-элементам" сказано что NodeList не имеет метода forEach() что является неверным

### ISSUE THREAD

**Issue by wombatbuddy** [javascript-tutorial/ru.javascript.info#1836]
Ссылка на текст с ошибкой: https://learn.javascript.ru/traversing-dom#kollektsii-ne-massivy
ссылка на документацию где сказано что у NodeList есть метод forEach(): https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Comment by Alexandre887** [comment]
![50](https://user-images.githubusercontent.com/74434545/232166498-6551cddc-3ad2-460b-aac1-f65e17d2c453.png)

**Comment by wombatbuddy** [comment]
Почему бы тогда не удалить страницы с ошибками? Пользователи могут попадать на них из Google поиска а не только пользуясь оглавлением. К тому же можно не заметить сообщение о том что материал устарел.

**Comment by Alexandre887** [comment]
> Почему бы тогда не удалить страницы с ошибками? Пользователи могут попадать на них из Google поиска а не только пользуясь оглавлением. К тому же можно не заметить сообщение о том что материал устарел.

Это не ошибка. NodeList действительно не имел метода forEach() до релиза ES2015. Информация в статье попросту устарела.
В удалении подобных статей нету смысла, т.к многим людям интересно почитать про старые возможности языка. Таких статей чуть больше сотни - https://github.com/javascript-tutorial/ru.javascript.info/tree/master/99-archive
В гугле попасть на них достаточно сложно, т.к в большинстве случаев по запросам выдаёт новые, современные статьи learn.javascript.ru. В крайнем случае, вверху каждой статьи присутствует большая табличка "Материал на этой странице устарел, более новая информация находится . . .", которую вы по невнимательности пропустили.
Также, на мой взгляд, читателя должно смутить отсутствие "навигации по уроку" в левой части страницы, которая присутствует в каждой современной статье.

**Comment by wombatbuddy** [comment]
Может быть в этом и есть смысл. 
Остаётся вопрос, почему в новой версии не сказано что с коллекциями можно использовать forEach()?

Ссылка на новую версию: https://learn.javascript.ru/dom-navigation#dom-kollektsii

**Comment by Alexandre887** [comment]
Если вы считаете, что в статье не хватает какой-либо информации по теме, вы всегда можете предложить свои улучшения, отправив Pull Request в репозиторий учебника.

**Comment by wombatbuddy** [comment]
ок

**Comment by wombatbuddy** [comment]
Ссылка на пул реквест: https://github.com/javascript-tutorial/ru.javascript.info/pull/1839
