### ISSUE TITLE
На страницах преподавателей курсов дёргается навигация

### ISSUE THREAD

**Issue by NiyazGaripov** [javascript-tutorial/ru.javascript.info#1838]
1. На страницах преподавателей курсов при скролле дёргается навигация по странице (sidebar__navigation).
2. На страницах преподавателей курсов при клике на пункты навигации дёргается навигация по странице (sidebar__navigation).

Пример:
https://learn.javascript.ru/profile/sergey-zelenov

https://user-images.githubusercontent.com/24496044/232250078-10c234fe-2224-4db7-8be5-82aec1370bc6.mov

**Comment by iliakan** [comment]
Спасибо, что назначил, @Alexandre887 !

А сейчас ок?

**Comment by NiyazGaripov** [comment]
В браузерах на движках Blink и Gecko - всё отлично.
В WebKit (Safari) при начальном скролле есть небольшие поддёргивания. После того как пункт навигации [О преподавателе](https://learn.javascript.ru/profile/egor-sidorov#profile-teacher-about) становится активным, то всё работает корректно и поддёргивания отсутствуют.
