### ISSUE TITLE
Неточная(?) информация о разной работе console.log/dir

### ISSUE THREAD

**Issue by oldGlobula** [javascript-tutorial/ru.javascript.info#1841]
basic-dom-node-properties#klassy-dom-uzlov
> Большинство браузеров поддерживают в инструментах разработчика две команды: console.log и console.dir. Они выводят свои аргументы в консоль. Для JavaScript-объектов эти команды обычно выводят одно и то же.

> Но для DOM-элементов они работают по-разному

В Firefox обе команды выводят элемент в виде объекта.

**Comment by Alexandre887** [comment]
Спасибо за замечание, исправили статью:
![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/bc4eb951-f3fb-43ce-b150-95d088dce703)


С Firefox 57.0 так происходит.
