### ISSUE TITLE
https://learn.javascript.ru/introduction-browser-events

### ISSUE THREAD

**Issue by userPashka** [javascript-tutorial/ru.javascript.info#1850]
Добрый день!
Я изучаю JavaScript по Вашему учебнику и хотел бы сначала поблагодарить Вас за его создание и обновления!
Поясните, пожалуйста, для чего на странице https://learn.javascript.ru/introduction-browser-events в последнем примере в строке `this[method](event);` указан параметр event, при том что в методах объекта menu onMousedown и onMouseup объект event в качестве аргумента не используется?
Может быть в предыдущих вариантах кода методов onMousedown и onMouseup аргумент event использовался, затем код упростили, убрав из него обработку event, а удалить его из параметров вызова забыли?

**Comment by Alexandre887** [comment]
Здравствуйте. 

Аргумент `event` действительно необязателен в указанном примере. Скорее всего, автор просто забыл убрать его. Статью поправили, спасибо за замечание.
