### ISSUE TITLE
Использование `export const` вместо `export let` при экспорте объекта. 

### ISSUE THREAD

**Issue by FedchenkoM** [javascript-tutorial/ru.javascript.info#1852]
Доброго времени. В разделе `https://learn.javascript.ru/modules-intro` ,
в части где вы экспортируете объект admin, возможно более уместно экспортировать 
его как const, чтобы у нас не было возможности случайно переопределить его в другом модуле. 

````
export let admin = { 
  name: "John"
};
```` 
====>>>>>>
```
export const admin = { 
  name: "John"
};
```
![Screenshot (1)](https://github.com/javascript-tutorial/ru.javascript.info/assets/73774460/d2f4fe86-a74f-45eb-bbd0-b111486ccdf9)

**Comment by Alexandre887** [comment]
Экспортируя объект `admin` как `let`, вы не сможете никаким образом переопределить его в другом модуле, т.к получите ошибку `TypeError: Assignment to constant variable` при попытке переопределения. Но, сможете переопределить `admin` в модуле, <ins>**из**</ins> которого его экспортируете.

Экспортируя объект `admin` как `const`, вы не сможете переопределить его <ins>**нигде**</ins>, даже в модуле, из которого экспортируете этот объект. Тоже будет ошибка.

Поэтому причин для внесения этой правки не вижу.
