### ISSUE TITLE
Нет запятой.

### ISSUE THREAD

**Issue by fluidliquid** [javascript-tutorial/ru.javascript.info#1853]
В разделе «use strict» (https://learn.javascript.ru/strict-mode#use-strict) не хватает запятой в третьем абзаце в предложении: «Забегая вперёд, заметим, что вместо всего скрипта "use strict" можно поставить в начале большинства видов функций», после слова «скрипта».
![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/134602756/3af5774a-f410-4ff6-abd3-20491326297c)

**Comment by ruslauz** [comment]
Здравствуйте. Не затруднит ли вас прислать ПР с правкой данной ошибки? Спасибо!

**Comment by Alexandre887** [comment]
Довольно спорный случай. Да и в целом, у предложения очень странная структура. Перефразировал следующим образом:

> **Совсем скоро мы начнём изучать функции (способ группировки команд), поэтому заранее отметим, что в начале большинства видов функций можно поставить `"use strict"`.** Это позволяет включить строгий режим только в конкретной функции. Но обычно люди используют его для всего файла.
