### ISSUE TITLE
Устарела информация или ошибка в статье "Общение между окнами"

### ISSUE THREAD

**Issue by Nover98** [javascript-tutorial/ru.javascript.info#1854]
В главе про [общение между окнами](https://learn.javascript.ru/cross-window-communication) написано, что при попытке получить доступ к iframe.contentDocument, где у iframe другой источник, будет ошибка. Но сейчас ошибки нет, а iframe.contentDocument возвращает `null`.

**Comment by Alexandre887** [comment]
Здравствуйте. В какой именно части статьи про это сказано? Процитируйте строку из главы.

**Comment by Nover98** [comment]
Добрый день, прошу прощения за долгий ответ, не видел сообщения на почте.
В стороке, куда указывает красная стрелка, не будет ошибки, там будет null.

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/37267977/6a2d6e60-4159-49d4-aefe-a69f3eb63e0e)

**Comment by Alexandre887** [comment]
В следующий раз, пожалуйста, когда открываете Issue, указывайте всю необходимую информацию сразу в описании, чтобы не приходилось уточнять.

Неточность устранена:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/3b2a9400-38dc-472b-9ed9-62dba9d16f35)
