### ISSUE TITLE
Замечание к статье https://learn.javascript.ru/introduction-browser-events

### ISSUE THREAD

**Issue by RusJstudent** [javascript-tutorial/ru.javascript.info#1860]
> Последний способ самый гибкий, однако нужно писать больше всего кода. Есть несколько типов событий, которые работают только через него, к примеру **transitionend** и DOMContentLoaded.

Поправка:
ontransitionend поддерживается во всех современных браузерах.

**Comment by Alexandre887** [comment]
Где вы нашли `ontransitionend`? Прикрепите ссылку.

**Comment by RusJstudent** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionend_event в разделе Browser compatibility

**Comment by Alexandre887** [comment]
Ни в одной современной документации не описан event "ontransitionend". В разделе "Browser Compability" я вижу только альтернативные названия event'a "transitionend", которые поддерживались **раньше**, в более ранних версиях браузеров. 

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/34e5d5d7-0fac-420c-9140-2e6d46bba248)

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/1339fc78-8f17-46d6-853c-1d13a56d3bd3)

К тому же, если данный event существует, какое его преимущество над "transitionend"? В чём его польза для разработчика?
Или Вы хотите сказать, что "transitionend" устарел, и вместо него нужно использовать "ontransitionend"? Я не понимаю суть данного Issue.

**Comment by RusJstudent** [comment]
@Alexandre887 Как я понимаю, там если указана полная поддержка, то поддерживается ontransitionend в том числе. Иначе, картина такая:
> 12 – 17 (Released 2015-07-28)
> footnote Partial support
> footnote The ontransitionend event handler property is not supported. To listen to this event, use element.addEventListener('transitionend', function() {});.
> 18 (Released 2018-10-02)
> footnote Full support

Насчет преимуществ ontransitionend над addEventListener('transitionend', ... ) - их нет, не считая более компактной записи. В статьях и без этого рекомендуется использоваться addEventListener вместо on<event>. Суть данного **issue** - поделиться своим наблюдением с вами, чтобы вы уже решили, менять предложение, которое я процитировал в начале или нет. Оно могло бы выглядеть вот так:

Есть несколько типов событий, которые работают только через него, к примеру DOMContentLoaded.

**Comment by Alexandre887** [comment]
Насчет поддержки, да, вы правы, в современных браузерах присутствует поддержка `ontransitionend`. Но как таковой причины для корректировки указанного предложения я, к сожалению, не нашел. 
Спасибо за наблюдение, обязательно присылайте issue/pull request в случае, если что-то заметите.
