### ISSUE TITLE
Возможная опечатка

### ISSUE THREAD

**Issue by evan-weissrussland** [javascript-tutorial/ru.javascript.info#1862]
В разделе "Регулярные выражения - Символьные классы" в примере №2, где alert выводит все числа номера, указаны числа 79035419441, а на мой взгляд должно быть 79031234567, т.к. исходная строка "+7(903)-123-45-67"

**Comment by Alexandre887** [comment]
Вы правы, спасибо за правку. 
В следующий раз, пожалуйста, открывайте Pull Request.
