### ISSUE TITLE
Ninja Code

### ISSUE THREAD

**Issue by miraage** [javascript-tutorial/ru.javascript.info#1865]
Здравствуйте. Много кому рекоммендую Ваш учебник, однако случайно зашел в раздел Ninja Code, и стало не по себе.
https://learn.javascript.ru/ninja-code

> Если правила, принятые в вашей команде, запрещают использовать абстрактные имена или имена из одной буквы – сокращайте их.

Если сокращение userAgent до ua еще хоть как-то понятен, то list-lst и browser-brsr не прошли бы код ревью ни в одной нормальной команде. Этот абзац вообще лучше вырезать, чтобы люди меньше говнокодили.

> Называйте переменную по типу данных, которые она хранит: str, num…

Ощущение, будто 1С битрикс разрабы писали документацию. Этого ни в коем случае не надо делать, кроме случаев, когда к нам пришел список, и нам для алгоритмической эффективности надо его преобразовать в мэп внутри какой-то функции (например, нам пришли два списка users и posts, и мы хотим каждому посту по post.authorId добавить саму сущность author, то есть смысл сделать временную переменную usersMap или usersById, которая имела бы тип `Record<string, User>`)

**Comment by Alexandre887** [comment]
> Много кому рекоммендую Ваш учебник, однако случайно зашел в раздел Ninja Code, и стало **не по себе**.

Здравствуйте. Читая вашу issue, становится не то чтобы "не по себе", становится страшно.

В самом начале статьи, прямо под заголовком, находится следующая табличка, **вытянутая во всю ширину страницы**:

![45](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/00a6ec3b-3a80-4f8b-861a-e59a098935d3)

Данная табличка (а именно её заголовок, "Осторожно, ирония!") информирует читателя о содержании статьи. Почему Вы проигнорировали её? Неизвестно.

**Comment by lufog** [comment]
А в чем вообще смысл данной статьи, налить воды? Смищно пошутить? Как дошел до этой клоунады, пропало все желание читать дальше 😕

**Comment by Alexandre887** [comment]
@lufog В статье приведено около 15 советов из разряда «как делать не надо». Это **очень** распространённые стилевые ошибки, которые сильно ухудшают качества кода в целом. Код становится намного сложнее поддерживать и работать с ним, — в частности, если это крупный проект, и вы пишите в команде. Подобные ошибки, к сожалению, зачастую появляются даже в коде опытных разработчиков.

А что касается «клоунады», — если вы не способны воспринимать информацию, написанную в нестрогом стиле, то, вероятно, единственным действенным решением для вас будет чтение [официальной спецификации](https://tc39.es/ecma262/) стандарта ECMAScript. Подобных «приколов» там вы не найдёте. 

И да, отвечая на ваш вопрос, который вы уже успели настрочить в комментариях под статьёй — всё верно, комедии больше не будет.
