### ISSUE TITLE
ошибка в учебнике

### ISSUE THREAD

**Issue by evgeny-dyakov** [javascript-tutorial/ru.javascript.info#1866]
Добрый день, вроде как ошибка в описании задачи: у вас есть массив объектов user... но массив называется userS.
Глава "методы массивов", задача [Трансформировать в объекты](https://learn.javascript.ru/array-methods#transformirovat-v-obekty)

**Comment by Alexandre887** [comment]
Здравствуйте.

Насколько я понимаю, имелось в виду "массив объектов **типа** user". Каждый объект представляет из себя одного user'a.
vasya - один юзер, petya - другой юзер и т.д.

**Comment by evgeny-dyakov** [comment]
Ааа, ну тогда да )

вт, 25 июл. 2023 г., 23:20 Aleksandras ***@***.***>:
