### ISSUE TITLE
Ошибка в статье про IndexDB

### ISSUE THREAD

**Issue by lykovrs** [javascript-tutorial/ru.javascript.info#1872]
Всё потому, что fetch является асинхронной операцией, макрозадачей. Транзакции завершаются раньше, чем браузер приступает к выполнению макрозадач.
https://learn.javascript.ru/indexeddb#avtomaticheskaya-fiksatsiya-tranzaktsiy

fetch - микротаск.
https://tr.javascript.info/microtask-queue

**Comment by Alexandre887** [comment]
Здравствуйте.

Во-первых, по ссылке [_**tr**_.javascript.info/microtask-queue](https://tr.javascript.info/microtask-queue) находится турецкая версия учебника, т.е перевод с оригинала на английском. В случае, если обновляется английская версия учебника, во все репозитории тех самых «переводов» автоматически отправляется Pull Request с изменениями, чтобы на всех языках была наиболее свежая информация. 

Оригинальная статья (**Microtasks**) давно была переработана, и в новой версии больше не содержится никаких упоминаний `fetch`. Редакторы турецкой версии учебника попросту не успели ещё принять присланные правки статьи. К тому же, как можно заметить из [чек-листа перевода статей](https://github.com/javascript-tutorial/tr.javascript.info/issues/1), к переводу **Microtasks** на турецкий ещё не приступали. 

Во-вторых, даже в устаревшей версии статьи, которая последний раз обновлялась в 2021 году, я не нашёл конкретных определений, что `fetch` — это <ins>микро</ins>задача. Вероятно, вы неправильно поняли контекст.

`fetch` — это <ins>макро</ins>таск, в статье про IndexDB всё сказано правильно. Правки не требуются.
