### ISSUE TITLE
Error in the article 

### ISSUE THREAD

**Issue by Bars026** [javascript-tutorial/ru.javascript.info#1875]
https://learn.javascript.ru/function-basics

Современные движки JavaScript поддерживают "Не найдена статья "nullish-coalescing-operator" ??" 

Возможно там была эта ссылка https://learn.javascript.ru/nullish-operators ссылка была заменена и это затронуло все статьи.

**Comment by Bars026** [comment]
![img-2023-08-05-09-57-49](https://github.com/javascript-tutorial/ru.javascript.info/assets/103095148/126acb5d-279d-4bdf-942f-59eeb21aa1f1)

**Comment by Alexandre887** [comment]
Добрый день.

Да, ссылка была заменена, вы правы. Проблему на скриншоте исправил, если увидите еще — обязательно отправляйте Pull Request.
