### ISSUE TITLE
JSHint 

### ISSUE THREAD

**Issue by Bars026** [javascript-tutorial/ru.javascript.info#1879]
https://learn.javascript.ru/coding-style JSHint  
всё (JSHint  "Это расширение устарело") 
нужно заменить текст, у меня не хватает фантазии для редактирования. 
Просто дописать  за место (" JSHint  – больше проверок, чем в JSLint.") 
это (" ̶J̶S̶H̶i̶n̶t̶ ̶ ̶–̶ ̶б̶о̶л̶ь̶ш̶е̶ ̶п̶р̶о̶в̶е̶р̶о̶к̶,̶ ̶ч̶е̶м̶ ̶в̶ ̶J̶S̶L̶i̶n̶t̶.̶ (Это расширение устарело)")  
Нужно заменить. Идеи нет стоящей.

**Comment by Alexandre887** [comment]
Почему же устарело?

**Comment by Bars026** [comment]
![img-2023-08-14-09-26-11](https://github.com/javascript-tutorial/ru.javascript.info/assets/103095148/205f4b39-48f2-4613-8594-871fff9297ea)

**Comment by Bars026** [comment]
![img-2023-08-14-09-28-35](https://github.com/javascript-tutorial/ru.javascript.info/assets/103095148/03a2962a-4237-420d-acdf-4c1fbfc016bf)

**Comment by Alexandre887** [comment]
Если посмотреть на разницу между датами релизов, можно заметить, что был и больший перерыв: 30 мая 2021 и 2 августа 2022 — 302 дня разница. После чего возобновилась разработка, хоть и с интервалами. С последнего релиза прошло пока 277 дней.

В [официальном репозитории JSHint](https://github.com/jshint/jshint) также не говорится о том, что он deprecated. Почему VS Code рекомендует не использовать его — не знаю. Если давно не было новых релизов, это же не говорит о том, что линтер сам по себе плохой или нерабочий. JSHint содержит больше проверок, чем JSLint, об этом также говорится в главе учебника.
