### ISSUE TITLE
Необходимо добавить информацию в текст про размеры и прокрутку окна.

### ISSUE THREAD

**Issue by iamlorddop** [javascript-tutorial/ru.javascript.info#1881]
В уроке не хватает информации о том, что scrollTo и scrollIntoView могут иметь объект options, как аргумент. Прошу его добавить.

> scrollTo может иметь объект options, как аргумент:
element.scrollTo(options).
options - объект с тремя свойствами:
> 
> element.scrollTo({`
>   top: 100,
>   left: 100,
>   behavior: 'smooth'
> });
> 
> где behavior: 'smooth' означает плавную прокрутку. Принимает значения "auto" или "smooth". По умолчанию "auto" - то есть, без плавной прокрутки.
> 
> Не поддерживается только в IE.
> То же самое с scrollBy.
> 
> scrollIntoView также может иметь объект options, как аргумент:
> element.scrollIntoView(options).
> options - объект с тремя свойствами:
> 
> behavior - Анимация прокрутки. Принимает значения "auto" или "smooth". По умолчанию "auto".
> block - Вертикальное выравнивание. Одно из значений: "start", "center", "end" или "nearest". По умолчанию "start".
> inline - Горизонтальное выравнивание. Одно из значений: "start", "center", "end" или "nearest". По умолчанию "nearest".
> 
> elem.scrollIntoView({block: "center", behavior: "smooth"});
> 
> behavior: "smooth" не поддерживается в IE и Safari, но начиная с версии 16.0 в Safari появилась поддержка behavior: 
> "smooth".

**Comment by Alexandre887** [comment]
Добрый вечер.

Правка достаточно неплохая и действительно имеет место быть, но, хотелось бы увидеть PR, а не Issue.

**Comment by iamlorddop** [comment]
Добрый вечер!

Поняла вас, в ближайшее время собиралась сделать PR.
