### ISSUE TITLE
Лучшее решение задачи №2

### ISSUE THREAD

**Issue by Danifka3** [javascript-tutorial/ru.javascript.info#1883]
Возможно, правильнее передавать параметр precision отдельно от объекта { template }

**Comment by Alexandre887** [comment]
Добрый вечер.

О какой задаче идёт речь?

**Comment by Danifka3** [comment]
Да, прошу прощения, не уточнил
https://learn.javascript.ru/class-inheritance#tasks
Задача 'Улучшенные часы'

**Comment by Alexandre887** [comment]
В решении всё сделано правильно, правки не требуются.
