### ISSUE TITLE
Требуются правки в главах учебника "Формат JSON, метод toJSON" и "Рекурсия и стек"

### ISSUE THREAD

**Issue by mecmep** [javascript-tutorial/ru.javascript.info#1886]
https://learn.javascript.ru/json#json-parse
В 4-ой строке типичных ошибок отсутствует запятая после значения, о чём в комментарии нет разъяснений.

https://learn.javascript.ru/recursion#svyazannyy-spisok
В альтернативном коде для создания связанного списка отсутствует 5-ая строка:
`list.next.next.next.next = null;`
Сейчас же получается, что _next_ последнего элемента равен _undefined_, что не соответствует следующему далее тексту.
Далее этот некорректный альтернативный код используется в примере добавления в список нового элемента, где тоже требуется правка.

**Comment by Alexandre887** [comment]
Спасибо за обращение, неточности исправили. В следующий раз, пожалуйста, присылайте Pull Request, а не Issue. 

- «[Руководство по редактированию учебника](CONTRIBUTING.MD)»

___

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/06606bd5-4dfc-443d-a845-fc1e2b081107)

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/0fbfa5f6-346c-4fee-8305-76b4d5be5ba1)

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/a9b7f871-069d-4bf1-9a96-27254a1eda92)
