### ISSUE TITLE
[Баг]: 472 страница 1 часть книги 2023 года

### ISSUE THREAD

**Issue by Ruslan-Muratbekov** [javascript-tutorial/ru.javascript.info#1888]
### Описание

на страницу 472 в 1 части учебника:

class User {
  constructor(name) {
    // вызывает сеттер
    this.name = name;
  }
  get name() {
    return this._name;
  }
  set name(value) {
    if (value.length < 4) {
      alert("Имя слишком короткое.");
      return;
    }
    this._name = value;
   }
}

constructor вы написали this.name а как мне кажется должно было быть this._name = name

### Как воспроизвести?

sdf

### Браузер

sdf

**Comment by Alexandre887** [comment]
**В указанном примере всё верно, правки не требуются.**

В следующий раз, если захотите исправить какую-либо информацию в учебнике, отправляйте Pull Request:

+ [Как внести правки в учебник?](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/CONTRIBUTING.md#%D0%BA%D0%B0%D0%BA-%D0%B2%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D0%B2-%D1%83%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA)

Мы не будем рассматривать подобные замечания в виде Issue.
