### ISSUE TITLE
[Баг]: function showMessage(from, text = anotherFunction()) {   // anotherFunction() выполнится только если не передан text   // результатом будет значение text }

### ISSUE THREAD

**Issue by myFullNmae** [javascript-tutorial/ru.javascript.info#1893]
### Описание

вы дали возможность запуска кода, который ничего не делает.... в разделе функиции... в принципе описали все коректно, но при запуске не видно результата в силу того что функция не была вызвана...
в принципе с тем же успехом можно отменить возможность запуска кода

### Как воспроизвести?

        function sayAboutText() {
            alert("you didn't set any text for function 'showMessage' so you see this message");
        }

         function showMessage(from, text = sayAboutText()) {
            // autor: anotherFunction() выполнится только если не передан text 
            // me: исходя из выше сказанного тело функции не будет выполняться если значение text не будет передан функции 
            from ??= null;
            text ??= null;  //данный код выпоняется если text был передан
    
            if (from && text) alert(`${from}: ${text}`);
        }

    showMessage();                      //sayAboutText() 
    showMessage("anne");                //sayAboutText()
    showMessage("anne", "you can see"); //showMessage()

### Браузер

извините за говно код

**Comment by Alexandre887** [comment]
Не совсем понятно, о чём идёт речь. Вы говорите об этом фрагменте кода?

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/9a1ea297-4cac-483e-92a8-a22fbf535c98)

Если да, то для чего открыли Issue в категории «Баг»?
