### ISSUE TITLE
Ошибка в тексте статьи

### ISSUE THREAD

**Issue by h0ttab** [javascript-tutorial/ru.javascript.info#1896]
### Описание

В статье ["Методы массивов"](https://learn.javascript.ru/array-methods#array-isarray), в разделе "Array.isArray" написано, что "Массивы не образуют отдельный тип **языка**." ❌

Я думаю, что имеется в виду "тип **данных**".✅

### Как воспроизвести?

Нужно просто открыть статью и нужный раздел, перейдя по ссылке с якорем на разделе.
https://learn.javascript.ru/array-methods#array-isarray

### Браузер

В любом браузере.

**Comment by Alexandre887** [comment]
Здравствуйте. Подскажите, вы видите в описании данного типа Issue пункт "неточность/ошибка в учебнике"?

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/f7756b0b-a378-4248-8afd-656152c70426)

Я, например, не вижу. Отправьте [Pull Request](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/CONTRIBUTING.md#%D0%BA%D0%B0%D0%BA-%D0%B2%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D0%B2-%D1%83%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA).

**Comment by h0ttab** [comment]
Согласен с вашим замечанием. Прошу прощения. Переделаю правку через pull request.
