### ISSUE TITLE
[Баг]: Promise.allSettled второй пример с опечаткой

### ISSUE THREAD

**Issue by Dzhake** [javascript-tutorial/ru.javascript.info#1913]
### Описание

В https://learn.javascript.ru/promise-api#promise-allsettled в втором примере написано "Promise.all()" хотя речь ясно идёт про "Promise.allSettled()".

### Как воспроизвести?

Что бы воспроизвести надо перейти на https://learn.javascript.ru/promise-api#promise-allsettled и увидеть код после "когда нам нужны все результаты для продолжения:"

### Браузер

У меня Chrome 119.

**Comment by Alexandre887** [comment]
Здравствуйте.

В указанной части статьи идёт сравнение уже рассмотренного метода `Promise.all` с `Promise.allSettled`. Ошибок нет.

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/29af7cab-9f4c-48bf-ad29-59e505364abd)
