### ISSUE TITLE
[Вопрос]: Ошибка описания поведения по умолчанию для F.prototype у функций

### ISSUE THREAD

**Issue by sur4a** [javascript-tutorial/ru.javascript.info#1914]
### Описание

![3E55C220-5252-46FE-8D2C-3138B8300FD2](https://github.com/javascript-tutorial/ru.javascript.info/assets/90856018/c36d8e91-6a97-4058-9512-081d4046503f)

https://learn.javascript.ru/function-prototype

здравствуйте) написано, что у «каждой функции» есть .prototype, но ведь стрелочная функция - тоже подходит под определение «функция», а у неё нет .prototype по умолчанию, может сбить с толку

**Comment by Alexandre887** [comment]
Спасибо за фидбэк, внёс уточнение в статью. В следующий раз, пожалуйста, [открывайте Pull Request](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/CONTRIBUTING.md#%D0%BA%D0%B0%D0%BA-%D0%B2%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D0%B2-%D1%83%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA).
