### ISSUE TITLE
[Баг]: предустановленное значение в тесте к задаче

### ISSUE THREAD

**Issue by svetarybalkina** [javascript-tutorial/ru.javascript.info#1917]
### Описание

В задаче №2 ["Создайте калькулятор"](https://learn.javascript.ru/task/calculator) к статье ["Методы объекта, "this"](https://learn.javascript.ru/object-methods) не совсем корректно написан тест на проверку функции read(), а именно: сразу задано название свойств 'а' и 'b', хотя в условии задачи про названия ничего не сказано. Таким образом если ученик задаёт другие имена, тест функции read() падает по этой причине.

Речь идет о куске кода из файла test.js ниже:

it('read получает два значения и сохраняет их как свойства объекта', function () {
      assert.equal(calculator.a, 2);
      assert.equal(calculator.b, 3);
      
[Ссылка на песочницу с тестами к этой задаче](https://plnkr.co/edit/8dD0zQy1BDTcwoJ3?p=preview&preview)

### Как воспроизвести?

Чтобы воспроизвести баг, нужно в вашем варианте решения к указанной задаче в функции read() поменять значения 'a' и 'b' на любые другие, скопировать получившийся код и запустить его в песочнице с тестами.

### Браузер

Chrome 108.0.5359.124

**Comment by Alexandre887** [comment]
Добрый день.

Большое спасибо за Issue, добавил уточнение в описание задачи:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/91239d59-36e3-499f-b45b-3d3e029a0d68)
