### ISSUE TITLE
[Предложение: веб-сайт]: 

### ISSUE THREAD

**Issue by TatianaLevoshko** [javascript-tutorial/ru.javascript.info#1937]
### Описание

Добрый день. Хотела бы предложить доработать или исправить карточки в статье о функциях. В частности об описании встроенных параметров. Там часто путаются понятия параметр-аргумент. Возможно для опытного разработчика это очевидно, но студент без опыта может запутаться. Прилагаю скрин. Спасибо.
![Функции - Google Chrome](https://github.com/javascript-tutorial/ru.javascript.info/assets/145283827/ff4855ee-a1e3-4496-990f-93d85ef4e75d)

**Comment by Alexandre887** [comment]
Спасибо, изменения внесены на сайт.

В следующий раз, пожалуйста, отправляйте Pull Request. [Инструкция](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/CONTRIBUTING.md#%D0%BA%D0%B0%D0%BA-%D0%B2%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D0%B2-%D1%83%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA).

**Comment by TatianaLevoshko** [comment]
Спасибо, хорошо 👍

вт, 5 мар. 2024 г., 19:48 Aleksandras ***@***.***>:
