### ISSUE TITLE
[Баг]: 

### ISSUE THREAD

**Issue by Hunter-137** [javascript-tutorial/ru.javascript.info#1939]
### Описание

В статье [про замыкание](https://learn.javascript.ru/closure#funktsiya-vnutri-if) в задаче про if есть код:
<pre>
let phrase = "Hello";

if (true) {
  let user = "John";

  function sayHi() {
    alert(`${phrase}, ${user}`);
  }
}

sayHi();
</pre>

Проблема в том, что данный код в консоли браузера и в компиляторе js отображает не ошибку, а фразу "Hello, John".

### Как воспроизвести?

Для наглядности: 
1. Запустите код по кнопке "Выполнить" на сайте учебника — alert выдаст ошибку;
2. Запустите код в консоли браузера Chrome — alert выдаст Hello, John
3. Запустите код в [компиляторе js](https://www.programiz.com/javascript/online-compiler/) — alert выдаст Hellom John

### Браузер

У меня воспроизводится этот баг в Chrome Версия 122.0.6261.129 (Официальная сборка), (64 бит)

**Comment by Alexandre887** [comment]
Здравствуйте.

Все примеры кода в учебнике запускаются в строгом режиме `"use strict"` (за исключением случаев, когда заранее упомянуто иное), об этом сказано в главе «[Строгий режим — "use strict"](https://learn.javascript.ru/strict-mode)». В строгом режиме данный код выводит ошибку, в нестрогом — нет.

**Comment by Hunter-137** [comment]
Здравствуйте! Понял, спасибо большое за объяснение.
