### ISSUE TITLE
[Вопрос]: Проблемы с логикой возникли не в задачах, а в статье.

### ISSUE THREAD

**Issue by autodatchik24** [javascript-tutorial/ru.javascript.info#1940]
### Описание

Проблемы с логикой возникли не в задачах, а в статье, где для примера работы ИЛИ, привели время работы организации, и где результатом был isWeekend. Чтобы понять приведенный пример, потребовалось миллион лет. Уважаемый админ, можно было для людей пояснить, что в данном красивом примере не предполагалось что время 12 часов выпадает на будничный день. Можете поправить?

**Comment by Alexandre887** [comment]
Здравствуйте.

Если время 12 часов выпадает на будний день, `if` и не должен работать, поскольку офис в это время открыт. Что конкретно вызывает затруднения здесь?

```js
let hour = 12;
let isWeekend = false; // установим "не выходной"

if (hour < 10 || hour > 18 || isWeekend) {
  alert("Офис закрыт.") // все операнды являются ложными, возвращается последний из них — false, поэтому alert не сработает
} else {
  alert("Офис открыт.") // сработает: выполнение кода перешло в ветку "иначе" (else), так как условие в if (...) {} было false
}
```

**Comment by autodatchik24** [comment]
Ну если установить isWeekend = false, то да. Это же если вручную указывать.
А если создать цепочкой присвоения для будних дней переменные и присвоить
последнему false, ну или без цепочки, для наглядного понимания. Просто для
новичков разобраться с первого раза трудно. Вроде если рабочий день и время
рабочее, то почему всё равно выходной выскакивает.

вс, 17 мар. 2024 г., 02:19 Aleksandras ***@***.***>:

**Comment by Alexandre887** [comment]
> А если создать цепочкой присвоения для будних дней переменные и присвоить
последнему false, ну или без цепочки, для наглядного понимания.

Слабо понимаю, о чём речь. Возможно, приведёте пример кода? 

> Просто для новичков разобраться с первого раза трудно. Вроде если рабочий день и время
рабочее, то почему всё равно выходной выскакивает.

Вроде бы, комментарий возле `alert` всё вполне объясняет. По крайней мере ни в комментариях под статьёй, ни в github    по поводу данного примера возражений не было.

**Comment by autodatchik24** [comment]
let hour = 12;
let isWeekend = true;

let Sunday = false; // И так далее..



if (hour < 10 || hour > 18 || isWeekend) {
  alert("Офис закрыт.")
} else {
  alert("Офис открыт.")
}


вс, 17 мар. 2024 г., 02:47 Aleksandras ***@***.***>:

**Comment by Alexandre887** [comment]
В логике кода ничего не поменялось, вы добавили неиспользуемую переменную `Sunday`.

**Comment by autodatchik24** [comment]
Извиняюсь, я пока во всём этом ноль, может склад ума не позволяет
воспринять данный пример с ходу.  Переменная типа isSunday может и не
используется, но если на дворе представить что Воскресенье и это рабочий
день, то трудно с ходу понять как сработает код.

вс, 17 мар. 2024 г., 02:59 Aleksandras ***@***.***>:

**Comment by Alexandre887** [comment]
>  Переменная типа isSunday может и неиспользуется, но <ins>**если на дворе представить что Воскресенье**</ins> и <ins>**это рабочий день**</ins>, то трудно с ходу понять как сработает код.

И как это следует понимать? 😂 

Я предлагаю вам лучше прислать сюда ту часть статьи, но модифицированную таким образом, чтобы она была понятна новичку. То есть готовый вариант, который вы хотели бы видеть в учебнике.

Речь об этом фрагменте всё ещё:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/f050b0fa-e92e-4804-8220-84ca953b41df)

**Comment by autodatchik24** [comment]
let hour = 12;
let isWeekend =  true;  // Будет ('Офис закрыт. ') , так как это выходной.
Если значение - false, то будет ('Офис открыт.'), так как это будет рабочий
день и рабочее время - 12.
if (hour < 10 || hour > 18 || isWeekend) {
  alert('Офис закрыт. ') ;
} else {
  alert('Офис открыт. ') ;
};

Ну или создать переменные будних дней с falsy значениями. Правда код
разбухнет тогда.  :)


вс, 17 мар. 2024 г., 15:14 Aleksandras ***@***.***>:

**Comment by autodatchik24** [comment]
Там, где группировка case идёт по уроку, переменная (а = 3), вместо (а = 2
+ 2).

**Comment by Alexandre887** [comment]
> Там, где группировка case идёт по уроку, переменная (а = 3), вместо (а = 2 + 2).

Подробнее, пожалуйста. Не совсем понятно, о чём речь. Какой урок? Что за пример?

**Comment by autodatchik24** [comment]
https://learn.javascript.ru/switch#gruppirovka-case


Посмотрите чему равна переменная (а).

пт, 3 мая 2024 г., 21:07 Aleksandras ***@***.***>:

**Comment by Alexandre887** [comment]
> https://learn.javascript.ru/switch#gruppirovka-case
>
> Посмотрите чему равна переменная (а).

В этом разделе обращается внимание читателя на часть кода с группировкой `case`, выделены строчки с 8 по 12. Эта часть сработает только в том случае, если $`\huge{a=3}`$ или $`\huge{a=5}`$. Здесь для `a` выбрано значение `3`.

В случае, если $`\large{a=2+2}`$, сработает только та часть кода, которая выводит сообщение «Правильно».

**Comment by autodatchik24** [comment]
Какая проблема изменить все варианты  case, да и значение переменной (а),
чтобы всё было правильно? Пусть группа неправильных вариантов, превратится
в правильные. А то получается, хороший урок с дурацким, наглядным примером.
Извините. А так, делайте как считаете правильно.

сб, 4 мая 2024 г., 00:00 Aleksandras ***@***.***>:

**Comment by Alexandre887** [comment]
Можно и заменить, если есть хорошая альтернатива, — нет проблем. Присылайте, посмотрим.
