### ISSUE TITLE
[Баг]: 

### ISSUE THREAD

**Issue by Kostya-x-pro** [javascript-tutorial/ru.javascript.info#1948]
### Описание

Статья "Функции" рахдел:
[Возврат значения](https://learn.javascript.ru/function-basics#vozvrat-znacheniya)

Во втором примере где спрашивается возраст если ввести возраст 1 то alert выведет "доступ получен".

 **return confirm('А родители разрешили?');**

можно сделать так:
confirm('А родители разрешили?');
return false.

будет логичнее.

### Как воспроизвести?

запустить пример в:
Статья "Функции" рахдел:
[Возврат значения](https://learn.javascript.ru/function-basics#vozvrat-znacheniya)

### Браузер

Google Chrome Версия 123.0.6312.106 (Официальная сборка), (64 бит)

**Comment by Alexandre887** [comment]
`confirm(...)` возвращает логическое значение, в зависимости от выбора кнопки: «ОК» — `true`, «Отмена» — `false`. 

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/e6b2a4f6-8f17-4be8-9f3d-250c82e30c13)

Если сделать `return false`, смысла в `confirm` не будет, поскольку всегда будет выводиться «Доступ закрыт», вне зависимости от ответа на «А родители разрешили?».

Почему считаете, что будет логичнее так сделать?

**Comment by Kostya-x-pro** [comment]
Да согласен.
