### ISSUE TITLE
[Баг]: Некоректное отображение кода на телефоне

### ISSUE THREAD

**Issue by Smit-TV** [javascript-tutorial/ru.javascript.info#1964]
### Описание

Во первых спасибо за такой классный ресурс.
Во вторых я благодарю вас за такой большой труд!
Но я заметил что в статьях где код большой код не отображается весь.
Т.е. Код виден типа так:
```javascript
class MyClass {
constructor(name) {
this.name = name;
}
getName() {
alert(this.name);
```
Проще говоря куска кода нет в видимой зоне и в писочнице тоже самое, может это у меня локальная проблема но вроде Chrome и Samsung не один в мире на одного человека
Может нужно зайти с ноутбука но просто как-то удобнее было бы чтобы с телефона можно было тоже учиться:)
Еще раз спасибо!

### Как воспроизвести?

Открыть сайт на телефоне, открыть урок с любым большим кодом 

### Браузер

Chrome  125.0.6422.53, Samsung Internet  25.0.1.3

**Comment by Alexandre887** [comment]
Добрый вечер.

Проверил в обоих браузерах, не получается воспроизвести. Не могли бы вы прислать скриншот (или запись экрана), где можно увидеть, что в мобильной версии сайта код отображается некорректно?

**Comment by Alexandre887** [comment]
@Smit-TV

**Comment by Alexandre887** [comment]
Ответа не поступило, закрываю Issue.
