### ISSUE TITLE
[Баг]: Отображаются ошибки из командной строки

### ISSUE THREAD

**Issue by vessellook** [javascript-tutorial/ru.javascript.info#1965]
### Описание

Заметил на странице https://learn.javascript.ru/selection-range следующий текст
```
/article/selection-range/range-example-p-1-3.svg: Command failed: identify-im6.q16: unable to create temporary file `/tmp/magick-3514njqEvi0F9mSj': No space left on device @ error/delegate.c/InvokeDelegate/1782. identify-im6.q16: unable to open file `/tmp/magick-3514njqEvi0F9mSj': No such file or directory @ error/constitute.c/ReadImage/544.
```

Он повторяется несколько раз, с разными путями /tmp/magick-3514njqEvi0F9mSj

Может, ещё на каких-то страницах это встречается 

### Как воспроизвести?

1. Открыть страницу https://learn.javascript.ru/selection-range
2. Перейти к разделу "Выделение частей текстовых узлов"
3. Посмотреть на вторую строку в разделе

### Браузер

Chrome 125.0.6422.60

**Comment by Alexandre887** [comment]
Добрый вечер. Большое спасибо за Issue, внёс изменения на сайт. Теперь всё отображается правильно:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/20f899ea-f312-4933-b5c6-9dfcff810951)
