### ISSUE TITLE
[Баг]: Неточный ответ в задаче "Функция внутри if"

### ISSUE THREAD

**Issue by s0nought** [javascript-tutorial/ru.javascript.info#1970]
### Описание

Условие:

```
Посмотрите на код. Какой будет результат у вызова на последней строке?

let phrase = "Hello";

if (true) {
  let user = "John";

  function sayHi() {
    alert(`${phrase}, ${user}`);
  }
}

sayHi();
```

Ответ:

```
Результатом будет ошибка.

Функция sayHi объявлена внутри if, так что она живёт только внутри этого блока. Снаружи нет sayHi.
```

В строгом режиме - ошибка.

![strict](https://github.com/javascript-tutorial/ru.javascript.info/assets/70777299/234438de-8431-4624-9905-059bfadd4d8c)

Без - нет.

![non-strict](https://github.com/javascript-tutorial/ru.javascript.info/assets/70777299/50863314-5062-4eec-abb9-5e00add2a446)

### Как воспроизвести?

1. Открыть https://learn.javascript.ru/task/function-in-if
2. Скопировать код задачи
3. Открыть новую вкладку с DevTools на Console
4. Вставить из буфера обмена и нажать Enter

### Браузер

Chrome 125.0.6422.113

Firefox 126.0.1

**Comment by Alexandre887** [comment]
Все примеры кода в учебнике подразумевают использование строгого режима в них. Об этом написано в самом начале, в статье «[Строгий режим — "use strict"](https://learn.javascript.ru/strict-mode)». Однако, поскольку это не первая Issue конкретно по этой задаче, добавляю уточнение.  

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/102c94e8-b6c2-4d2f-a57a-bc965c15126e)
