### ISSUE TITLE
Не всё правильно про ?.

### ISSUE THREAD

**Issue by oleedd** [javascript-tutorial/ru.javascript.info#1995]
### Описание

Статья: https://learn.javascript.ru/optional-chaining
![image](https://github.com/user-attachments/assets/b0d94802-ef36-4adb-8b9d-a5278064ba38)
Это оператор. Вот: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Optional_chaining
И он есть в списке JS операторов.

![image](https://github.com/user-attachments/assets/5806aa06-cfcb-451d-960c-2c5d60d6a724)
Его нельзя сполифилить, поскольку это оператор. Мы не можем объяснить движку, что такое `?.`.
Этот общий блок "Новая возможность" здесь вводит людей в заблуждение, будто для него возможно написать полифил.

**Comment by oleedd** [comment]
Заодно кое-что бы поправил.
1) "Чтобы он не скрывал от нас ошибки программирования, если они возникнут" — здесь лучше заменить на "если они есть", а то "в коде возникли ошибки" — это не по-русски.
2) "ошибки могут замалчиваться там, где это неуместно" — не очень по-русски, как бы все ошибки неуместны, может, "когда это неуместно"? Типа когда ищем, почему не работает как положено.
3) "…Или ещё один пример" — так нельзя по правилам пунктуации.

**Comment by oleedd** [comment]
Заодно кое-что бы поправил.
1\) "Чтобы он не скрывал от нас ошибки программирования, если они возникнут" — здесь лучше заменить на "если они есть", а то "если в коде возникнут ошибки" — это не по-русски.
2\) "ошибки могут замалчиваться там, где это неуместно" — не очень по-русски, как бы все ошибки неуместны, может, "когда это неуместно"? Типа когда ищем, почему не работает как положено.
3\) "…Или ещё один пример" — так нельзя по правилам пунктуации.

**Comment by Alexandre887** [comment]
В вашей прошлой issue я уже говорил, что такие правки нужно присылать PR'ом, в репозитории учебника [есть](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/CONTRIBUTING.md#%D0%BA%D0%B0%D0%BA-%D0%B2%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D0%B2-%D1%83%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA) пошаговое объяснение, как это сделать.

**Comment by oleedd** [comment]
И как вы ник запомнили... Правка только для первого, второе и третье вам исправлять. Исходя из задумки (автору виднее).
Но это дополнительно, а основная проблема в первом комментарии.

**Comment by oleedd** [comment]
И как вы ник запомнили... Правка только для первого, второе и третье вам исправлять. Исходя из задумки (автору виднее).
Но это дополнительно, а основная проблема в первом посте.

**Comment by Alexandre887** [comment]
По-моему я уже написал, что требуется сделать.

**Comment by oleedd** [comment]
Насчёт чего? Насчёт одной правки? Для остального у меня нет однозначного исправления. В 2 смысл неясен, а в 3 может быть нужным сделать связку вместо многоточия. А исправлять "это не оператор" — это уж надо статью немного перестроить. Здесь вообще без понятия.
Мне не нравится копирование в свой профиль проектов всего лишь для исправления. Считаю, что это логично, только когда намерен разрабатывать свой проект на основе другого. А для исправлений это дурацкая система. Было бы возможно исправлять здесь (типа как на Википедии) — может, хотелось бы этим заняться. (Я в курсе, что на Github только так можно. Поэтому предлагал добавить редактирование на сайт. Пусть бот сюда переносит. Было бы гораздо эффективнее, наверно, ошибок бы вообще не осталось. Ведь не у всех есть аккаунт на Github, и единицы из обнаруживших ошибку пойдут изучать, как сделать Pull request.)

**Comment by Alexandre887** [comment]
Ручной перенос замечаний на сайт из issue неудобен. По созданию PR инструкция максимально примитивная, ничего изучать не надо; все неоднозначности решаются в обсуждении PR. Из профиля проект удаляется за 10 секунд, проблемы это сделать нет. Помимо моего времени вы тратите и своё, ибо расписывать диссертацию "здесь по-русски, а здесь не по-русски" сложнее, чем просто поудалять лишние запятые и перефразировать конкретные предложения.

**Comment by oleedd** [comment]
Там надо указать причину, как и здесь. Поэтому "диссертация" нужна и там.
Пусть инструкция примитивная, но расписано будто на страниц десять.
Зачем ручной перенос из issue, если можно просто взять и исправить, будучи "Member"...
В любом случае у меня лишь одна правка. Другие — просто указания на ошибку, не стал бы самостоятельно их править (честно). Даже если что-то коряво звучит — это уже как минимум стилистическая ошибка.
Ну и это не столь важно. Более важное в первом посте. А исправление этого — это точно не ко мне.

**Comment by Alexandre887** [comment]
Вас никто не обязывает заполнять описание PR по шаблону, это рекомендация. С PR все предлагаемые автором правки вносятся по нажатию на одну кнопку, конкретно в этом для редакторов плюс. Также есть возможность комментировать конкретные части вносимых изменений. Одна правка, десять правок — роли не играет. И, тем более, в описании того типа issue, который вы выбрали, чёрным по белому написано, для каких конкретно тем эта категория (то ли вы выбрали её рандомно, то ли всё описание пролистали). Дальнейших объяснений я давать не буду, поскольку вижу, что уже начинается хождение по кругу. Всю необходимую информацию для внесения изменений я привел выше.

**Comment by oleedd** [comment]
Не знал, но думаю, что без указания причины стилистическую правку, скорее всего, отклонят.
Не знал, что все по нажатию на одну кнопку. Считал, что для каждого исправления должен быть отдельный pull request.
В описании этого типа issue есть "ошибки/опечатки". Это не подходит под "bug", где "что-то неправильно отображается; не работает; работает не так, как нужно". Подходящий тип не нашёл.
Не имея исправления, в котором уверен, точно не стал бы открывать pull request. А из-за одной правки, в которой уверен, не хочу начинать. И вообще, стилистику лучше поправлять тому, кто переводил (это больше похоже на перевод, потому что другие статьи более грамотные).
Если у меня будет много исправлений, в которых уверен, то рассмотрю открытие pull request. Но не из-за одного. Одно уже можете сами внести.
Насчёт остальных — просто сообщил об ошибках, не знаю, как там лучше исправить.

**Comment by Alexandre887** [comment]
> без указания причины стилистическую правку, скорее всего, отклонят.

Рассмотрением PR занимаюсь я.

> Подходящий тип не нашёл.

Поскольку для ваших правок его нет, для этого есть PR. Предварительного обсуждения требуют крупные изменения, по типу создания новой статьи, нового цикла статей.

**Comment by oleedd** [comment]
Ну ок, буду знать. Думал, что несколько человек этим занимаются.
Ну ведь бывают же ситуации, когда видишь, что информация неверна, но не знаешь, как исправить. Как с этим "это не оператор". Для таких случаев нет label.
Тогда предлагаю вам уже заменить на "если они есть", если оно ок. А для других двух в идеале, чтобы поправил тот, кто переводил.
А при наличии нескольких исправлений буду уже делать pull request.
Ну а основная проблема — это, наверно, уже по части автора учебника. Насколько мне известно, другие не пишут статьи, а переводят/улучшают.

**Comment by oleedd** [comment]
Вместо "если они есть", наверно, лучше "если они будут". Вот так вот, если бы открыл pull request, пришлось бы ещё раз открывать.

**Comment by Alexandre887** [comment]
Видимо, для ТС проще часами объяснять, почему он не будет открывать PR, нежели чем просто взять и сделать это, даже для одной правки. Issue закрываю.

**Comment by oleedd** [comment]
Ну да, тоже так считаю. Лучше переоткрыть без этих всех off-topic комментариев.
