### ISSUE TITLE
[Баг]: Не отображаются изображения на странице cookie

### ISSUE THREAD

**Issue by YaroslavShilov** [javascript-tutorial/ru.javascript.info#2009]
### Описание

На странице https://learn.javascript.ru/cookie изображения не отображаются в некоторых местах.
При этом в исходном файле на GitHub (https://github.com/javascript-tutorial/ru.javascript.info/blob/master/6-data-storage/01-cookie/article.md) изображения отображаются корректно.

![1](https://github.com/user-attachments/assets/f7aaebf2-7551-4a6f-af8b-81bc8429d9bd)
![2](https://github.com/user-attachments/assets/9affea7c-5d53-47bd-9119-0430e6668458)
![3](https://github.com/user-attachments/assets/5891b1f8-da75-4457-96e4-7a8de6c991f6)

### Как воспроизвести?

Открыл страницу

### Браузер

Использовал браузер Chrome Version 130.0.6723.92 (Official Build) (64-bit), в других браузерах не тестировал

**Comment by Alexandre887** [comment]
Добрый день. Пожалуйста, проверьте страницу еще раз. Проблем сейчас я не наблюдаю.

**Comment by YaroslavShilov** [comment]
> Добрый день. Пожалуйста, проверьте страницу еще раз. Проблем сейчас я не наблюдаю.

Проверил, теперь работает 👍
