### ISSUE TITLE
Кому следует решать конфликты и как?

### ISSUE THREAD

**Issue by xcurveballx** [javascript-tutorial/ru.javascript.info#211]
В списке PR есть уже немало PR с конфликтами. Кто их должен решать и чем руководствоваться? 

Например,

#208 #196 #185

**Comment by dandgerson** [comment]
Вот в этом #181 =)
Продублирую сюда свой вопрос https://github.com/javascript-tutorial/ru.javascript.info/pull/181#issuecomment-495756398

**Comment by dandgerson** [comment]
> Вот в этом #181 =)
> Продублирую сюда свой вопрос [#181 (comment)](https://github.com/javascript-tutorial/ru.javascript.info/pull/181#issuecomment-495756398)

с этим уже разобрались =)

**Comment by oshliaer** [comment]
Решать должны те, кто иммет право на запись в ветку или в реквест.

**Comment by iliakan** [comment]
Большинство конфликтов связаны с тем, что я после ревью делаю улучшения в англ версии. 

Фактически они являются бэкпортом с русского. Так что при разрешении вы, скорее всего, увидите, что текст и в англ и в рус версии одинаковый, и можно просто взять русскую версию из конфликта.

Бывает, конечно, и иначе - в англ версии появились новые изменения с момента, когда вы начали перевод. Тогда их следует учесть. 

Разрешать конфликт вполне может автор перевода.
