### ISSUE TITLE
Ошибка в ответе теста

### ISSUE THREAD

**Issue by roman-sergeenko** [javascript-tutorial/ru.javascript.info#227]
Привет, обнаружил ошибку в ответе теста на этот вопрос
![image](https://user-images.githubusercontent.com/20598230/58804649-08b79a00-861b-11e9-801f-f3bc1d03925a.png)
UPD: Да, увидел перед началом теста, что везде 'use strict', может тогда стоит дописать в вопрос?
Тем более уже есть такие вопросы. Думаю может ввести в заблуждение
![image](https://user-images.githubusercontent.com/20598230/59025750-85d25180-885d-11e9-9d83-19f08154eac2.png)

**Comment by iliakan** [comment]
В начале каждого вопроса что ли писать?
