### ISSUE TITLE
Разделы для ES-2016/2017/2018/2019

### ISSUE THREAD

**Issue by oleedd** [javascript-tutorial/ru.javascript.info#238]
Стоит добавлять ES разделы для каждого года, тем более следующие релизы после 2015 намного меньше.
Каждый год добавляются интересные возможности.
Сейчас мало информации об этих новшествах (они уже реализованы в браузерах). А на нормальном доступном языке с понятными примерами, как в этом учебнике, вообще не найти.
Стандарт JavaScript развивается, а учебник - нет.

**Comment by iliakan** [comment]
Почему нет, когда да? Вы старую редакцию только видели наверняка.

**Comment by oleedd** [comment]
Так а что есть разделы для новых ES (после 2015)?
А что есть другое на русском, кроме этого?
https://learn.javascript.ru/

**Comment by oleedd** [comment]
@iliakan
> Почему нет, когда да?

А что есть темы про новые ES после 2015?
> Вы старую редакцию только видели наверняка.

А что есть другая редакция на русском, кроме этой?
https://learn.javascript.ru/
За год не вижу в ней новых тем.
