### ISSUE TITLE
Вычитка

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ru.javascript.info#288]
Перед тем, как показывать новый учебник людям, его нужно вычитать.

Даже после хорошего перевода бывают предложения, написанные не совсем по-русски, непонятные объяснения и т.п.

Чтобы это отловить, достаточно прочитать русский текст свежим взглядом.

Можно сделать это локально, установив сервер <https://github.com/javascript-tutorial/server>.

Если что не так - PR. Я сам помечу статью галочкой после вычитки.

Спасибо!

### An introduction

* [x] [An Introduction to JavaScript](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/01-getting-started/1-intro) 
* [x] [Manuals and specifications](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/01-getting-started/2-manuals-specifications) 
* [x] [Code editors](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/01-getting-started/3-code-editors) 
* [x] [Developer console](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/01-getting-started/4-devtools) 

### JavaScript Fundamentals

* [x] [Hello, world!](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/01-hello-world) 
* [x] [Code structure](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/02-structure) 
* [x] [The modern mode, "use strict"](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/03-strict-mode) 
* [x] [Variables](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/04-variables) 
* [x] [Data types](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/05-types) 
* [x] [Type Conversions](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/06-type-conversions) 
* [x] [Operators](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/07-operators) 
* [x] [Comparisons](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/08-comparison) 
* [x] [Interaction: alert, prompt, confirm](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/09-alert-prompt-confirm) 
* [x] [Conditional operators: if, '?'](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/10-ifelse) 
* [x] [Logical operators](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/11-logical-operators) 
* [x] [Loops: while and for](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/12-while-for) 
* [x] [The "switch" statement](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/13-switch) 
* [x] [Functions](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/14-function-basics) 
* [x] [Function expressions and arrows](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/15-function-expressions-arrows) 
* [x] [JavaScript specials](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/16-javascript-specials) 

### Code quality

* [x] [Debugging in Chrome](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/03-code-quality/01-debugging-chrome) 
* [x] [Coding Style](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/03-code-quality/02-coding-style) 
* [x] [Comments](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/03-code-quality/03-comments) 
* [x] [Ninja code](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/03-code-quality/04-ninja-code) 
* [x] [Automated testing with mocha](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/03-code-quality/05-testing-mocha) 
* [x] [Polyfills](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/03-code-quality/06-polyfills) 

### Objects: the basics

* [x] [Objects](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/04-object-basics/01-object) 
* [x] [Garbage collection](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/04-object-basics/02-garbage-collection) 
* [x] [Symbol type](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/04-object-basics/03-symbol) 
* [x] [Object methods, "this"](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/04-object-basics/04-object-methods) 
* [x] [Object to primitive conversion](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/04-object-basics/05-object-toprimitive) 
* [x] [Constructor, operator "new"](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/04-object-basics/06-constructor-new) 

### Data types

* [x] [Methods of primitives](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/01-primitives-methods) 
* [x] [Numbers](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/02-number) 
* [x] [Strings](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/03-string) 
* [x] [Arrays](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/04-array) 
* [x] [Array methods](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/05-array-methods) 
* [x] [Iterables](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/06-iterable) 
* [x] [Map and Set](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/07-map-set) 
* [x] [WeakMap and WeakSet](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/08-weakmap-weakset) 
* [x] [Object.keys, values, entries](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/09-keys-values-entries) 
* [x] [Destructuring assignment](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/10-destructuring-assignment) 
* [x] [Date and time](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/11-date) 
* [x] [JSON methods, toJSON](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/05-data-types/12-json) 

### Advanced working with functions

* [x] [Recursion and stack](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/01-recursion) 
* [x] [Rest parameters and spread operator](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/02-rest-parameters-spread-operator) 
* [x] [Closure](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/03-closure) 
* [x] [The old "var"](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/04-var) 
* [x] [Global object](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/05-global-object) 
* [x] [Function object, NFE](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/06-function-object) 
* [x] [The "new Function" syntax](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/07-new-function) 
* [x] [Scheduling: setTimeout and setInterval](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/08-settimeout-setinterval) 
* [x] [Decorators and forwarding, call/apply](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/09-call-apply-decorators) 
* [x] [Function binding](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/10-bind) 
* [x] [Arrow functions revisited](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/12-arrow-functions) 

### Object properties configuration

* [x] [Property flags and descriptors](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/07-object-properties/01-property-descriptors) 
* [x] [Property getters and setters](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/07-object-properties/02-property-accessors) 

### Prototypes, inheritance

* [x] [Prototypal inheritance](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/08-prototypes/01-prototype-inheritance) 
* [x] [F.prototype](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/08-prototypes/02-function-prototype) 
* [x] [Native prototypes](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/08-prototypes/03-native-prototypes) 
* [x] [Prototype methods, objects without __proto__](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/08-prototypes/04-prototype-methods) 

### Classes

* [x] [Class basic syntax](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/09-classes/01-class) 
* [x] [Class inheritance](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/09-classes/02-class-inheritance) 
* [x] [Static properties and methods](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/09-classes/03-static-properties-methods) 
* [x] [Private and protected properties and methods](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/09-classes/04-private-protected-properties-methods) 
* [x] [Extending built-in classes](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/09-classes/05-extend-natives) 
* [x] [Class checking: "instanceof"](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/09-classes/06-instanceof) 
* [x] [Mixins](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/09-classes/07-mixins) 

### Error handling

* [x] [Error handling, "try..catch"](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/10-error-handling/1-try-catch) 
* [x] [Custom errors, extending Error](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/10-error-handling/2-custom-errors) 

### Promises, async/await

* [x] [Introduction: callbacks](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/11-async/01-callbacks) 
* [x] [Promise](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/11-async/02-promise-basics) 
* [x] [Promises chaining](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/11-async/03-promise-chaining) 
* [x] [Error handling with promises](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/11-async/04-promise-error-handling) 
* [x] [Promise API](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/11-async/05-promise-api) 
* [x] [Promisification](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/11-async/06-promisify) 
* [x] [Microtasks](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/11-async/07-microtask-queue)
* [x] [Async/await](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/11-async/08-async-await) 

### Generators, advanced iteration

* [x] [Generators](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/12-generators-iterators/1-generators) 
* [x] [Async iterators and generators](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/12-generators-iterators/2-async-iterators-generators) 

### Modules

* [x] [Modules, introduction](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/13-modules/01-modules-intro) 
* [x] [Export and Import](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/13-modules/02-import-export) 
* [x] [Dynamic imports](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/13-modules/03-modules-dynamic-imports) 

### Miscellaneous

* [x] [Proxy and Reflect](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/99-js-misc/01-proxy) 
* [x] [Eval: run a code string](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/99-js-misc/02-eval)

### Document

* [x] [Browser environment, specs](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/01-browser-environment) 
* [x] [DOM tree](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/02-dom-nodes) 
* [x] [Walking the DOM](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/03-dom-navigation) 
* [x] [Searching: getElement*, querySelector*](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/04-searching-elements-dom) 
* [x] [Node properties: type, tag and contents](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/05-basic-dom-node-properties) 
* [x] [Attributes and properties](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/06-dom-attributes-and-properties) 
* [x] [Modifying the document](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/07-modifying-document) 
* [x] [Styles and classes](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/08-styles-and-classes) 
* [x] [Element size and scrolling](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/09-size-and-scroll) 
* [x] [Window sizes and scrolling](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/10-size-and-scroll-window) 
* [x] [Coordinates](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/11-coordinates) 

### Introduction to Events

* [x] [Introduction to browser events](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/2-events/01-introduction-browser-events) 
* [x] [Bubbling and capturing](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/2-events/02-bubbling-and-capturing) 
* [x] [Event delegation](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/2-events/03-event-delegation) 
* [x] [Browser default actions](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/2-events/04-default-browser-action) 
* [x] [Dispatching custom events](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/2-events/05-dispatch-events) 

### UI Events

* [x] [Mouse events basics](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/3-event-details/1-mouse-events-basics) 
* [x] [Moving: mouseover/out, mouseenter/leave](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave) 
* [x] [Drag'n'Drop with mouse events](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/3-event-details/4-mouse-drag-and-drop) 
* [x] [Keyboard: keydown and keyup](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/3-event-details/5-keyboard-events) 
* [x] [Scrolling](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/3-event-details/8-onscroll) 

### Forms, controls

* [x] [Form properties and methods](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/4-forms-controls/1-form-elements) 
* [ ] [Focusing: focus/blur](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/4-forms-controls/2-focus-blur) 
* [ ] [Events: change, input, cut, copy, paste](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/4-forms-controls/3-events-change-input) 
* [ ] [Forms: event and method submit](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/4-forms-controls/4-forms-submit)

### Document and resource loading

* [ ] [Page: DOMContentLoaded, load, beforeunload, unload](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/5-loading/01-onload-ondomcontentloaded) 
* [ ] [Scripts: async, defer](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/5-loading/02-script-async-defer) 
* [ ] [Resource loading: onload and onerror](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/5-loading/03-onload-onerror) 

### Miscellaneous

* [x] [Mutation observer](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/99-ui-misc/01-mutation-observer) 
* [ ] [Selection and Range](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/99-ui-misc/02-selection-range)
* [x] [Event loop: microtasks and macrotasks](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/99-ui-misc/03-event-loop)

## Frames and windows

* [ ] [Popups and window methods](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/3-frames-and-windows/01-popup-windows) 
* [ ] [Cross-window communication](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/3-frames-and-windows/03-cross-window-communication) 
* [ ] [The clickjacking attack](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/3-frames-and-windows/06-clickjacking) 

## Binary data, files

* [ ] [ArrayBuffer, binary arrays](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/4-binary/01-arraybuffer-binary-arrays) 
* [x] [TextDecoder and TextEncoder](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/4-binary/02-text-decoder) 
* [ ] [Blob](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/4-binary/03-blob) 
* [ ] [File and FileReader](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/4-binary/04-file) 

## Network requests

* [x] [Fetch](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/01-fetch)
* [x] [FormData](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/02-formdata)
* [x] [Fetch: Download progress](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/03-fetch-progress) 
* [x] [Fetch: Abort](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/04-fetch-abort) 
* [x] [Fetch: Cross-Origin Requests](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/05-fetch-crossorigin) 
* [x] [Fetch API](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/06-fetch-api) 
* [x] [URL objects](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/07-url) 
* [x] [XMLHttpRequest](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/08-xmlhttprequest) 
* [x] [Resumable file upload](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/09-resume-upload)
* [x] [Long polling](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/10-long-polling)
* [x] [WebSocket](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/11-websocket) 
* [ ] [Server Sent Events](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/5-network/12-server-sent-events)

## Storing data in the browser

* [ ] [Cookies, document.cookie](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/6-data-storage/01-cookie) 
* [ ] [LocalStorage, sessionStorage](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/6-data-storage/02-localstorage) 
* [ ] [IndexedDB](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/6-data-storage/03-indexeddb) 

## Animation

* [ ] [Bezier curve](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/7-animation/1-bezier-curve) 
* [ ] [CSS-animations](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/7-animation/2-css-animations) 
* [ ] [JavaScript animations](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/7-animation/3-js-animation) 

## Web components

* [ ] [From the orbital height](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/8-web-components/1-webcomponents-intro) 
* [ ] [Custom elements](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/8-web-components/2-custom-elements) 
* [ ] [Shadow DOM](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/8-web-components/3-shadow-dom) and events 
* [ ] [Template element](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/8-web-components/4-template-element) 
* [ ] [Shadow DOM slots, composition](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/8-web-components/5-slots-composition) 
* [ ] [Shadow DOM styling](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/8-web-components/6-shadow-dom-style) 
* [ ] [Shadow DOM and events](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/8-web-components/7-shadow-dom-events) 

## Regular expressions

* [x] [Patterns and flags](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/01-regexp-introduction) 
* [x] [Methods of RegExp and String](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/02-regexp-methods) 
* [x] [Character classes](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/03-regexp-character-classes) 
* [x] [Escaping, special characters](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/04-regexp-escaping) 
* [x] [Sets and ranges [...]](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/05-regexp-character-sets-and-ranges) 
* [x] [Quantifiers +, *, ? and {n}](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/07-regexp-quantifiers) 
* [x] [Greedy and lazy quantifiers](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/08-regexp-greedy-and-lazy) 
* [x] [Capturing groups](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/09-regexp-groups) 
* [x] [Backreferences in pattern: \n and \k](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/10-regexp-backreferences) 
* [x] [Alternation (OR) |](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/11-regexp-alternation) 
* [x] [String start ^ and finish $](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/12-regexp-anchors) 
* [x] [Multiline mode, flag "m"](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/13-regexp-multiline-mode) 
* [x] [Lookahead and lookbehind](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/14-regexp-lookahead-lookbehind) 
* [x] [Infinite backtracking problem](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/15-regexp-infinite-backtracking-problem) 
* [x] [Unicode: flag "u"](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/20-regexp-unicode) 
* [x] [Unicode character properties \p](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/21-regexp-unicode-properties) 
* [x] [Sticky flag "y", searching at position](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/9-regular-expressions/22-regexp-sticky)

**Comment by iliakan** [comment]
@javascript-tutorial/translate-ru

**Comment by iliakan** [comment]
@javascript-tutorial/translate-ru почитайте, что получилось, пожалуйста.

**Comment by oshliaer** [comment]
На вычитке.

**Comment by iliakan** [comment]
@javascript-tutorial/translate-ru up =)

**Comment by xcurveballx** [comment]
@iliakan По вопросу вычитки я думаю так: вычитывать стоит дать или проф. редактору с целью исправления каких-то неточностей/ошибок на проф. уровне или вычитывать следует автору с целью проверить, всё ли так в плане единого авторского стиля и фактического изложения материала.

Предлагать вычитывать всем желающим мне кажется контрпродуктивным, так как у всех разное мышление, разные привычные фразы (многие из других стран вообще) и технический кругозор, не говоря уже о грамотности.

Как вариант, поскольку так или иначе все главы были прочитаны во время перевода и ревью, то можно считать учебник готовым, а дальнейшие правки/улучшения производить ориентируясь на комментарии читателей - кому что непонятно, кто где ошибку заметит и т.д. Как-то так.

**Comment by iliakan** [comment]
Автор уже проверил =), но любой перевод нуждается в шлифовке, при чтении на свежую голову корявые обороты и тавтологии становятся видны.

**Comment by iliakan** [comment]
Читаю вот и вижу, где-то фразы недопереведены, где-то оборот не по-русски звучит.

**Comment by iliakan** [comment]
@javascript-tutorial/translate-ru Может кто-то поучаствовать в вычитке? Внимательно прочитать текст, где надо - улучшить фразы, иногда доперевести по мелочи. 

Если возьмете какой-то раздел из первых - напишите, я тогда более сложные вещи буду читать.

**Comment by xcurveballx** [comment]
@iliakan могу взять раздел Objects: the basics

**Comment by iliakan** [comment]
@aruseni у вас были очень дельные комментарии по строкам, может быть, вы сможете поучаствовать в вычитке?

Кстати, я сделал механизм перевода картинок (замены фраз в SVG), там местами есть несоответствие текста переведённого тому, что в иллюстрациях. 

Можно либо вернуть в тексте англ, либо в картинках перевести (см файл images.yml в корне)

**Comment by iliakan** [comment]
@xcurveballx вычитал =) Может, регэкспы (если в них разбираешься хорошо)? или Animation?

**Comment by aruseni** [comment]
@iliakan Спасибо!

Беру Scrolling.

**Comment by iliakan** [comment]
Картинки я вроде перевёл )

**Comment by iliakan** [comment]
В переводах много ошибок. Вычитывать необходимо.

**Comment by oshliaer** [comment]
> В переводах много ошибок. Вычитывать необходимо.

Как отправлять PR? На каждую ошибку?

**Comment by iliakan** [comment]
На статью. Потом я здесь помечу.

**Comment by oshliaer** [comment]
@iliakan , зацени #446, пожалуйста. Или надо искать только грубые нарушения текста?

**Comment by xcurveballx** [comment]
@iliakan При попытке открыть по ссылке статью про карринг - https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/06-advanced-functions/11-currying-partials открывается страница 404. Что-то не так с ссылкой или изменилась структура учебника?

**Comment by oshliaer** [comment]
@xcurveballx переименовано без изменений https://github.com/javascript-tutorial/ru.javascript.info/commit/ce7a22a7739da2799d97f8d59290ffa7f90ea135

```sh
$user⎇master > git log -p --follow -- 1-js/06-advanced-functions/11-currying-partials
```

**Comment by iliakan** [comment]
@xcurveballx да, переименовал, я с сайта всё читаю, поэтому не заметил.

**Comment by oshliaer** [comment]
@iliakan , я читаю с локального сервера только `master`. Это же верный путь?

**Comment by iliakan** [comment]
в смысле ветка? ветка master - да, верная.

**Comment by xcurveballx** [comment]
@iliakan в разделе Data types последние несколько статей не открываются по ссылке - 404.

**Comment by iliakan** [comment]
@xcurveballx Там статья map/set/weakmap/weakset была разделена на две. Обновил список, сейчас должно быть ок.

**Comment by iliakan** [comment]
Обновлён раздел "регулярные выражения". Сами темы не поменялись, скорее большой рефакторинг, чтобы сделать всё проще и понятнее. Просьба прочитать, написать если что-то не так.

**Comment by iliakan** [comment]
Пользуясь случаем - кто-то мог бы сделать обратную операцию: перевести обновлённый русский вариант на английский?

**Comment by Dziamid-Harbatsevich** [comment]
_https://learn.javascript.ru/js_
That`s a **new link** for book "Язык программирования JavaScript" (RU)
