### ISSUE TITLE
select onchange

### ISSUE THREAD

**Issue by maxymczech** [javascript-tutorial/ru.javascript.info#298]
https://learn.javascript.ru/events-change
Допишите плз к тому, как работает change на <select>: если перевести фокус на элемент <select> и на клавиатуре нажимать стрелки вверх/вниз, событие change сработает только когда фокус уйдет с элемента.

**Comment by iliakan** [comment]
Это для какого элемента?

**Comment by maxymczech** [comment]
```
<select>
 <option>
</select>
```

**Comment by iliakan** [comment]
Попробовал в Chrome https://plnkr.co/edit/vP7Bb24ANRdZX5GjfWVQ?p=preview

Вот видео - событие триггерится при смене варианта с клавиатуры https://jmp.sh/9Bz7eaN

**Comment by maxymczech** [comment]
Проверил - был неправ, признаки старческой деменции налицо. Сорян что побеспокоил :)
https://jsfiddle.net/awotgn4r/

**Comment by iliakan** [comment]
была такая проблема в старых ie
