### ISSUE TITLE
15-regexp-infinite-backtracking-problem

### ISSUE THREAD

**Issue by alexandroppolus** [javascript-tutorial/ru.javascript.info#311]
Приветствую!
Не совсем согласен с пунктом "Назад к тегам" в статье. На самом деле атрибуты не группируются разными кучками, одно значение для повторяющегося паттерна внутри скобок `(...)*` всегда содержит один атрибут: (a=b) (a=b) (a=b) (a=b) - только вот так.
А засада в пробелах, разделяющих атрибуты: паттерн `\s*\w+=\w+\s*` допускает пробелы в вначале и в конце, и регексовый движок тупо перекидывает пробелы между соседними значениями.
Отсюда вывод: во многих случаях проблема возникает из-за размытой границы для значений повторяющегося паттерна. В данном примере достаточно выкинуть последний `\s*` из группы, и всё как рукой снимет.
И, кстати, именно по такой вот размытой границе легче всего заметить проблемный регекс.

**Comment by iliakan** [comment]
Бэктрекинг заключается в том, что при несовопадении уменьшается кол-во применений квантификатора.  Так что `(...)*` может в процессе поиска содержать `(a=b)`, `(a=b) (a=b)` и так далее. 

С этим что-то не так?

**Comment by alexandroppolus** [comment]
Применений квантификатора в итоге всегда будет ровно столько, сколько есть атрибутов. `\s*\w+=\w+\s*` - это всегда ровно один атрибут.
А долгий бэктрекинг - оттого что есть пробелы, каждый пробел между двумя атрибутами можно прицепить как к атрибуту перед ним, так и после. Если у нас N атрибутов и между ними по одному пробелу, то это 2 в степени (N-1) разных вариантов, и движок перепробует их все.
Как только мы делаем `(\s*\w+=\w+)*`, сразу пропадает возможность перекидывать пробелы и регекс становится безопасным.

**Comment by iliakan** [comment]
Как бы вы улучшили объяснение?

**Comment by iliakan** [comment]
Может быть, еще упростить пример, как-то типа `(\s*\w+\s*)*`

**Comment by alexandroppolus** [comment]
Нет, упрощать не надо, совсем упрощенный пример уже есть.

Да, бэктрекинг будет в любом случае, но для `(\s*\w+=\w+)*` он будет таким как изначально задумывался - для строки '<a=b a=b a=b' проверяются варианты с откатом назад:
<(a=b)( a=b)( a=b)_
<(a=b)( a=b)_
<(a=b)_
<_
и всё

А регулярка `(\s*\w+=\w+\s*)*` начинает безумие с пробелами:
<(a=b )(a=b )(a=b)_
<(a=b )(a=b )_
<(a=b )(a=b)( a=b)_
<(a=b )(a=b)_
<(a=b )_
<(a=b)( a=b )(a=b)_
<(a=b)( a=b )_
<(a=b)( a=b)( a=b)_
<(a=b)( a=b)_
....
и алгоритм из линейного превращается в NP-полный.

Предложенный в статье способ в предпросмотром подходит, когда бэктрекинг совсем не нужен. А вот если он по каким-то причинам всё-таки требуется (например, для нежадного квантификатора), то надо просто сделать четкие границы значения для паттерна в скобках, и всё отработает как задумано. Кстати, для данного примера надо ещё \b дописать: `<(\s*\w+=\w+\b)*\s*>`, иначе зависает на длинной строке типа '<a=aaa=aaaa=aaaa=aaaaa=aaaa=aaa...'

**Comment by iliakan** [comment]
@alexandroppolus улучшаю сейчас этот раздел учебника - может быть, есть получше пример?

**Comment by iliakan** [comment]
Что-то, что похоже на реальный пример и попроще с виду.

**Comment by alexandroppolus** [comment]
Пример попроще вряд ли приведу, куда уж тут проще.

Любопытный пример - задачка с кодоварсов. Есть строка только из нулей и единиц, и надо регуляркой проверить, что в строке содержится двоичное представление числа, делящегося на 3. Т.е. `regex.test(str)` должен быть true, только если `parseInt(str, 2)` делится на 3. Там дается [ссылка](https://math.stackexchange.com/questions/140283/why-does-this-fsm-accept-binary-numbers-divisible-by-three) на конечный автомат, который делает эту проверку, и по сути надо этот автомат запихнуть в регулярку.
На строке "000...001" некоторые решения зависают.
Пример плохой регулярки: `/^(0*(1(01*0)*1)*)*$/` - тут всё те же размытые границы паттернов в скобках.
Хорошая регулярка: `/^(0*(1(01*0)*1))*0*$/` - границы четкие.
Забавно, что плохие регулярки получили больше всего лайков)) Народ не читает учебник.

**Comment by iliakan** [comment]
Я уже переписываю этот раздел, чтобы он был понятнее. Эта статья уже переписана, стало лучше.

**Comment by iliakan** [comment]
Выложу - напишу =)

**Comment by iliakan** [comment]
Глава был переписана.
