### ISSUE TITLE
Добавление задач

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ru.javascript.info#321]
Во многих главах учебника задач мало или они отсутствует.

Нужно добавить их, с тестами, по образцу существующих.

**Comment by alexandroppolus** [comment]
Можно на форуме тему создать, указать к каким темам нужны задачи. Завсегдатаи наверняка что-нибудь вспомнят и предложат.

**Comment by dobernike** [comment]
#448 добавил 2 задания

**Comment by MariaLovesGithub** [comment]
а можно дополнить эту статью? https://learn.javascript.ru/polyfills тут же ни одного примерчика, как использовать Babel, в отличии от предыдущей статьи Автоматическое тестирование c использованием фреймворка Mocha
