### ISSUE TITLE
Возможная ошибка в примере про долгий AJAX запрос

### ISSUE THREAD

**Issue by hig2** [javascript-tutorial/ru.javascript.info#325]
Здравствуйте! в примере про  долгий запрос есть строка if(this.readyState != 4 ){return}; означает что ждем состояние под номером 4 если взглянуть в спецификацию там можно увидеть что при этом состоянии ответ(сообщение + код сервера) полностью получен а код от сервера 200 300 404 уже был присвоен на втором  из чего следует что обработчик события onMessage бесполезен т.к ответ к этому участку кода всегда получен .
Я думаю надо исправить на if(this.readyState < 2 ){return};

https://learn.javascript.ru/xhr-longpoll

**Comment by hig2** [comment]
А вообще: 
2 статус 
> **Вызван метод send()**, получены заголовки и код ответа (200, 404, 501 и проч)

Значит при обращении к .onreadystatechange смотрит уже за изменением  от статуса 2 и выше тогда там не может быть статуса 0 и 1 выходит проверка if(this.readyState != 4 )return; вообще не нужна при использовании onMessage .
Отпишите очень интересно так ли это, а то я может туплю просто.

**Comment by hig2** [comment]
а скажем при таком коде
`function ajaxGetLong(){
  var xhr = new XMLHttpRequest();                 
  xhr.open('GET','/data');                    
  xhr.onreadystatechange = function(){
     if(this.status === 200){                     
      onMessage(this.responseText);
     }else{
      console.log('Код сервера: '+ this.status);
     }
  }
  xhr.send();
}
`
Нам проверка вообще не будет нужна т.к обработчик будет смотреть изменение со статуса 1  и после метода send()  сразу сработает  вызвав проверку на код сервера  ну и будет ждать сообщения с помощью onMessage

**Comment by iliakan** [comment]
Это архивный материал, посмотрите на современный, пожалуйста.
