### ISSUE TITLE
Ошибка в задаче «Функция в if»

### ISSUE THREAD

**Issue by panteslav** [javascript-tutorial/ru.javascript.info#333]
В задаче «Функция if» в главе [«Замыкания»](https://learn.javascript.ru/closure) предложенное решение не соответствует действительному поведению кода: в решении написано, что будет ошибка, а, по факту, функция вызывается.
Возможно, здесь имелось в виду, что ошибка произойдет не при вызове функции <code>sayHi()</code>, а при вызове переменной <code>user</code> после блока с <code>if</code>. В этом случае поведение именно такое, как описано в предложенном решении: ошибка.

**Comment by iliakan** [comment]
Вы забыли use strict.

**Comment by panteslav** [comment]
Перепроверил: ошибка НЕ появляется при использовании Opera. 
![image](https://user-images.githubusercontent.com/53494097/62446872-91ae9700-b76c-11e9-935a-9c8ad38d22b3.png)
Примечательно, что если открыть отдельное окно с [заданием](https://learn.javascript.ru/task/function-in-if), то код выдает ошибку, как и положено.

**Comment by ZhenyaGro** [comment]
> Вы забыли use strict.

В браузере Google Chrome с использованием 'use strict' код отрабатывает без ошибки.
![image](https://user-images.githubusercontent.com/95648111/157895084-ffaa4743-b462-4998-93d1-7207fa9203f4.png)

**Comment by iliakan** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/349336/157895540-65185183-30cb-428f-b4ee-3ec2605e3cf3.png">

**Comment by iliakan** [comment]
```
"use strict";

let phrase = "Hello";

if (true) {
  let user = "John";

  function sayHi() {
    alert(`${phrase}, ${user}`);
  }
}

sayHi();
```

**Comment by ZhenyaGro** [comment]
> <img alt="image" width="445" src="https://user-images.githubusercontent.com/349336/157895540-65185183-30cb-428f-b4ee-3ec2605e3cf3.png">

Разобрался, спасибо.
После выполнения кода без 'use strict'; нужно обновить страницу в браузере. После чего, используя строгий режим, будет ошибка.
