### ISSUE TITLE
Уточнения по главе о событийном цикле

### ISSUE THREAD

**Issue by xcurveballx** [javascript-tutorial/ru.javascript.info#338]
Я прочитал главу про [событийный цикл](https://github.com/javascript-tutorial/ru.javascript.info/tree/master/2-ui/99-ui-misc/03-event-loop) и есть пара уточнений, хотя может я и не прав.

Ближе к концу идёт фраза

> После каждой макрозадачи движок исполняет все задачи из очереди микрозадач перед тем, как выполнить следующую макрозадачу.

Я считаю, что стоит добавить 2 уточнения для лучшего понимания:

1) Микрозадачи исполняются на текущей итерации событийного цикла, т.е. на той же итерации, что и завершенная макрозадача, что объясняет, почему в микрозадачи не может влезть что-то другое.
2) И более важный момент - микрозадачи выполняются вслед за макро, только если стек пуст в данный момент. Об этом пишет [Джек Арчибальд](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/) со ссылкой на спеки.

И еще одно замечание по поводу картинки в конце главы - на ней показано, что рендеринг возможен между макротаской и микротасками, а затем следом в описании уже рендеринг идёт после микрозадач. Тут тоже надо уточнить, что если стек пуст и в ход идут микрозадачи, то рендеринг возможен только после них, так как микротаски выполняются на том же шаге, что и текущая макротаска, а если стек не пуст, то микрозадачи в ход не идут и рендеринг возможен между макрозадачами.

Как-то так, надеюсь понятно описал. Если я где-то ошибся - буду благодарен за разъяснение.

**Comment by iliakan** [comment]
1. Да, вроде бы так и нарисовано, и рассказано. Какие-то фразы конкретные стоит улучшить?
2. Не может быть такого, что после макрозадачи стек не пуст. Вообще, управление не может при непустом стеке на какие-то другие макро- микро- и другие задачи уйти. Мне казалось, это очевидно?
3. По поводу картинки - рендеринг возможен только после микротасков. Где-то там ошибка?

Спасибо

**Comment by xcurveballx** [comment]
1. Я бы дописал так: "После каждой макрозадачи **на той же итерации событийного цикла** движок исполняет все задачи из очереди микрозадач перед тем, как выполнить следующую макрозадачу." Это не очевидно мне кажется. Можне подумать, что микрозадачи делаются отдельно на новой итерации событийного цикла.

2. Возможно, я что-то путаю, но например в стеке есть основной скрипт, который вызывает функцию А, которая вызывает функцию Б. Все синхронно, то есть в стеке 3 фрейма с локальными данными этих функций. Верно? Это всё 1 макрозадача или 3 макрозадачи? Если одна, то вопрос снимается, а если 3, то например функция Б использует `fetch` и обработчик из `then`прилетает в очередь микрозадач. По ссылкам в первом сообщении там пишут, что в таком случае после выполнения функции Б, так как стек не пуст (в нем есть А и основной скрипт), обработчик из `then` не выполнится, он выполнится, только когда стек опустеет, т.е. после завершения функции А и основного скрипта. Надеюсь, я понятно изложил свою мысль. 

3. Меня наверное стрелочка смутила. Что показывает её направление? Не должна ли стрелочка быть в другую сторону?

**Comment by iliakan** [comment]
Немного переписал эту секцию, чтобы стало проще.

2. Это всё одна макрозадача.

3. Где стрелка не та? Может быть и ошибка в картинке.

**Comment by xcurveballx** [comment]
1. ок
2. ок.
3. картинка в конце статьи вот эта https://github.com/javascript-tutorial/ru.javascript.info/raw/master/2-ui/99-ui-misc/03-event-loop/eventLoop-full.svg?sanitize=true

**Comment by iliakan** [comment]
Имел в виду что микрозадачи все выполняются

**Comment by iliakan** [comment]
Можно поменять иконку

**Comment by xcurveballx** [comment]
Просто стрелочка лично меня путает - как будто задачи берутся в порядке setTimeout->Mousemove->скрипт. На первой картинке более понятно изображено - https://github.com/javascript-tutorial/ru.javascript.info/raw/master/2-ui/99-ui-misc/03-event-loop/eventLoop.svg?sanitize=true

Кстати, в статье еще пара мест я заметил с ошибками пунктуации. Это достойно отдельного PR?

**Comment by iliakan** [comment]
Ошибки, конечно, хорошо бы исправить.

**Comment by xcurveballx** [comment]
@iliakan  #347
