### ISSUE TITLE
Опечатка в тексте

### ISSUE THREAD

**Issue by dobernike** [javascript-tutorial/ru.javascript.info#341]
https://learn.javascript.ru/object 
![изображение](https://user-images.githubusercontent.com/26094706/62428789-6ac17800-b70e-11e9-9ef0-cdf499714f3a.png)

**Comment by iliakan** [comment]
Спасибо, исправлено!

**Comment by junkiemonkey** [comment]
https://learn.javascript.ru/modules-intro
Директива import загружает модуль по пути ./sayHi.js относительно текущего файла и записывает --> **эксортированную** _(экспортированную?)_ функцию sayHi в соответствующую переменную.
