### ISSUE TITLE
Неверное решение задачи "Максимальная зарплата"

### ISSUE THREAD

**Issue by lomeat** [javascript-tutorial/ru.javascript.info#362]
Задача из темы: https://learn.javascript.ru/task/max-salary
В решении не учтены условия на null и на несколько имен.
В комментариях я, под ником lemma, предположил свой вариант решения. Там же еще кто-то немного по-другому решил.

Надо бы залить царское решение того, как надо.

**Comment by iliakan** [comment]
Там даже тест есть на `null`.
Почему не учтено?

Можно подробнее?

**Comment by lomeat** [comment]
На счет null меня в комментариях уже поправляли, я так понимаю, что скопировав ваш код я получил undefined, тк использовал node вместо браузера для запуска. 

Суть в том, что в условии указано, что если несколько пользователей имеют одинаковое колво зп, то и выводить надо несколько таких человек, а не единственного наибольшего.
Я это вывел в виде массива, кто-то выводит в виде конкатенации строки.
