### ISSUE TITLE
Массивы - Подмассив наибольшей суммы

### ISSUE THREAD

**Issue by shotalime** [javascript-tutorial/ru.javascript.info#366]
Последний тест и решение написаны неправильно, результат по массиву [2, -8, 5, -1, 2, -3, 2]  должен быть 5, а в тесте 6.
Функция проходит проверку, из-за того что тест не верен.

https://learn.javascript.ru/task/maximal-subarray

**Comment by iliakan** [comment]
Решение верное, кому-то надо лучше считать =).

5 - 1 + 2 = 6
