### ISSUE TITLE
Логические операторы ошибка в адаптиве

### ISSUE THREAD

**Issue by Mishkalesha** [javascript-tutorial/ru.javascript.info#399]
ТЕМА: ЛОГИЧЕСКИЕ ОПЕРАТОРЫ
При адаптации для мобильных устройств , картинка в задании "ПРОВЕРКА ЛОГИНА" вылазит за рамки и добавляет горизонтальный скрол, нужно изменить на width: 100%, height: auto. Тогда все читабельно и нет горизонтального скрола. Учебник бомба!

**Comment by iliakan** [comment]
PR плиз?

**Comment by Mishkalesha** [comment]
Pr это что?)

вс, 11 авг. 2019 г., 15:27 Ilya Kantor <notifications@github.com>:

**Comment by lomeat** [comment]
Pull Request создай с твоими изменениями в репозитории на мерж с веткой master.

**Comment by oshliaer** [comment]
Что-то я не смог повторить фокус. Проверял только на хроме мобильном и не очень, но смещение есть только при переключении режимов с обычного на мобильный. Но повторная загрузка все возвращает на место.

**Comment by iliakan** [comment]
Непонятно
