### ISSUE TITLE
Некорректное отображение изображений в формате SVG

### ISSUE THREAD

**Issue by shamilDzhakeev** [javascript-tutorial/ru.javascript.info#428]
На странице https://learn.javascript.ru/regexp-character-classes некорректно отображается SVG. 
Отображение SVG меняется в зависимости от браузера. Причина, насколько я понял в следующем см. https://toster.ru/q/378496.

Как решение предлагаю конвертировать текст SVG в кривые. Подробности по ссылке выше.

![diff_svg](https://user-images.githubusercontent.com/46997727/62775304-ebd29380-baaf-11e9-96dc-2d9828c63d21.png)

Лучший вариант ИМХО наблюдается в IE.

**Comment by iliakan** [comment]
А сейчас?

**Comment by shamilDzhakeev** [comment]
Посмотрел в FF и Chrome - ничего не изменилось. Аналогично FF на андроид.

**Comment by lomeat** [comment]
![image](https://user-images.githubusercontent.com/33469504/62838545-66eda280-bc86-11e9-9572-e33f166c654b.png)
хз, правильное ли это отображение, но выглядит как будто так и надо

**Comment by shamilDzhakeev** [comment]
@lomeat Да, это правильное отображение, но почему у меня не так - не понятно.

К примеру EDGE:

![изображение](https://user-images.githubusercontent.com/46997727/62838931-76231f00-bc8b-11e9-9ca1-d2ee161ab362.png)

**Comment by iliakan** [comment]
Проверил и в Edge и в IE11 - все ок.

У кого-то ещё есть подобная проблема?

P.S. Я добавил загрузку внешнего шрифта @font-face в SVG и подключаю через `<object>` вместо `<img>`, чтобы он подхватывался.

**Comment by shamilDzhakeev** [comment]
У меня какой-то плавающий баг, на домашнем ПК все плохо, на рабочем Chrome и IE отобразили все нормально. На рабочем тестовом опять все плохо. Кэш очищал, сбрасывал все настройки браузера, отключался от своего аккаунта.

После установил чистую Win10 на VMware и посмотрел как там. Вот результат:

![clearOS](https://user-images.githubusercontent.com/46997727/62882048-bccf5280-bd39-11e9-950a-ead1b741428c.png)

Нужно посмотреть есть ли у кого еще такие проблемы, возможно я что-то делаю не так.

**Comment by iliakan** [comment]
@shamilDzhakeev а сейчас?

И еще - в коде страницы у вас на этом месте тег `<object>` или `<img>`?

**Comment by shamilDzhakeev** [comment]
В коде - `<object>`. Все еще есть проблемы, у коллеги на FF и Chrome неправильно отобразилось.

![изображение](https://user-images.githubusercontent.com/46997727/62941479-c78ff300-bdde-11e9-8abc-55d339c13a7e.png)

**Comment by iliakan** [comment]
Скажите, а шрифты из SVG подгрузились успешно? В Network woff2/woff какие шрифты подгрузились успешно какие нет?

**Comment by iliakan** [comment]
У коллеги ошибка, а у вас все стало ок?

**Comment by shamilDzhakeev** [comment]
@iliakan перепроверил. Вроде везде ок, за исключением Firefox.

Количество подгружаемых шрифтов отличается для Firefox.

![изображение](https://user-images.githubusercontent.com/46997727/63000822-bb597380-be7a-11e9-97a5-9b57012828cd.png)

**Comment by iliakan** [comment]
С этой конкретно картинкой понятно:
![image](https://user-images.githubusercontent.com/349336/63006842-252c4a00-be88-11e9-8b09-b26b778c8f27.png)
Есть проблемы с другими?

**Comment by shamilDzhakeev** [comment]
Да, перепроверил IE11, Chrome, Edge, Opera - везде четко, модно, молодежно!

**Comment by iliakan** [comment]
Поправил картинки с этой проблемой, перезалил.

Спасибо!

Если будут проблемы - переоткрой плиз.
