### ISSUE TITLE
errors (ошибки)

### ISSUE THREAD

**Issue by Dimedrolity** [javascript-tutorial/ru.javascript.info#456]
In articel array-methods (в статья методы массивов):
1. literal error (опечатка). равнй 1.
Right variant (правильный вариант): равный 1.
2. logic error in output of code describe split method
(логическая ошибка в коде, описывающем метод split :
```
for (let name of arr) {
  alert( `Сообщение получат: ${name}.` ); // Сообщение получат: Вася (и другие имена)
}
```
This code outputs text "Сообщение получат" on every cycle iteration, I think it is gonna be one time before cycle _for_ because the phrase is plural (этот код выводит текст "Сообщение получат" на каждой итерации цикла, я думаю, что это должно быть однократным перед циклом _for_, потому что эта фраза в множественном числе).

**Comment by iliakan** [comment]
Не могли бы в Github отредактировать и прислать PR?

**Comment by Dimedrolity** [comment]
> Не могли бы в Github отредактировать и прислать PR?
Где именно отредактировать? и что значит PR? первый раз таким занимаюсь

**Comment by iliakan** [comment]
Слева-снизу от статьи, в сайдбаре, есть ссылка "Редактировать на GitHub".

PR - означает "pull request", вы можете сделать изменения в статье и предложить их для принятия.

Это широко используемые инструменты разработки.

**Comment by Dimedrolity** [comment]
> Слева-снизу от статьи, в сайдбаре, есть ссылка "Редактировать на GitHub".
> 
> PR - означает "pull request", вы можете сделать изменения в статье и предложить их для принятия.
> 
> Это широко используемые инструменты разработки.

Сделал PR, вот ссылка https://github.com/javascript-tutorial/ru.javascript.info/pull/484

**Comment by iliakan** [comment]
Вы подписанием даете право учебнику использовать ваш текст.

**Comment by ZdraviiSmisl** [comment]
https://learn.javascript.ru/event-loop ссылка на статью.. Переход по ссылки WebWorkers выдаёт ошибку

**Comment by iliakan** [comment]
пишите письма в РосКомНадзор
