### ISSUE TITLE
Header bug

### ISSUE THREAD

**Issue by Problemon** [javascript-tutorial/ru.javascript.info#458]
В шапке открытого урока при ширине от 841px до 900px, появляется вторая шапка для мобилок которая перекрывает текст.

P.S Use Yandex Browser.

U.P.D: Учусь веб программированию. Если не совсем точно описал проблему, напишите как будет верно.

**Comment by iliakan** [comment]
Можно скриншот?

**Comment by pashamonster1** [comment]
Вот скрин: http://prntscr.com/os2v33

**Comment by iliakan** [comment]
OS Windows?

**Comment by pashamonster1** [comment]
Да

**Comment by iliakan** [comment]
А ошибка еще есть? Вроде поправлено?
