### ISSUE TITLE
1-js/02-first-steps/04-variables

### ISSUE THREAD

**Issue by MrShtein** [javascript-tutorial/ru.javascript.info#46]
Translate

**Comment by lex111** [comment]
@MrShtein странно, вы взяли на перевод статью про переменные, но отправили пулреквест другой статьи - про строгий режим https://github.com/javascript-tutorial/ru.javascript.info/pull/44
Спасибо, но теперь непонятно, произошла путаница, либо вы Переменные также переведете?

**Comment by MrShtein** [comment]
@lex111 Я закончил со стаьей про "use strict", и взял, следующую, "variables", или пока  issue не закрыта, не стоит начинать переводить новую статью  ? Я не так давно на github и не совсем уверен, что все делаю правильно.

**Comment by MrShtein** [comment]
статья про переменные переведена на 90%

**Comment by lex111** [comment]
В любом случае нужно сообщить об этом, т.е. не было ишью про перевод про строгий режим. А так мы придерживаемся того, чтобы один человек брал на перевод одну статью, когда ее перевели, если хотите еще помочь, то берете следующую и т.д.
В общем, отметил эти две статьи, что вы их переводите вот здесь - https://github.com/javascript-tutorial/ru.javascript.info/issues/60

**Comment by MrShtein** [comment]
@lex111 Я разобрался, просто, когда я перевод закончил, я issue - #43 закрыл, а так ясно, поэтому Вы ее не видели.
