### ISSUE TITLE
Старая версия русского сайта

### ISSUE THREAD

**Issue by andrew-uskov** [javascript-tutorial/ru.javascript.info#464]
Здравствуйте.

Подскажите пожалуйста, а где теперь можно найти старую версию русского сайта, которая изначально писалась на русском языке, а не переводилась с английского?

Я полазил по этому репозитарию и не нашел никаких её следов здесь, или плохо смотрел?

Спасибо.

**Comment by MistakeOfNature** [comment]
[https://github.com/iliakan/javascript-tutorial-ru]

**Comment by iliakan** [comment]
Зачем?

**Comment by zsapozhnikov** [comment]
Я моуг ответить: про функциональное наследование я сейчас не нашёл ни слова. Предыдушая версия была написана в основном для es5, тогда как ныняшняя написана для es6. Понятно, что всё идёт к переходу, но всё же важно знать, как и что устроено под капотом такого синтаксического сахара, как class и extends. Поддерживать её, думаю, не стоит, но оставить в удобочитаемом виде (для меня лично этой сайт, а не маркдаун) стоило бы

**Comment by MistakeOfNature** [comment]
Я уже настрочил текст, но раз уж за меня ответили, я не буду позориться своим мнением =).

**Comment by iliakan** [comment]
@zsapozhnikov Функциональное наследование почти не используется, поэтому оно убрано. Его нет "под капотом" class/extends, там прототипы.

Текст улучшим, вычитка приветствуется, чтобы сделать его более "русским" =)

**Comment by zsapozhnikov** [comment]
> Его нет "под капотом" class/extends, там прототипы

да, я имел в виду что сайт больше написан для изучения es6, тогда как es5 знать тоже важно. Это очень частый вопрос на собеседованиях (а многие к ним готовятся или изучают js с нуля именно по вашему сайту, я сам его рекомендую), да и в легаси проектах присутствует. Откуда информация, что почти не используется? Как я вижу, это всё есть в новом репозитории, да и прямые ссылки работают. Было бы классно, если бы вы вывели это хотя бы в какой-то архив, чтобы было так же удобно смотреть на сайте)

**Comment by iliakan** [comment]
функциональное наследование не рекомендуется к использованию
