### ISSUE TITLE
Обсуждение стандартов/практик/рекомендаций/стилей оформления текста

### ISSUE THREAD

**Issue by contributorpw** [javascript-tutorial/ru.javascript.info#48]
# TOC

## В репозитории

- [Рекомендации и соглашения по переводу!](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/TRANSLATION.md)
- [Порядок внесения изменений](https://github.com/javascript-tutorial/ru.javascript.info/issues/211#issuecomment-497282839)

## В этом топике

- [Inline код](#issuecomment-482947630)
- [Отступы между строк](#issuecomment-483502557)
- [Обратный апостроф](#issuecomment-486442597)
- [mdn ссылки](#issuecomment-486742104)
- [Сверка с другими источниками](#issuecomment-495640841)

# Описание проблемы

Некоторые элементы текста удручают своим разнообразием. Предлагаю хотя бы собрать попавшиеся варианты.

Например, разметка сниппета 

    ````warn header="`matchAll` возвращает итератор, а не массив"
    ````

Ломает штатный syntax highlighting моих редакторов напрочь.

Ну, и т.д.

**Comment by oshliaer** [comment]
# Inline код

Как правильно?

    флаг `'g'`
    флаг `"g"`
    флаг `g`

**Comment by oshliaer** [comment]
# Отступы между строк

Некоторый страницы содержат больше нужного отступов между строками. Особенно это касается сниппетов

    some text
    
    
    
    
    ````
    a snippet
    ````
    
    
    some text

Некоторый сниппеты выжержаны на расстоянии трех или четырех строк от основного повествования.

**Comment by aruseni** [comment]
Как мы будем называть по-русски вот этот символ: `? В английском он называется backticks. Предлагаю вариант [обратный апостроф](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%88%D0%B8%D0%BD%D0%BE%D0%BF%D0%B8%D1%81%D0%BD%D1%8B%D0%B9_%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D1%8B%D0%B9_%D0%B0%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%BE%D1%84).

**Comment by lex111** [comment]
@aruseni да, верно.

**Comment by oshliaer** [comment]
В #60 сказано, что будет "glossary and style guide"

**Comment by aruseni** [comment]
[docs](mdn:/JavaScript/Reference/Template_literals#Tagged_template_literals)

Вот такие ссылки надо менять? Они автоматически преобразуются при рендеринге учебника?

**Comment by aruseni** [comment]
```
[docs](mdn:/JavaScript/Reference/Template_literals#Tagged_template_literals)
```

Вот такие ссылки надо менять? Они автоматически преобразуются при рендеринге учебника?

**Comment by oshliaer** [comment]
@aruseni, насколько я понимаю механизм, менять такие ссылки не нужно.

Ссылки будут заменены в зависимости от контекста https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals или https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals

**Comment by oshliaer** [comment]
@aruseni, в рекомендациях по переводу указанно, что менять только если ссылка внешняя https://github.com/javascript-tutorial/ru.javascript.info/blob/master/TRANSLATION.md

**Comment by xcurveballx** [comment]
такой еще вопросик возник - что делать со словами типа tag, stack и т.д.? Можно писать тЕг, а можно тЭг, аналогично стек/стэк. По моим наблюдениям, более популярен вариант через Е, но это нигде особо не отражено.

**Comment by oshliaer** [comment]
> После согласных пишется е, кроме слов пэр, мэр, сэр, а также некоторых собственных имён, например: Улан-Удэ, Бэкон, Тэн.

**СТОП ФАНТАЗИЯ!**

**Comment by GordonDrop** [comment]
Подскажите как переводить такие термины, как `dispach`, `custom`. Конекст `Dispatching custom events`.

Приходят в голову варианты:
- генерация собственных событий
- рассылка
- создание...

**Comment by aruseni** [comment]
Dispatch — отправка.

Custom — это интереснее, обычно я употребляю слово «кастомный».

Если есть какая-то причина не использовать кальку, то надо или искать похожее слово, или придумать новое. Из похожих есть, например, «пользовательский». Новое — тут может быть всё, что угодно, например, «своеный».

**Comment by oshliaer** [comment]
@GordonDrop, можно свериться (с предыдущим переводом](https://learn.javascript.ru/), если он есть для этого раздела.

Как я понимаю https://learn.javascript.ru/dispatch-events.

Попробуйте подыскать общеупотребительный термин на MDN или академическое значение, если оно где-то упомянуто (например, на Мультитране или Реверсо).

**Comment by iliakan** [comment]
Согласен, постарайтесь найти аналогичный текст.

По поводу dispatch - в контексте событий я бы перевел как "генерация".
Слово custom - "свой".

Генерация "своих" событий.

**Comment by dandgerson** [comment]
@oshliaer 
> Правило русского языка:
> 
> > После согласных пишется е, кроме слов пэр, мэр, сэр, а также некоторых собственных имён, например: Улан-Удэ, Бэкон, Тэн.
> 
> **СТОП ФАНТАЗИЯ!**

Но "стэк/стек" это не русский язык, это кириллическая транскрипция английского, тут не работают эти правила =). И зачем же отказываться от фантазии?

**Comment by dandgerson** [comment]
И потом, что это ещё за правила? можно и нужно их обдумывать. 
Когда-то в нашем родном языке было гораздо больше символов-букв-образов. И одним формальным махом кто-то урезал десяток символов-букв-образов. А если посчитать и вдуматься... ?

Сколько букв, почти столько и их комбинаций - слов. в азбуке из пяти букв будет 120 слов. Простой факториал, а в азбуке из 33 букв. А в азбуке из 44 ?

А если из азбуки с 44-мя символами убрать один на сколько слов обеднеет письменная речь ? Давайте посчитаем:
`factorial(44) -> 2658271574788448768043625811014615890319638528000000000`
`factorial(43) -> 60415263063373835637355132068513997507264512000000000`
грубая разница -- два порядка. А теперь от 33
`factorial(33) -> 8683317618811886495518194401280000000`
Вот как обеднела наша письменная речь с начала века. Не считая, остальных "правил".

**Comment by oshliaer** [comment]
Это правило Русского языка. Я не вижу смысла, способностей и времени его менять. Транскрипция же на письме выделяется по-другому, с указанием значащих и активных звуков.
Наша способность, как людей в группе, написать и произнести одинаково одно и то же слово делает нас образованными. Не мы делаем образование, а оно нас.

**Comment by dandgerson** [comment]
@oshliaer 
Пожалуйста, не воспринимайте это, как вызов или приглашение к спору. В спорах не рождается истина. Я лишь хотел обратить на это Ваше внимание. Благодарю за ответ.

К слову, написание `стэк`, гораздо точнее передаёт образ, т.к. `стек`, можно спутать с глаголом `стёк`. Есть русский вариант `стопка` =) И заметьте, в правиле, на которое Вы ссылаетесь, через "э", в качестве исключения, пишутся только иностранные слова. `стэк` - иностранное слово.
Так, что предлагаю добавить это слово в список исключений и везде писать через "Э".

**Comment by oshliaer** [comment]
Это првило для написания иностранных слов. Слова исключения: мэр, пэр, сэр; если не ошибаюсь.
В любом слыче, я не видел книг, где бы было написано с `э`, хоть это и во всём очень прекрасная и интересная буква.
