### ISSUE TITLE
Проблемы

### ISSUE THREAD

**Issue by dobernike** [javascript-tutorial/ru.javascript.info#500]
![изображение](https://user-images.githubusercontent.com/26094706/63177275-3fb11f80-c050-11e9-9cbb-b69ceab42360.png)

**Comment by dobernike** [comment]
https://learn.javascript.ru/ На русской версии упали стили и скрипты. 404
на https://javascript.info/ все работает

**Comment by dobernike** [comment]
Все, заработало.

**Comment by dobernike** [comment]
https://learn.javascript.ru/focus-blur#tasks 
Не загружаются задания в демо.

![изображение](https://user-images.githubusercontent.com/26094706/63177898-8fdcb180-c051-11e9-825c-a133db18c6a5.png)

![изображение](https://user-images.githubusercontent.com/26094706/63177861-763b6a00-c051-11e9-8d35-05720f5dc9e7.png)

**Comment by iliakan** [comment]
должно быть ок
