### ISSUE TITLE
ошибка в главе о сеттерах и сеттерах (поддерживается / не поддерживается delete)

### ISSUE THREAD

**Issue by Anton-Stenin** [javascript-tutorial/ru.javascript.info#502]
Вот тут:

https://learn.javascript.ru/property-accessors

 написано следующее:

"Нет поддержки для delete
При попытке удалить свойство-аксессор оператором delete будет ошибка."

Я взял Объект

let user = {
    name: "John",
    surname: "Smith",
  
    get fullName() {
        return `${this.name} ${this.surname}`
    },

    set fullName(value) {
        [this.name, this.surname] = value.split(' ');
    },
};

И присвоил свойству fulName новое значение, вот так:

user.fullName = 'Ivan Stenin';

После чего посмотрел структуру объекта через
alert (JSON.stringify(Object.getOwnPropertyDescriptors(user), null, 2) );

В объекте появилось свойство fullName с двумя флагами - enumerable : true, configurable: true.

![Screenshot 2019-08-17 at 17 47 53](https://user-images.githubusercontent.com/54212748/63213623-36d75100-c117-11e9-9708-4fb88996f3d2.png)

Я удалил свойство fullName, вот так:

delete user.fullName;

и снова запросил структуру объекта через 
alert (JSON.stringify(Object.getOwnPropertyDescriptors(user), null, 2) );

Свойство fullName из структуры исчезло. При попытке чтения этого свойства выдается undefined. 

Ошибок отладчик не выдал.

**Comment by iliakan** [comment]
use strict не забыли?
