### ISSUE TITLE
Иерархия учебника

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ru.javascript.info#537]
Есть предложение использовать слово "урок" вместо "статьи", что думаете?

То есть, иерархия будет такая:

- Часть 1. Язык программирования JavaScript
    - Глава 1.1. Введение
        - Урок 1.1.1. Введение в JavaScript

@xcurveballx @lex111 @stas-dolgachov

**Comment by iliakan** [comment]
Изначально вопрос был поставлен про английскую версию нейтив спикером: https://github.com/javascript-tutorial/en.javascript.info/issues/1247

**Comment by xcurveballx** [comment]
Я бы оставил статью. 

1) Потому что урок подразумевает что-то цельное, какой-то законченный юнит информации, которым можно пользоваться. Типа урок как сделать слайдер. В нашем случае значительная часть материала - это не уроки, а именно статьи с информацией, и часто вся информация по теме не вмещается в одну статью и разбивается на несколько связанных материалов. 

2) К тому же, урок подразумевает интерактивность какую-то, а далеко не ко всем статьям есть задачи. 

3) И если это всё в формате книги, то слово урок тут не очень тоже подходит.

Теоретически, если немного переработать всю иерархию материалов, добавить какие-то видео и задачи везде, то можно позиционировать как видеокурс с уроками, но сейчас это как книга и ей лучше оставаться книгой, так как видеокурсов уже много и в них обычно идёт акцент на парктическое применение, а хороших книг, где последовательно объясняются какие-то теоретические моменты начиная от простых и заканчивая сложными не так много.

**Comment by stas-dolgachov** [comment]
Для текущей структуры учебника мне больше нравится именование "статья".

Лично я обращаюсь к учебнику, как к универсальному справочнику, когда что-то подзабыл или хочу уточнить. Мои коллеги используют его похожим образом. По сути для меня это такой MDN на стероидах, место, в котором я могу найти исчерпывающую информацию с большим количеством подробностей и деталей.

По моему мнению, "урок" более уместен в контексте обучающего курса, поэтому, я бы оставлял как есть.

**Comment by iliakan** [comment]
По остальному какие-то комментарии есть? Секция (под заголовком внутри статьи) -  это ок?

- Часть 1 "The JavaScript Language"
- Глава 1.1 "An Introduction"
- Статья 1.1.1 "An Introduction to JavaScript"
- Секция 1.1.1.a "What is JavaScript?"

**Comment by iliakan** [comment]
А текущая структура не лучше? Вот она:

Часть 1 "The JavaScript Language"
Раздел 1.1 "An Introduction"
Глава 1.1.1 "An Introduction to JavaScript"
Секция 1.1.1.a "What is JavaScript?"

@lex111 @xcurveballx @stas-dolgachov
