### ISSUE TITLE
Одно лишнее "Явно"

### ISSUE THREAD

**Issue by Vromga** [javascript-tutorial/ru.javascript.info#570]
Задача Класс расширяет объект?

В строке: Но что если мы **явно** напишем **явно** "class Rabbit extends Object"

**Comment by lex111** [comment]
@Vromga спасибо, что сообщили, исправлено в коммите https://github.com/javascript-tutorial/ru.javascript.info/commit/df855b83bfa3e22419f6989d9ff4b47616bce68c.
