### ISSUE TITLE
Забыто слово в тексте. Объекты: основы > Сборка мусора

### ISSUE THREAD

**Issue by R-Mosolov** [javascript-tutorial/ru.javascript.info#572]
Последнее предложение, перед началом блока "Итого".

"Если, конечно, это не вопрос чистого интереса, тогда для вас будут (вероятно, здесь Вы хотели написать "полезно". – прим. авт.) некоторые ссылки ниже".

![Screen Shot 2019-08-30 at 3 57 44 PM](https://user-images.githubusercontent.com/41830045/64022490-093ece80-cb3f-11e9-9380-ed2b49a6377f.png)

**Comment by iliakan** [comment]
Добавлю, но вообще без этого слова тоже понятно =)
