### ISSUE TITLE
Неочевидный пример в главе "Методы массивов\thisArg"

### ISSUE THREAD

**Issue by DrToldme** [javascript-tutorial/ru.javascript.info#609]
В данном разделе: http://learn.javascript.ru/array-methods, в самом последнем примере было бы очевиднее происходящее, если бы объект, который фактически отсеивает значения массива, назывался более подходящим к контексту образом и более очевидно.

Изображение примера:
![изображение](https://user-images.githubusercontent.com/16436298/64193021-9c9c3a80-ce84-11e9-95cd-2b6f41c5cd0d.png)

Тут название объекта ```user``` сбивает с толку, т.к. дальше в коде используется так же массив ```users```, и может создаться ошибочное мнение, что ```user``` переменной для перебора массива. Однако, он вообще не имеет отношения к массиву, с помощью этого объекта происходит фильтрация и это приводит в замешательство:  ```users.filter(user.younger, user);```

Я предлагаю переименовать ```user``` в существительное, описывающее некое множество ограничений, например, ```lawbook```, а метод соответственно ```consensualRelationship``` или инфинитив, а массив ```users``` можно заменить на ```clients```, если потребуется.

Таким образом код будет логичней: ```clients.filter(lawbook.consensualRelationship, lawbook);```. Т.е. у нас есть свод законов, в нём описано множество ограничений и с помощью этого объекта идёт фильтрация.

Так же нужно сменить вывод в конце не на количество элементов(это ничего нем не говорит), а на отфильтрованные элементы, ради чего пример и был.

**Comment by iliakan** [comment]
Сейчас лучше?

**Comment by DrToldme** [comment]
Понимаете, по факту ничего не поменялось от того, что Вы просто быстренько посмотрели, заменили на johnи и ничего другого не тронули, и сразу же закрыли issue. Мгновенно.
К чему вообще нужен был Ваш комментарий тогда?
Нет, не лучше. Никак, ничего не поменялось, пример всё ещё нужно доработать:

- название метода ```younger();``` вводит в заблуждение, тк ```john.younger``` читается как "Джон младше" и дальше ожидается список кого младше Джон, а по факту всё наоборот.

- вывод количества найденных объектов ещё не говорит, что фильтрация прошла правильно, нужно вывести сами объекты, как это делалось в примерах раньше.

- теперь нет коллизии между массивом ```users``` и фильтрующим объектом, но нужно найти такое название к этому объекту, что бы вот тут ```users.filter(john.younger, john)``` прослеживалось больше логики, если это возможно. Может есть способ использования ArgThis по-другому? Что бы не было теперь ситуации когда мы передаём метод, определённый внутри объекта и потом сам объект. Возникает вопрос: "А можно лучше?". Можно не передавать сначала частичку объекта, а потом его целиком?
