### ISSUE TITLE
Неочевидный пример в главе "Методы массивов\thisArg"

### ISSUE THREAD

**Issue by DrToldme** [javascript-tutorial/ru.javascript.info#619]
Эта issue создана потому что аналогичная такая же не была решена и закрыта мгновенно, ссылка: https://github.com/javascript-tutorial/ru.javascript.info/issues/609

Вот сегмент, к которому имеются претензии:
![изображение](https://user-images.githubusercontent.com/16436298/64474730-50e9d980-d181-11e9-9146-8002ec098344.png)

Комментарий по проблеме, что нужно сделать:
https://github.com/javascript-tutorial/ru.javascript.info/issues/609#issuecomment-529101441
@iliakan

**Comment by iliakan** [comment]
А сейчас?

**Comment by DrToldme** [comment]
@iliakan, да, стало определённо лучше.
Однако проблема, описанная в последнем пункте осталась:
"Может есть способ использования ArgThis по-другому? Что бы не было теперь ситуации когда мы передаём метод, определённый внутри объекта и потом сам объект. Возникает вопрос: "А можно лучше?". Можно не передавать сначала частичку объекта, а потом его целиком?"

Возможно у Вас есть аргументы против этого? Или Вы предложите способ разделить метод и объект, но чтоб thisArg оставался?
Например, будет какой-то внешний метод, который работает с внутренним методом объекта?

**Comment by iliakan** [comment]
Я не понимаю, что вы предлагаете. 
Добавил еще:

Впрочем, тот же результат дал бы вызов `users.filter(user => army.canJoin(user))`, и он более нагляден, поэтому так пишут чаще.
