### ISSUE TITLE
Спец-символ отображается не как символ, а как его код

### ISSUE THREAD

**Issue by tjbulick** [javascript-tutorial/ru.javascript.info#620]
В [одной из статей](https://learn.javascript.ru/css-center) нашёл следующее:

![image](https://user-images.githubusercontent.com/28315191/64475118-fb183000-d186-11e9-8610-98840ff6544b.png)

Как оказалось, это код символа тире. Проверил на разных ОС на всякий случай:

![macos](https://user-images.githubusercontent.com/28315191/64475144-5e09c700-d187-11e9-8367-da13ad3d0b8c.png)

![windows](https://user-images.githubusercontent.com/28315191/64475138-521e0500-d187-11e9-8757-c874cc23abd8.png)

Поскольку в статьях много где используются спец символы, эта ошибка может многократно повторяться. Ссылка на конкретный пример сверху.

**Comment by iliakan** [comment]
Исправлено =)
