### ISSUE TITLE
Отправка простой формы - глобальные переменные

### ISSUE THREAD

**Issue by progrdk** [javascript-tutorial/ru.javascript.info#630]
Здравствуйте!
*большое спасибо за великолепный учебник*

В пункте ["Отправка простой формы"](https://learn.javascript.ru/formdata#otpravka-prostoy-formy) использован механизм доступа к DOM элементам через глобальные переменные, что, как я понял, является запредельно [плохой и опасной практикой](https://stackoverflow.com/questions/6381425/is-there-a-spec-that-the-id-of-elements-should-be-made-global-variable/6381766#6381766), а так же порождает дикий диссонанс восприятия языка и принятых правил у обучающихся (в моём случае уж точно).

**Comment by iliakan** [comment]
Вы, наверно, не по порядку учебник читали? Добавил в соответствующую главу еще разъяснения на этот счет.
