### ISSUE TITLE
Ошибка в разделе про промисы

### ISSUE THREAD

**Issue by sovetkin-am** [javascript-tutorial/ru.javascript.info#633]
Привет!

Страница - [Промисы](https://learn.javascript.ru/promise-basics)

Предлагаю убрать слово "мгновенно"/"сразу" в разделе промисы и сделать акцент, что then/catch будет вызван всегда асинхронно.

Вот этот пример:

```
// мгновенный перевод промиса в состояние "успешно завершён"
let promise = new Promise(resolve => resolve("готово!"));

promise.then(alert); // готово! (выведется сразу)
```

На примерно вот такой:

```
let promise = new Promise(resolve => resolve("готово!"));

promise.then(() => {
    promise.then(console.log);
	alert('синхронный код всегда раньше then');
 }); // готово! (выведется сразу), но асинхронно
alert('сихронный код');
```

**Comment by alexandroppolus** [comment]
Дальше идёт глава про микрозадачи, там подробно размусолен вопрос.

**Comment by iliakan** [comment]
чуть поправил формулировку 
про микрозадачи там позже
