### ISSUE TITLE
В главе "Асинхронные итераторы и генераторы" перепутаны возвращаемые значения в секции Итого

### ISSUE THREAD

**Issue by ki11en** [javascript-tutorial/ru.javascript.info#647]
В секции Итого для итераторов указано, что next() возвращает любое значение или промис (async), тогда как для генераторов указано, что next() возвращает {value:…, done: true/false} или промис с таким значением.

На мой взгляд, дожно быть написано наоборот.
![image](https://user-images.githubusercontent.com/10799208/64936201-6c2da680-d85d-11e9-8de5-6bf19bcce0bf.png)

**Comment by iliakan** [comment]
Там одно и то же.
