### ISSUE TITLE
Intersection Observer

### ISSUE THREAD

**Issue by zarabotaet** [javascript-tutorial/ru.javascript.info#658]
А почему нет статьи об этом api ?

**Comment by iliakan** [comment]
PR?

**Comment by zarabotaet** [comment]
Я бы мог предложить. Думаю этот апи неплохо "положить" рядом с Mutation Observer. Но мне нужно немного подтянуть навык написания в стиле вашей книги.
Что мне прочесть прежде?
Я так понимаю PR вначале для [javascript.info](http://javascript.info/) нужно?

**Comment by iliakan** [comment]
Да, по идее рядом с Mutation Observer ему место.

Можно прочесть Mutation Observer =) Из статьи должно быть ясно, зачем Intersection Observer нужен, где он полезен.

Вначале можно простой небольшой пример, но основа - сценарии использования на практики.

**Comment by iliakan** [comment]
закрыто по неактивности
