### ISSUE TITLE
Добавить ссылку и короткое описание prettier.

### ISSUE THREAD

**Issue by zarabotaet** [javascript-tutorial/ru.javascript.info#659]
ru.javascript.info/1-js/03-code-quality/02-coding-style
Могу предложить PR.

**Comment by iliakan** [comment]
prettier - очень общее слово, можно подробнее?

**Comment by zarabotaet** [comment]
https://prettier.io/
Имел ввиду инструмент для стилизации кода. Очень часто правила линта по стилизации берет на себя притиер. Думаю можно просто его упомянуть. Он доступен как через cli так и в ввиде плагинов ля всех популярных IDE

**Comment by iliakan** [comment]
это авто-форматтер, который использует правила линтера?

**Comment by zarabotaet** [comment]
Это форматер для кода. Вцелом он расширяет все правила линтера, которые касаются стилистики, поэтому иногда даже используют специальный плагин, что б отключить эти правила линтера и переложить это работу на притиер. [ссыль](https://prettier.io/docs/en/integrating-with-linters.html#eslint)

**Comment by iliakan** [comment]
В принципе, можно упомянуть.

**Comment by iliakan** [comment]
Хотя в редакторах есть свои автоформаттеры с правилами. Я, например, прям не вижу смысла в нем для себя.

**Comment by zarabotaet** [comment]
Он более гибко настраивается и удобно использовать в связки с линтером, особенно в CI\CD или с прекоммитами (а стандартный форматер может иметь отличное мнение от линтера и если настроены прекоммиты то стандартный форматер будет иметь свое видение стиля кода)

**Comment by zarabotaet** [comment]
Вот неплохая статья 
https://thomlom.dev/setup-eslint-prettier-react/

**Comment by iliakan** [comment]
Ок, можно упомянуть.

**Comment by iliakan** [comment]
закрыто по неактивности
