### ISSUE TITLE
Более правильное решение в задаче 

### ISSUE THREAD

**Issue by Falsin** [javascript-tutorial/ru.javascript.info#675]
Ссылка на главу https://learn.javascript.ru/array.
Мне кажется, что, следуя одному из условий второй задачи: "Замените значение в середине на «Классика». Ваш код для поиска значения в середине должен работать для массивов с любой длиной.", решение всё же должно быть таким:
let array = ["Джаз", "Блюз"];
array.push("Рок-н-ролл");
array[Math.round((array.length-1) / 2)] = "Классика";
array[Math.round(array.length / 2 - 1)] = "Классика";
console.log(array.shift());
array.unshift("Рэп", "Регги");
console.log(array);
В данном решении действительно учитывается любая длина массива (пусть количество элементов будет чётно или нечётно). А решение, приведённое в учебнике, будет корректно работать только при нечётном количестве элементов.

**Comment by iliakan** [comment]
Если четное, то середины нет, берется максимально близкое к середине значение.
