### ISSUE TITLE
Небольшая правка

### ISSUE THREAD

**Issue by germakis** [javascript-tutorial/ru.javascript.info#680]
В https://learn.javascript.ru/array-methods#concat

1) Косметические изменения. Почти все закрывающие скобки без пробела.

// создать массив из: arr и [3,4]
alert( arr.concat([3, 4])); // 1,2,3,4

// создать массив из: arr и [3,4] и [5,6]
alert( arr.concat([3, 4], [5, 6])); // 1,2,3,4,5,6

// создать массив из: arr и [3,4], потом добавить значения 5 и 6
alert( arr.concat([3, 4], 5, 6)); // 1,2,3,4,5,6

2) В этом моменте последний комментарий что означает? Забыто что-то?

alert( arr.concat(arrayLike) ); // 1,2,[object Object]
//[1, 2, arrayLike]

**Comment by iliakan** [comment]
fixed
