### ISSUE TITLE
Mistake in && section

### ISSUE THREAD

**Issue by FSamolev** [javascript-tutorial/ru.javascript.info#684]
https://learn.javascript.ru/logical-operators#i

Ошибка в примере.

if (1 && 0) { // вычисляется как true && false
  alert( "won't work, because the result is falsy" );
}

Условие возвращает false, поэтому alert должен быть в else { alert ...}, 

if (1 && 0) { // вычисляется как true && false
  alert( "" );
} else {
 alert( "won't work, because the result is falsy" );
}

**Comment by iliakan** [comment]
перевел там текст
