### ISSUE TITLE
Систематическая ошибка в примерах и задачах

### ISSUE THREAD

**Issue by Pavel-Plaschinsky** [javascript-tutorial/ru.javascript.info#689]
Например, в" 3. Автоматическое тестирование c использованием фреймворка Mocha":

Не рассмотрена самая большая неприятность pow(0, 0) -- неопределённость! Тоже должна давать NaN, по идее...

Или, раз речь идёт только о <em>натуральных числах</em>, изменить проверку на
<code> if (n <= 0) return NaN;</code>

Более того <em>(добавил позже, по мере прочтения учебника)</em> во <b><i>ВСЕХ</i></b> примерах функций, где требуется для ввода "целое положительное число" или "натуральное число", присутствует эта же неправильная проверка! Всё время через неё проскакивает НОЛЬ! В частности, в блоке "Обработка ошибок, "try..catch"" в функции fib(n).

**Comment by iliakan** [comment]
Может быть, пришлёте PR?
