### ISSUE TITLE
section 5.7  Task №1  the argument must be checked

### ISSUE THREAD

**Issue by sdf-hgnom** [javascript-tutorial/ru.javascript.info#693]
Привет All

Хочу обратить внимание на косяк в решении 1 задачи 
если подсунуть number let ret= unique(1);
то будет ошибка

т.е. надо-бы проверить аргумент ф-ции на предмет совместимости с Set(...)

function unique(arr) {
let iterator = arr[Symbol.iterator];
if (iterator === undefined){

return [];
}
let un= new Set(arr);
return Array.from(un);

т.е вернуть пустой массив --> нет ничего

**Comment by iliakan** [comment]
предполагается, что аргумент корректного типа
