### ISSUE TITLE
синтаксическая ошибка.

### ISSUE THREAD

**Issue by fomenkogregory** [javascript-tutorial/ru.javascript.info#699]
https://learn.javascript.ru/weakmap-weakset#hranenie-otmetok-ne-prochitano 
У вас есть к ним доступ, но управление этим массивом происходит где-то ещё. Добавляются новые сообщениЙ и удаляются старые, и вы не знаете в какой момент это может произойти.

стоит исправить на сообщения

**Comment by lex111** [comment]
@fomenkogregory спасибо, исправили!
