### ISSUE TITLE
1-js/08-prototypes/01-prototype-inheritance/article.md

### ISSUE THREAD

**Issue by dnzg666** [javascript-tutorial/ru.javascript.info#7]
Беру статью на перевод

**Comment by lex111** [comment]
Здравствуйте, @dnzg666, как дела с переводом?

**Comment by dnzg666** [comment]
Добрый день. Отправил PR.

**Comment by dnzg666** [comment]
@iliakan, вопрос по добавлению в [https://learn.javascript.ru/about](список). Меня забыли добавить, или это случится позже?
