### ISSUE TITLE
Ошибка в задаче

### ISSUE THREAD

**Issue by AntonKlip** [javascript-tutorial/ru.javascript.info#702]
![image](https://user-images.githubusercontent.com/34768637/67187538-18315700-f3f3-11e9-9c3b-9ffe0ceb3043.png)

**Comment by Pavel-Plaschinsky** [comment]
Тут нет ошибки. Просто имелась  в виду сортировка по-убыванию. У Ильи иногда плохо с русским языком ;).

**Comment by AntonKlip** [comment]
Решаешь, смотришь решение, и сидишь минут 5 вдупляешь "чтоооооо?" ;)

**Comment by lex111** [comment]
Спасибо, исправили, действительно, есть непонимание тут, также заменили в [оригинале](https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/05-data-types/05-array-methods/4-sort-back/task.md).

**Comment by iliakan** [comment]
@lex111 👍
