### ISSUE TITLE
Неверное изображение scrollTop на рисунке

### ISSUE THREAD

**Issue by denis-osipov** [javascript-tutorial/ru.javascript.info#725]
На [рисунке с геометрическими свойствами](2-ui/1-document/09-size-and-scroll/metric-all.svg) scrollTop не включает clientTop.

**Comment by iliakan** [comment]
404 по ссылке

**Comment by denis-osipov** [comment]
Прошу прощения, относительная ссылка получилась. Я про [этот рисунок](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/2-ui/1-document/09-size-and-scroll/metric-all.svg).

**Comment by iliakan** [comment]
было исправлено
