### ISSUE TITLE
CSS pixel

### ISSUE THREAD

**Issue by svetley1** [javascript-tutorial/ru.javascript.info#729]
В [статье про единицы измерения](https://learn.javascript.ru/height-percent) описание px начинается с: "Пиксель px – это самая базовая, абсолютная и окончательная единица измерения.
Количество пикселей задаётся в настройках разрешения экрана, один px – это как раз один такой пиксель на экране. Все значения браузер в итоге пересчитает в пиксели."

НО следует отметить, что существует понятие [CSS Pixel](https://developer.mozilla.org/en-US/docs/Glossary/CSS_pixel). То, что мы пишем в HTML и CSS - как раз CSS Pixel и он может отличаться от физического. 

Еще существует понятие reference pixel ([в середине параграфа](https://www.w3.org/TR/css-values-3/#px) ), который определяет размер пикселя в зависимости от предпологаемой удаленности дисплея от газ пользователя.

В специфакации явно указано, что CSS пиксель может быть привязан как к физическому пикселю, так и к reference pixel (см предыдущую ссылку ): "
For a CSS device, these dimensions are anchored either
- by relating the physical units to their physical measurements, or
- by relating the pixel unit to the reference pixel.
"

Кроме того, насколько мне известно, современный алгоритм масштабирования веб-страницы строится на изменении CSS разрешения. 
Вот пример CSS разрешения и разной плотности пикселей:

![image](https://user-images.githubusercontent.com/44160260/68114587-34b3b000-ff18-11e9-9c70-c39e85efb19c.png)

Или вот зависимость CSS пискселя в зависимости от предпологаемого использования устройства: 
https://www.w3.org/TR/css-values-3/images/pixel1.png
![image](https://user-images.githubusercontent.com/44160260/68119109-9decf080-ff23-11e9-80ec-46bb422802a1.png)

![image](https://user-images.githubusercontent.com/44160260/68119133-b9f09200-ff23-11e9-84a2-ab8ddc0dd686.png)

**Comment by iliakan** [comment]
весь этот раздел нужно кардинально обновить
