### ISSUE TITLE
заменить bottom на top

### ISSUE THREAD

**Issue by mezhnin** [javascript-tutorial/ru.javascript.info#735]
в статье https://learn.javascript.ru/coordinates, в примере "Координаты относительно документа"

надо заменить 
message.style.top = coords.bottom + "px";
на
message.style.top = coords.top + "px";

**Comment by lex111** [comment]
Нет тут никакой ошибки, попробуйте перейти на страницу https://learn.javascript.ru/coordinates и скопировать в консоль измененный код, у вас не будет ожидаемого результата:

> Кнопка с id=«coords-show-mark», сообщение появится под ней
