### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by SeniorIgor** [javascript-tutorial/ru.javascript.info#750]
Присутствует ошибка. На изображениях scrollTop отмечен не одинаково
![37A9EA3F-8438-4C30-A04F-58B01FDD8609](https://user-images.githubusercontent.com/52932834/69012430-c4307880-0986-11ea-81f6-ca136ebbe8a5.png)

![A1D5D3D1-EB60-4985-96DA-983001D1B428](https://user-images.githubusercontent.com/52932834/69012437-db6f6600-0986-11ea-8f63-96a0e429db69.png)

**Comment by iliakan** [comment]
fixed?
