### ISSUE TITLE
the fault on task 3 "Функция в if" explanation  (page https://learn.javascript.ru/closure)

### ISSUE THREAD

**Issue by godofnoobs** [javascript-tutorial/ru.javascript.info#753]
The explanation of the task 3 "Функция в if" is wrong.
The result won't be an error, cos the function sayHi declaration will be hoisted top outside of "if" block scope.
If you would like demonstrate such type of code behaviour you should use strict mode or function expression inside the block scope, like
let sayHi = function () {
    alert(`${phrase}, ${user}`);
  }

Best regards

**Comment by iliakan** [comment]
All code is assumed to run in strict mode by default in this tutorial.
