### ISSUE TITLE
Ошибка 404 ссылки на странице с устаревшей инфо

### ISSUE THREAD

**Issue by encrypted-fox** [javascript-tutorial/ru.javascript.info#757]
Воспроизведение - перейдите по ссылке https://learn.javascript.ru/function-declaration-expression, нажмите на ссылку сверху страницы.
![Screenshot_20191121-193633_Browser](https://user-images.githubusercontent.com/33814692/69357504-41653180-0c96-11ea-9851-fbfb2827cee2.jpg)
![Screenshot_20191121-193702_Browser](https://user-images.githubusercontent.com/33814692/69357505-41653180-0c96-11ea-8b51-e6a9d7532576.jpg)

**Comment by iliakan** [comment]
fixed thanks!
