### ISSUE TITLE
Уточнение в тексте. call/apply

### ISSUE THREAD

**Issue by FSamolev** [javascript-tutorial/ru.javascript.info#759]
https://learn.javascript.ru/call-apply-decorators

"Теперь он работает с любым количеством аргументов."

Всё-таки работает не с любым количеством, а только с  **двумя** аргументами.

**Comment by iliakan** [comment]
Разве? Декоратор работает с функцией с любым количеством аргументов.

**Comment by iliakan** [comment]
В данном примере 2. Но могло бы быть и 3.
