### ISSUE TITLE
Ошибка 500 при попытке оплатить курс

### ISSUE THREAD

**Issue by pitersky** [javascript-tutorial/ru.javascript.info#763]
Профиль: https://learn.javascript.ru/profile/yuri-shilka

Курс "JavaScript/DOM/Интерфейсы" для программистов. Я его отложил неделю назад, сегодня попытался оплатить, любой из методов оплаты выдаёт 500.

Перед совершением оплаты я поменял имя пользователя в профиле.

**Comment by iliakan** [comment]
Да, видимо, ошибка из-за этого, видимо, надо более понятное сообщение сделать.

Вы пытаетесь редактировать заказ и оплатить, да?

**Comment by iliakan** [comment]
Сейчас должно сработать.
