### ISSUE TITLE
Побитовые операторы (Материал на этой странице устарел, поэтому скрыт из оглавления сайта.)

### ISSUE THREAD

**Issue by artalar** [javascript-tutorial/ru.javascript.info#765]
Почему этот раздел скрыт, разве там что-то устарело?

https://learn.javascript.ru/bitwise-operators

![изображение](https://user-images.githubusercontent.com/27290320/69827906-8525e100-122a-11ea-8220-2979e377690f.png)

**Comment by iliakan** [comment]
В общем-то ничего, просто редко надо, перенес в основное оглавление =)
