### ISSUE TITLE
Ошибка в getter/setter 

### ISSUE THREAD

**Issue by FSamolev** [javascript-tutorial/ru.javascript.info#767]
https://learn.javascript.ru/property-accessors

> _При попытке удалить свойство-аксессор оператором delete будет ошибка._

Через delete удалить можно, ошибки не будет. На mdn об этом прямо написано.

> _If you want to remove the getter, you can just delete it_
`delete obj.latest;`

Про _setter_ аналогично.

Ошибка будет, если было добавление через `Object.defineProperty` без установки `configurable: true`

**Comment by iliakan** [comment]
Да, поправил. Спасибо.
