### ISSUE TITLE
Not sure if the question is correct.

### ISSUE THREAD

**Issue by assumetry** [javascript-tutorial/ru.javascript.info#778]
the question asks us to make a html page with function that solves a exponentiation. There also is a rule, that exponent HAS to be a natural number. The answer is written like this
<pre>function pow(x, n) { let result = x;
  for (let i = 1; i < n; i++) { result *= x;  }
  return result;}
let x = prompt("x?", '');
let n = prompt("n?", '');
if (n < 1) {alert(`Степень ${n} не поддерживается, используйте натуральное число`);
} else {alert( pow(x, n) );} </pre>
but in this case we can do n=2.5 and that is not a natural number? Is that a mistake, or am I missing something?

**Comment by assumetry** [comment]
link to the page
https://learn.javascript.ru/function-basics
4th question. Sorry for not including into the main message.

**Comment by melyru** [comment]
The fact is that before this lesson the functions necessary for rounding the numbers were not studied, so if they were added to this example this would cause confusion among users
