### ISSUE TITLE
inconsistent method names

### ISSUE THREAD

**Issue by exarces** [javascript-tutorial/ru.javascript.info#781]
В разделе Примеси (https://learn.javascript.ru/mixins) в примере EventMixin. Неверно указаны имена аргументов у трех методов. Имена в объяснение кода не совпадают с имена в самом коде. И неправильный порядок перечисления (если это важно)
![image](https://user-images.githubusercontent.com/33513899/70380484-4cce8300-194d-11ea-88c5-2c41867784a9.png)

**Comment by exarces** [comment]
> В разделе Примеси (https://learn.javascript.ru/mixins) в примере EventMixin. Неверно указаны имена аргументов у трех методов. Имена в объяснение кода не совпадают с имена в самом коде. И неправильный порядок перечисления (если это важно)
> ![image](https://user-images.githubusercontent.com/33513899/70380484-4cce8300-194d-11ea-88c5-2c41867784a9.png)

**Comment by lex111** [comment]
В данном случае это не так важно: в тексте указана спецификация методов, а не точная сигнатура из кода, - это проще для чтения (тем более дальше идёт пояснение), в самом же кода уже больше конкретики, чтобы было понятнее. Как-то так, но не должно вызывать путаницы, всё в целом ясно.
