### ISSUE TITLE
 Typo

### ISSUE THREAD

**Issue by fomenkogregory** [javascript-tutorial/ru.javascript.info#785]
Met small typo in this article:
https://learn.javascript.ru/currying-partials
![carry](https://user-images.githubusercontent.com/51916577/70627355-89e19080-1c3f-11ea-8a3b-f3403169c645.png)

**Comment by fomenkogregory** [comment]
One more: 
https://javascript.info/regexp-unicode
![212](https://user-images.githubusercontent.com/51916577/70748802-2c833780-1d44-11ea-9e17-f69ceef4e279.png)

**Comment by lex111** [comment]
Спасибо, все опечатки исправлены.
