### ISSUE TITLE
Грамматическая ошибка

### ISSUE THREAD

**Issue by Matcenko** [javascript-tutorial/ru.javascript.info#790]
![Снимок экрана 2019-12-26 в 19 18 10](https://user-images.githubusercontent.com/42418799/71484348-9e638280-2814-11ea-92b9-95dfa2c5c394.png)

В данном случае слово некорректен должно писаться слитно

**Comment by Matcenko** [comment]
https://learn.javascript.ru/try-catch

**Comment by lex111** [comment]
@Matcenko спасибо, исправлено!
