### ISSUE TITLE
Тест знаний. Заявленный ответ как правильный - не соответствует действительности.

### ISSUE THREAD

**Issue by demimurych** [javascript-tutorial/ru.javascript.info#793]
> Вопрос:
> Сколько детей (дочерних DOM-узлов) у элемента <ul> в примере ниже:
> ```
> <ul>
>   <li>Привет</li>
>   <li>Мир</li>
> </ul>
> ```
> 
> Заявлен правильный ответ:
> 5

Формулировка вопроса подразумевает, что тестируемый должен учесть текстовые ноды расположенные между элементами: ul -> li, li->li, li->ul 
Что приводит к цифре 5 (3 текстовые ноды плюс две LI)

Однако это не до конца верно. 
Между узлами может быть больше одной текстовой ноды, и это внешне никак заметно не будет. 
То есть правильный ответ: больше или равно пяти. 

Удостовериться можно в этом проведя простой тест:
```
<ul id="ul">
 <li id="li">Привет</li>
 <li>Мир</li>
</ul>
```

```
let textnode=document.createTextNode("");
ul.insertbefore(textnode, li);
ul.childNodes
NodeList(6) [text, text, li#li, text, li, text]
```

**Comment by iliakan** [comment]
Там дан HTML. При парсинге HTML не может быть больше одной текстовой ноды между элементами.

**Comment by demimurych** [comment]
> Там дан HTML. При парсинге HTML не может быть больше одной текстовой ноды между элементами.

Мне кажется что тут есть некоторое недопонимание.
Я прошу Вас прислушаться, и быть может кто-то из нас изменит свою точку зрения.

Вы предлагаете задачу, решение которой лежит в области реализации алгоритма построения DOM дерева. Алгоритма реализация которого, во многих своих частях НЕ НОРМИРОВАНА. То есть прописана в стандарте как рекомендации. Иначе говоря ошибкой считается только  DOM дерево которое не удовлетворяет его спецификации.

Иными словами, если спецификация допускает в DOM  существование нескольких текстовых узлов подряд, а алгоритм формирования начального DOM  не только не имеет обязательной к исполнению спецификации,  но и подчеркивает, что реализация может напрямую зависеть от пользовательского агента, то утверждать, что при составлении дерева всегда будет одна текстовая нода, между двумя другими, некорректно. 

>The algorithm described below places no limit on the depth of the DOM tree generated, or on the length of tag names, attribute names, attribute values, Text nodes, etc. While implementers are encouraged to avoid arbitrary limits, it is recognized that practical concerns will likely force user agents to impose nesting depth constraints.

> User agents may impose implementation-specific limits on otherwise unconstrained inputs, e.g., to prevent denial of service attacks, to guard against running out of memory, or to work around platform-specific limitations.

> For performance reasons, an implementation that does not report errors and that uses the actual state machine described in this specification directly could use the PLAINTEXT state instead of the RAWTEXT and script data states where those are mentioned in the list above. Except for rules regarding parse errors, they are equivalent, since there is no appropriate end tag token in the fragment case, yet they involve far fewer state transitions.

Ну и, строго говоря, даже если бы в спецификации было прописана обязательная нормализация текстовых нод,  практического смысла в  задаче из теста, нет никакого.  По причине того, что понимание этого факта, не влечет за собой никакого влияния на то, как  агент должен обрабатывать DOM. 
А именно, **он всегда должен** его обрабатывать, как дерево в  котором может быть любое количество текстовых узлов стоящих подряд.

**Comment by iliakan** [comment]
В какой именно среде выполнения JS при парсинге такого HTML получается две текстовых ноды? 

Если вы такую дадите - я прислушаюсь. До этого момента - извините, но issue закрыта.
