### ISSUE TITLE
Если они не равны ничему другому, то это значит что они не равны и сами себе.

### ISSUE THREAD

**Issue by MaximYaskov** [javascript-tutorial/ru.javascript.info#795]
> Значения null и undefined равны == друг другу и не равны любому другому значению.

> Эти значения равны друг другу и не равны никаким другим значениям.

> они равны друг другу и не равны ничему другому

https://learn.javascript.ru/comparison

**Comment by iliakan** [comment]
Там реально что-то непонятно или вы придираетесь? =)
