### ISSUE TITLE
Не запускается тест с использованием Mocha

### ISSUE THREAD

**Issue by vsiliuk** [javascript-tutorial/ru.javascript.info#796]
Создал html-файл с таким же содержанием что и в статье про [автоматическое тестирование c использованием фреймворка Mocha](https://learn.javascript.ru/testing-mocha), добавил начальную реализацию в test.js файл, но при открытии html-страницы в браузере было выведено только это:
![изображение](https://user-images.githubusercontent.com/36772576/71689361-ece3c480-2db2-11ea-9755-279118cf95ff.png)

**Comment by iliakan** [comment]
А в учебнике все работает или ошибка? Сделайте песочницу с вашим примером.
