### ISSUE TITLE
Регулярные выражения.Ретроспективные и опережающие проверки.

### ISSUE THREAD

**Issue by Canvas04** [javascript-tutorial/ru.javascript.info#799]
Здравствуйте! В данном примере  про ретроспективные негативные проверки регулярное выражение работает некорректно , если поставить флаг g.Выражение выводит не только цифру 2 , но и цифры стоящие после цифры 6
let str = "2 индейки стоят $60";

alert( str.match(/(?<!\$)\d+/) ); // 2 (проигнорировалась цена)

**Comment by iliakan** [comment]
Вариант в учебнике работает корректно? Ошибка есть или нет - не понимаю?

**Comment by Ruslan04071996** [comment]
Работает корректно
