### ISSUE TITLE
Язык программирования JavaScript > Типы данных > Строки > Правильное сравнение

### ISSUE THREAD

**Issue by ishoomsky** [javascript-tutorial/ru.javascript.info#802]
Язык программирования JavaScript > Типы данных > Строки > Правильное сравнение
Ссылка: [https://learn.javascript.ru/string#pravilnoe-sravnenie](url)

Возможно, тут опечатка:
> Отрицательное число, если str **меньше** str2.
> Положительное число, если str **больше** str2.

```
let str = 'a';
let str2 = 'A';

str.localeCompare(str2); //-1  
//'a' больше 'A'
//Отрицательное число, если str больше str2
```
```
let str = 'B';
let str2 = 'b';

str.localeCompare(str2); //1  
//'B' меньше 'b'
//Положительное число, если str меньше str2
```

**Comment by iliakan** [comment]
Не вижу ошибки: `"a".localeCompare('z') = -1` , то есть str < str2.
