### ISSUE TITLE
Не нашел, как попасть на страницу "скринкасты" с мобильной версии сайта

### ISSUE THREAD

**Issue by priestofkarma** [javascript-tutorial/ru.javascript.info#814]
+ на странице скринкаста вот такой баг с версткой в мобильной версии сайта
![изображение](https://user-images.githubusercontent.com/43789165/72517094-738cad00-385b-11ea-8716-a2918bb62914.png)

**Comment by GSemikozov** [comment]
в итоге надо пофиксить позиционирование контента и футера? или же баг заключается в том, что на мобилке нет навигационного меню по которому можно добраться до скринкастов? @DarkLurkerrr

**Comment by DarkLurkerrr** [comment]
да и то и другое
