### ISSUE TITLE
Тесты знаний: другой заявленный ответ не соответствует действительности

### ISSUE THREAD

**Issue by wentout** [javascript-tutorial/ru.javascript.info#821]
Во всех браузерах и в Node.js получаю `NaN`, а `'use strict';` вроде бы ни при чём...

![image](https://user-images.githubusercontent.com/1651439/72986047-61c97d80-3df8-11ea-9b1b-5222f8ae4ce0.png)

**Comment by iliakan** [comment]
Переменная не определена. use strict очень даже причем.
