### ISSUE TITLE
Ошибка в тесте

### ISSUE THREAD

**Issue by rudoyKolya** [javascript-tutorial/ru.javascript.info#823]
![Capture](https://user-images.githubusercontent.com/38522312/73063277-83d20700-3eaf-11ea-9120-a4f0434bf269.PNG)

звездочка может использоваться в генераторах

**Comment by alex-karo** [comment]
Насколько я это вижу - самостоятельно звездочка в генераторах оператором не является, она входит в состав других ключевых слов и выражений

**Comment by iliakan** [comment]
Да
