### ISSUE TITLE
Грамматическая неточность.

### ISSUE THREAD

**Issue by sese911** [javascript-tutorial/ru.javascript.info#828]
Здравствуйте.
Извините, что придираюсь к подобным мелочам, но в русской версии учебника в статье "Рекурсия и стек" во второй строке написано - "Наша первая тема будет рекурсия". Звучит как-то не по русски. Может лучше написать так - "Нашей первой темой будет рекурсия", или так - "Наша первая тема - рекурсия".

**Comment by lex111** [comment]
@sese911 здравствуйте, да, вы совершенно правы, поэтому изменили это предложение, спасибо, что сообщили об этом! https://github.com/javascript-tutorial/ru.javascript.info/commit/88e799f0e17b54349194ac78006cf98a09220371
