### ISSUE TITLE
В задаче с выражением (i++ < 5) написано что (i++) выполняется после (<) 

### ISSUE THREAD

**Issue by Michael1195** [javascript-tutorial/ru.javascript.info#840]
Раздел: Основы JavaScript - Циклы while и for
Задача: Какие значения выведет цикл while?

![Screenshot_1](https://user-images.githubusercontent.com/34819933/73839005-9d633f00-481d-11ea-8264-d9e3ad5b3d89.png)

**Comment by fomenkogregory** [comment]
А в чем вопрос? Здесь все верно.

**Comment by Michael1195** [comment]
Вопрос в приоритете операторов,

Как я понимаю и с доков learn.javascript(инкременты) и с MDN, то в выражении (i++ < 5) 
сначала все таки сработает операция (i++) увеличивая (i) до 1 и возвращая на свое место старое значение. И только после этого произойдет сравнение.

Если что поправьте.

**Comment by ArMANIAK** [comment]
В JavaScript, как и в некоторых других языках программирования, сначала происходит операция (в данном случае, сравнения), а потом изменение значения переменной при постфиксном инкременте (i++), и наоборот при префиксном (++i).
Так что все правильно написано.
