### ISSUE TITLE
Ошибочный вариант ответа в тесте знаний

### ISSUE THREAD

**Issue by prosvirninvlad** [javascript-tutorial/ru.javascript.info#853]
Обращение к свойству объекта, которое отсутствует, всегда возвращает undefined (в тесте правильный ответ "будет ошибка").
<img width="814" alt="Снимок экрана 2020-02-12 в 22 04 11" src="https://user-images.githubusercontent.com/8470692/74367960-cb2f2180-4de3-11ea-8629-b8589a195a4b.png">

**Comment by oleedd** [comment]
![image](https://user-images.githubusercontent.com/36125949/74530460-c9c03f00-4f32-11ea-8365-7c10b878a123.png)
