### ISSUE TITLE
Отправление текстовых ошибок через Ctrl+Enter

### ISSUE THREAD

**Issue by oleedd** [javascript-tutorial/ru.javascript.info#856]
В параграфах по 1-3 пунктуационные ошибки. Быстрее - отправлять их через Ctrl+Enter (с комментарием), как это работает на других сайтах, чтобы не заморачиваться с PR.

**Comment by oleedd** [comment]
А зря. Мигом бы всё исправили. Большинство читающих даже не зайдёт сюда.

**Comment by Alexandre887** [comment]
В каждой статье, в левом сайдбаре присутствует кнопка "Редактировать на Github". Нажимаете на неё, выбираете нужный файл, редактируете его и нажимаете на "Propose changes". После чего Github сам предложит вам создать Pull Request. 

К тому же, использовать PR'ы намного удобнее. Мейнтейнеры могут запросить у автора изменение одной или нескольких его предложенных правок, прокомментировать правки, или просто принять их.

Практика показывает, что это лучший вариант исправления текстов в учебнике. В одной только русской версии было принято более тысячи правок. Реализации функционала с Ctrl+Enter нецелесообразна.
