### ISSUE TITLE
Неточность про возведение в степень в главе "Операторы"

### ISSUE THREAD

**Issue by TheDreamCatcher** [javascript-tutorial/ru.javascript.info#866]
В главе https://learn.javascript.ru/operators есть пример 

alert( 4 ** (1/2) ); // 2 (степень 1/2 эквивалентна взятию квадратного корня)
alert( 8 ** (1/3) ); // 2 (степень 1/3 эквивалентна взятию кубического корня)

На самом деле это не так, возведение в степень с действительным показателем степени определён только для положительного основания, а корень на всем множестве.

Пример для тестирования

(-8)**(1/3)

Вернёт NaN, хотя кубический корень из -8 => -2

**Comment by Alexandre887** [comment]
Спасибо за замечание. Неточная информация удалена.
