### ISSUE TITLE
Объекты: основы. 4.1 Объекты. Количество типов данных

### ISSUE THREAD

**Issue by abarmina** [javascript-tutorial/ru.javascript.info#872]
Самый первый абзац:
> Как мы знаем из главы Типы данных, в JavaScript существует **семь** типов данных. **Шесть** из них называются «примитивными», так как содержат только одно значение (будь то строка, число или что-то другое).

Типов данных **восемь**, а **семь** из них называются «примитивными».

**Comment by Alexandre887** [comment]
Неактуально.
