### ISSUE TITLE
Вы допустили ошибку исправьте пожалуйста

### ISSUE THREAD

**Issue by KamilMagomedov** [javascript-tutorial/ru.javascript.info#875]
Добрый вечер разработчики сайта хотел вас предупредить что вы допустили ошибку когда писали одну задачу,первую,  Чему будут равны переменные a, b, c и d в примере ниже? там b = 1, а вы написали 2!будьте внимательны пожалуйста!)))

**Comment by maxnest2006** [comment]
Уточните, пожалуйста, в какой статье ошибка. Также вы можете исправить её сами и сделать Pull request.
Я не разработчик этого сайта, просто всё равно так будет лучше.

**Comment by semaphore8** [comment]
Камиль, о каком примере идет речь?

**Comment by Alexandre887** [comment]
Некорректная issue, закрываю.
