### ISSUE TITLE
Раздел: Методы массивов (метод splice)

### ISSUE THREAD

**Issue by magacode** [javascript-tutorial/ru.javascript.info#882]
Здравствуйте! Проверьте пожалуйста следующую строку, мне кажется там опечатка:
arr.splice(index[, deleteCount, elem1, ..., elemN])

Если я правильно понимаю данный метод, то второй параметр указывающий количество удаляемых элементов deleteCount является обязательным. Мне кажется тут должно быть написано так:

arr.splice(index, deleteCount [, elem1, ..., elemN]) - переместил квадратную скобку дальше.

**Comment by blohamen** [comment]
На MDN действительно указан вариант, который Вы предоставили, но если зайди в консоль chrome-а и прописать `[1,2,3].splice(` ,то хром покажет что deleteCount идет со значком ?, что означает что он необязательный. 
Если прописать полностью пример `[1,2,3].splice(2)` то результат будет [3]. Т.е как мне кажется,  что строка изначально верна была составлена.
