### ISSUE TITLE
Outdated info

### ISSUE THREAD

**Issue by dmrnz** [javascript-tutorial/ru.javascript.info#897]
[Здесь в конце статьи](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/8-web-components/2-custom-elements/article.md):

> Пользовательские элементы широко поддерживаются браузерами. Edge немного отстаёт, но есть полифил https://github.com/webcomponents/webcomponentsjs.

Но ведь Edge с февраля, кажется, перешёл на Chromium, и поэтому уточнение про Edge уже неактуально

**Comment by kpodmasko** [comment]
Edge перешел на Chromium, но все равно еще есть пользователи, которые не обновили Edge и используют старую версию без Chromium.

**Comment by renuo-nego** [comment]
Я понимаю, но в данной формулировке, мне кажется, имеются ввиду именно основные поддерживаемые браузеры. Нет же упоминания того же IE.

**Comment by Alexandre887** [comment]
### Неактуально.

![image](https://user-images.githubusercontent.com/74434545/187041447-1c60cc33-44ec-49a4-bf49-9d1f4a695f3d.png)
