### ISSUE TITLE
Авторизация через GitHub

### ISSUE THREAD

**Issue by vadyton** [javascript-tutorial/ru.javascript.info#907]
При попытке авторизоваться через гитхаб выдает 400 ошибку ссылаясь на то, что имя пользователя должно содержать не менее 1 символа
<img width="1278" alt="Снимок экрана 2020-04-03 в 20 49 56" src="https://user-images.githubusercontent.com/63119823/78391035-421bb600-75ee-11ea-86ed-0270eee6a0c5.png">

**Comment by Alexandre887** [comment]
Добрый вечер. Проблема еще актуальна?
