### ISSUE TITLE
Правила вызова функции при работе с addEventListener (removeEventListener)

### ISSUE THREAD

**Issue by nallden** [javascript-tutorial/ru.javascript.info#908]
https://learn.javascript.ru/mousewheel#masshtabirovanie-kolyosikom-myshi

**Comment by nallden** [comment]
в песочнице для решения данной задачи используется анонимная функция при работе с addEventListener, но если человек захочет сделать removeEventListener, то у него ничего не выйдет, так как функция обязательна должна быть внешней. Ошибок в консоли он при этом также не сможет отследить.

Цитата с сайта https://www.w3schools.com/jsref/met_element_removeeventlistener.asp:

"To remove event handlers, the function specified with the addEventListener() method must be an external function...
...Anonymous functions, like "element.removeEventListener("event", function(){ myScript });" will not work."

**Comment by randomnf** [comment]
Цель задачи не в этом. Безусловно, если бы потребовалось в будущем снять этот обработчик, нужно было бы использовать именованную функцию (или переписать код по необходимости).

Если задача не предполагает снятия обработчика, анонимная функция - отличный вариант.

**Comment by Alexandre887** [comment]
Неактуально.
