### ISSUE TITLE
Ошибка в статье "Объекты основы"

### ISSUE THREAD

**Issue by Slav4ik888** [javascript-tutorial/ru.javascript.info#911]
Либо я не понял материал, либо есть небольшая ошибка.

Место где описывается про очень редкую ситуацию, когда значение в объекте = undefined.

> Таким образом, оператор in является экзотическим гостем в коде.

Возможно вместо in нужно указать undefined ? Именно он является экзотикой?

**Comment by Alexandre887** [comment]
@Slav4ik888, некорректное утверждение удалили.

@oleedd, пунктуация исправлена в 0d8168c.
