### ISSUE TITLE
ляп в статье "Function Expression"

### ISSUE THREAD

**Issue by QQpy3ko** [javascript-tutorial/ru.javascript.info#914]
https://learn.javascript.ru/function-expressions

После
> Это произошло, так как объявление Function Declaration видимо только внутри блока кода, в котором располагается.
> 
> Вот ещё один пример:

в примере, кажется, нужно, скобочку первую из строки 12 в строку 10 перенести (второй 
вызов  `welcome()` чтобы в блоке `else`  был

```let age = 16; // присвоим для примера 16

if (age < 18) {
  welcome();               // \   (выполнится)
                           //  |
  function welcome() {     //  |
    alert("Привет!");      //  |  Function Declaration доступно
  }                        //  |  во всём блоке кода, в котором объявлено
                           //  |
  welcome();               // /   (выполнится)

} else {

  function welcome() {
    alert("Здравствуйте!");
  }
}

// здесь фигурная скобка закрывается,
// поэтому Function Declaration, созданные внутри блока кода выше -- недоступны отсюда.

welcome(); // Ошибка: welcome is not defined```
Спасибо.

**Comment by randomnf** [comment]
Это не ошибка. Так сделано для того, чтобы показать, что функцию, объявленную как FD, можно вызвать и до ее объявления, и после.
В блоке `else` функция объявлена еще раз для того, чтобы показать, что снаружи блока она видна (или, переопределена) не будет.

**Comment by QQpy3ko** [comment]
Спасибо, что-то меня поплавило тогда, противоречий с текстом же нет никаких. Прошу прощения!
