### ISSUE TITLE
Ошибка верстки

### ISSUE THREAD

**Issue by nikita-prokopov** [javascript-tutorial/ru.javascript.info#915]
**Раздел:** Обработка ошибок
**Тема:** Пользовательские ошибки, расширение Error
https://learn.javascript.ru/custom-errors

**Браузер:** Версия 4.1.7.182 (Официальная сборка), (32 бит) (Chromium 78.0.3904.108)

![Screenshot_1](https://user-images.githubusercontent.com/61139889/79308692-b9601c80-7f01-11ea-8534-a3a4396fae67.png)

**Comment by nikita-prokopov** [comment]
https://learn.javascript.ru/custom-errors

**Comment by nikita-prokopov** [comment]
Вот ещё одна:
https://learn.javascript.ru/modules-intro

![Screenshot_1](https://user-images.githubusercontent.com/61139889/79358282-acffb200-7f49-11ea-87ac-619669873fee.png)

**Comment by Alexandre887** [comment]
> **Раздел:** Обработка ошибок **Тема:** Пользовательские ошибки, расширение Error https://learn.javascript.ru/custom-errors
> 
> **Браузер:** Версия 4.1.7.182 (Официальная сборка), (32 бит) (Chromium 78.0.3904.108)
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/61139889/79308692-b9601c80-7f01-11ea-8534-a3a4396fae67.png)

### Исправлено:

![image](https://user-images.githubusercontent.com/74434545/187040512-5f367caa-4590-403f-a4b1-4ffc4b611751.png)



> Вот ещё одна: https://learn.javascript.ru/modules-intro
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/61139889/79358282-acffb200-7f49-11ea-87ac-619669873fee.png)

### Исправлено:

![image](https://user-images.githubusercontent.com/74434545/187040572-b196395c-b047-4fc8-9e90-b21bfea0fa01.png)
