### ISSUE TITLE
6.3 Замыкание. Ошибка в тексте

### ISSUE THREAD

**Issue by abarmina** [javascript-tutorial/ru.javascript.info#916]
Блок "Продвинутая работа с циклами", часть "[Блоки кода](https://learn.javascript.ru/closure#bloki-koda)", конец 2 абзаца: 
> перезаписывают друг**а** друга.

Нужно исправить на:
> перезаписывают друг друга.

**Comment by randomnf** [comment]
На такие простые и очевидные ошибки можно сразу PR открывать) Это очень поможет мейнтейнерам учебника.

**Comment by Alexandre887** [comment]
Исправлено.
