### ISSUE TITLE
Событийный цикл: микрозадачи и макрозадачи

### ISSUE THREAD

**Issue by MaximYaskov** [javascript-tutorial/ru.javascript.info#917]
1. Ошибка в последней картинке: рендеринг стоит перед микрозадачами.
2. Ошибка в одном из примеров: не `1e7`, а `1e6`.
https://learn.javascript.ru/event-loop

**Comment by BoldyrevDA** [comment]
Согласен последовательность рендеринга и микрозадач давно глаз режет:
![image](https://user-images.githubusercontent.com/22929109/95194490-64350180-07e6-11eb-870c-4e9db364ec3d.png)
