### ISSUE TITLE
Грамматическая ошибка.

### ISSUE THREAD

**Issue by samius-s** [javascript-tutorial/ru.javascript.info#924]
В главе: Проверка класса: "instanceof"

Кстати, есть метод objA.isPrototypeOf(objB), **которые** возвращает true, если объект objA есть где-то в прототипной цепочке объекта objB.

"которые" --> "который".

**Comment by lex111** [comment]
Спасибо, исправлено в коммите https://github.com/javascript-tutorial/ru.javascript.info/commit/42176a6e7ef42897fe56ec36edaed6250157a479
