### ISSUE TITLE
Несколько замечаний относительно раздела "Промисы".

### ISSUE THREAD

**Issue by denisnow** [javascript-tutorial/ru.javascript.info#925]
1. В тексте о промисах "https://learn.javascript.ru/promise-basics" есть странный текст:

"Почему так? Скоро нам станет понятно."

Вы не могли бы написать сразу в чём дело или дать ссылку? Не заставляйте читателя читать дальше. Даже не понятно, сколько ещё надо прочитать и где ответ.

2. Мне кажется, что текст "Обработчик finally «пропускает» результат или ошибку дальше, к последующим обработчикам." ошибочный. Может это промис, созданный методом finally, а не обработчик, «пропускает» результат или ошибку дальше, к последующим обработчикам?

3. Почему, если не ошибаюсь, нигде в этом разделе нет информации о том, что при вызове методов then, catch, finally создаётся новый промис? Для кого-то это может показаться очевидным, кто-то может это понять исходя из текста "у промисов также есть метод finally", но мне кажется что луше написать об этом, чтобы было ясно без домыслов. Это может помочь тем, кто учит язык.

**Comment by denisnow** [comment]
Немного исправил сообщение.

**Comment by denisnow** [comment]
Да и вообще, мне кажется, что называть обработчиком функцию, передаваемую в метод finally, не правильно. Она ведь ничего не обрабатывает.

**Comment by denisnow** [comment]
А может имеется ввиду обработка изменения статуса промиса, по аналогии с обработчиком событий? Но там обработчиком называют саму функцию, вызываемую, когда происходит событие, а в учебнике часто используется формулировка "обработчик then/catch/finally".
И еще - формулировка "Обработчик, вызываемый из finally" звучит странно.

**Comment by denisnow** [comment]
Так как изменение может не произойти, так как оно произошло раньше, то может это просто обработчик состояния?

**Comment by denisnow** [comment]
С другой стороны в обработчик событий передаётся информация о событии, а в функцию передаваемую в finally, ничего не передаётся.

**Comment by denisnow** [comment]
"Обработчик (handler) -- это функция, которая вызывается какой-либо программной системой в ответ на наступление какого-либо события. Чтобы система поняла, что надо вызывать именно эту функцию в ответ на это событие, обычно необходимо обратиться к какому-то специальной функции регистрации обработчиков событий (например в php)."

Выходит, что это всё таки  обработчик. Я был не прав.

**Comment by denisnow** [comment]
Дополнительно, мне кажется, что раздел Микрозадачи должен быть перед разделом Промисы, чтобы можно было объяснить читателю, в какой момент будут вызваны функции передаваемые в методы then/catch/finally. Микрозадачи можно объяснить на примере метода queueMicrotask().

**Comment by denisnow** [comment]
Раз уж я затронул раздел "Микрозадачи", я не могу не процитировать текст "Асинхронные задачи требуют правильного управления.". Это шутка? Какие-то задачи не требуют правильного управления?

Вот люди пишут об ошибках - https://github.com/javascript-tutorial/ru.javascript.info/issues/917

Вы вообще собираетесь что-то менять или так и будете эту дичь лелеять? Если нет времени, найдите кого-то другого, у кого есть. Вы же вводите читателя в заблуждение.

**Comment by randomnf** [comment]
От себя добавлю, что во всем разделе про промисы не было упоминания про то, что код в промисах выносится в отдельный поток выполнения.

**Comment by denisnow** [comment]
> 
> 
> От себя добавлю, что во всем разделе про промисы не было упоминания про то, что код в промисах выносится в отдельный поток выполнения.

Что за "код в промисах"?

**Comment by randomnf** [comment]
> Что за "код в промисах"?
```
new Promise((resolve, reject) => {
   // какие-то вычисления
});
```
Вот эти самые **какие-то вычисления** будут выполняться в соседнем потоке.

**Comment by denisnow** [comment]
> ```
> new Promise((resolve, reject) => {
>    // какие-то вычисления
> });
> ```
> 
> Вот эти самые **какие-то вычисления** будут выполняться в соседнем потоке.
> 
> В принципе, этот вывод можно сделать после прочтения раздела "Микрозадачи", но нигде явного упоминания нет.

Во первых это не "код в промисах", а исполнитель - функция обратного вызова, которую передают в конструктор промиса. Во вторых, эта функция выполняется в том-же потоке, этоже не метод API и не Web Worker.

**Comment by denisnow** [comment]
Точнее это не методы API, а некоторые опреации Web API выполняются в другом потоке или других потоках.

**Comment by denisnow** [comment]
Точнее это не методы API, а некоторые опрерации Web API выполняются в другом потоке или других потоках. Например метод fetch(), входящий в состав Fetch API выполняет определённые (сетевые) операции в другом потоке, но создаёт промис в том-же потоке, в котором работает скрипт.

**Comment by denisnow** [comment]
Немного отредактировал предыдущее сообщение.

**Comment by denisnow** [comment]
А может в очередь микрозадачь дабвляется опреция вызова оставшейся части исполнителя, по аналогии с функцией async, прерванной исполнением команды await. Или говоря по другому, может в очередь микрозадачь дабвляется опреция возобновления выполнения исполнителя. Это всё лирика, суть от этого не меняется.

**Comment by denisnow** [comment]
> 
> 
> > в другом потоке также происходит добавление вызова resolve/reject в очередь микрозадач
> 
> Даже не знаю, может более коректно будет сказать/написать, что в очередь микрозадач добавляется операция вызова оставшейся части исполнителя, по аналогии с функцией async, выполнение которой было прервано вызовом кода с оператором await. Или говоря по другому, в очередь микрозадач добавляется операция возобновления выполнения исполнителя.

Мне кажется, самый оптимальный вариант: после получения сетевого ответа, а точнее заголовков ответа или в случае ошибки, в очередь микрозадач добавляется операция изменения состояния промиса, возвращённого методом fetch.
