### ISSUE TITLE
Ошибка с "push" и "="

### ISSUE THREAD

**Issue by pew-rivza** [javascript-tutorial/ru.javascript.info#928]
В ru.javascript.info/1-js/05-data-types/04-array/article.md  -> 
Методы pop/push, shift/unshift -> 
Методы, работающие с концом массива -> 
push

Вот конкретно в этом разделе предложение: "Вызов `fruits.push(...)` равнозначен `fruits[fruits.length] = ...`." не верно, так как метод push и оператор присваивания имеют разное возвращаемое значение. Оператор вернет то значение, которое он присвоил; метод вернет длину получившегося массива.

**Comment by niskadevla** [comment]
Автор имел ввиду, что элемент можно добавить в конец массива и без метода push. Бывают такие задчи, напримермна собесах, что запрещено использовать методы массива и написать свои нужно. Так вот это панацея. А вообще Екатерина правильно подметила, на счет возвращаемого значения.
