### ISSUE TITLE
Пользовательские ошибки, расширение Error

### ISSUE THREAD

**Issue by MaximYaskov** [javascript-tutorial/ru.javascript.info#930]
Первый пример на странице перестаёт работать после первого выполнения.
(Другие примеры на данную ошибку я не тестировал).
https://learn.javascript.ru/custom-errors

**Comment by randomnf** [comment]
`SyntaxError: redeclaration of let ValidationError`

**Comment by Alexandre887** [comment]
Исправлено. Большое спасибо за обращение!
