### ISSUE TITLE
[Ошибка] Полифил Promise.allSettled

### ISSUE THREAD

**Issue by ghost** [javascript-tutorial/ru.javascript.info#933]
https://learn.javascript.ru/promise-api#polifil

В полифиле создаются объекты с ключами "state" (в примере и в описании), но "state" является внутренним свойством объекта promise. Синтаксис allSettled подразумевает ключ "**status**". 

Корректнее будет исправить под синтаксис allSettled.

**Comment by FSamolev** [comment]
https://learn.javascript.ru/promise-api#itogo

Тут тоже нужно поправить state -> status
