### ISSUE TITLE
Возможная ошибка

### ISSUE THREAD

**Issue by SymphonyNineth** [javascript-tutorial/ru.javascript.info#947]
Добрый день. Во первых спасибо за фантастический учебник.
Я не уверен, но во главе https://learn.javascript.ru/prototype-methods, в предложении - 
"Object.create(null) создаёт пустой объект без прототипа ? ([[Prototype]] будет null):"

Стоит поставить запятую/точку/тире на том месте где я поставил вопросительный знак.

**Comment by Alexandre887** [comment]
Нет, на месте вопросительного знака не требуется запятая, точка, или тире.
См. http://new.gramota.ru/biblio/readingroom/rules/162-skobki
