### ISSUE TITLE
Юникодные свойства \p{…} уже поддерживаются в Firefox 

### ISSUE THREAD

**Issue by saneq1** [javascript-tutorial/ru.javascript.info#960]
https://learn.javascript.ru/regexp-unicode
уже в мазиле работает
![image](https://user-images.githubusercontent.com/20462876/83345607-dddf4f00-a31d-11ea-9ad0-cb769f7845b9.png)

**Comment by Alexandre887** [comment]
Спасибо за обращение. Неактуальная информация убрана:

![image](https://user-images.githubusercontent.com/74434545/187519256-c1e0811d-9af1-40f7-8760-1e96ca9c2628.png)
