### ISSUE TITLE
Опечатка в главе Fetch: запросы на другие сайты

### ISSUE THREAD

**Issue by GVakil** [javascript-tutorial/ru.javascript.info#969]
![image](https://user-images.githubusercontent.com/53818127/84006645-89287d80-a988-11ea-9361-33184508c4bb.png)

В главе (https://learn.javascript.ru/fetch-crossorigin) должно быть "по умолчанию"

**Comment by Alexandre887** [comment]
### Исправлено:

![image](https://user-images.githubusercontent.com/74434545/187503099-d4db43d9-508b-4ec2-86e8-dbbd66e7f88a.png)
