### ISSUE TITLE
Функции задачи 

### ISSUE THREAD

**Issue by Serebro00** [javascript-tutorial/ru.javascript.info#970]
Задача 4. Думаю более правильнее было бы сделать концовку кода так 
`if (x < 1 ) {
    alert(`Степень ${x} не поддерживается, используйте натуральное число`);
  } else if (n < 1){
    alert(`Степень ${n} не поддерживается, используйте натуральное число`);
  } else {
    alert( pow(x, n) );
  }`
Иначе же, без проверки вводимого числа x функция будет выполняться, т.е. будет выполнение  не натуральных чисел, а по условию этого не должно.

**Comment by Serebro00** [comment]
Забыл добавить ссылку где именно: [тык](https://learn.javascript.ru/function-basics)

**Comment by TravellerOnline** [comment]
Во-первых, х не степень, а основание степени
Во-вторых, в условии сказано, что степень должна быть натуральным числом, к основанию степени таких требований не было
Закрывай тему
