### ISSUE TITLE
ошибка в примерах

### ISSUE THREAD

**Issue by DarkDiMMu** [javascript-tutorial/ru.javascript.info#972]
![2020-06-10 (1)](https://user-images.githubusercontent.com/58729530/84262158-c9713280-ab25-11ea-944b-7d2fd5728b19.png)

[ссылка на страницу с ошибкой](https://learn.javascript.ru/number)

Должно быть:
**1** делится на 1 с 3 нулями и **1.23** делится на 1 с 6 нулями

**Comment by iampopovich** [comment]
![image](https://user-images.githubusercontent.com/23129441/183776304-8707cccd-0078-40cd-a549-686be676da82.png)
пофикшено , закройте, пожалуйста @DarkDiMMu
