### ISSUE TITLE
Ошибка в тесте

### ISSUE THREAD

**Issue by AChernenok** [javascript-tutorial/ru.javascript.info#973]
Тест "Язык JavaScript", вопрос таков:
Чему равно i в конце кода?

> 1    for(var i=0; i<10; i++) {
> 2      console.log(i);
> 3    }
> 4   // i = ?

Варианты ответов:

- undefined;
- 9;
- 10;
- Нет такой переменной после цикла.

Правильный ответ будет 9, у вас указано, что верный ответ - 10.

**Comment by kpodmasko** [comment]
Ошибки в тесте нет, ответ верный. Сначала движок проинкрементировал i с 9 на 10, а потом сравнил i < 10 и вышел из цикла. Поэтому после тела цикла i === 10.
![image](https://user-images.githubusercontent.com/22004278/84397242-43c5b380-ac07-11ea-9f4f-feaa84e269c7.png)
