### ISSUE TITLE
Возможная ошибка в главе "Стили и классы".

### ISSUE THREAD

**Issue by ghost** [javascript-tutorial/ru.javascript.info#976]
В главе "[Стили и классы](https://learn.javascript.ru/styles-and-classes)" написано:

> **Нельзя установить список стилей как, например, div.style="color: red; width: 100px", потому что div.style – это объект, и он доступен только для чтения.** Для задания нескольких стилей в одной строке используется специальное свойство style.cssText.

Я прошёл эту главу и попытался воспроизвести это, вот что получилось (изображение можно открыть, будет лучше видно).

![Альтернативный текст](http://ipic.su/img/img7/fs/example.1591910011.png)

Хотелось бы как минимум докопаться до истины.

**Comment by oleedd** [comment]
У меня в Chrome тоже работает.

**Comment by oleedd** [comment]
И ещё ниже написано:
>Это свойство редко используется, потому что такое присваивание удаляет все существующие стили: оно не добавляет, а заменяет их.

Но ведь никто не мешает использовать `+=`, тогда не удаляет все существующие.

**Comment by Alexandre887** [comment]
Информация устарела, обновили статью.
