### ISSUE TITLE
"То есть" и "фактически" не требуют пунктуационного обособления

### ISSUE THREAD

**Issue by oleedd** [javascript-tutorial/ru.javascript.info#989]
В учебнике часто встречается запятая после "то есть" в начале предложения.
http://new.gramota.ru/spravka/punctum?layout=item&id=58_733

Слово "фактически" в учебнике отделяется запятыми.
http://new.gramota.ru/spravka/punctum?layout=item&id=58_744

Например, в этом параграфе:
https://learn.javascript.ru/prototype-inheritance

**Comment by oleedd** [comment]
То же с "так что" (запятая не должна стоять после):
https://learn.javascript.ru/closure

**Comment by oleedd** [comment]
@Alexandre887
А ошибки исправлять никто не собирается?

**Comment by Alexandre887** [comment]
@oleedd 
Если по ходу чтения материала учебника вы заметили какие-либо ошибки, пожалуйста, отправьте в данный репозиторий Pull Request с исправлением — его рассмотрят, и, если он окажется действительно полезным, ваши правки будут применены на сайте. Это не сложно, у вас на это уйдет около 20-30 секунд.

А тщательный пересмотр всех статей в учебнике с целью расставить/убрать запятые того не стоит. Одна только первая часть учебника включает в себя **93 статьи** с содержанием различного объёма. 

Материал регулярно обновляется, добавляются новые статьи, некоторые из которых были переведены с английского языка на русский. Исходя из этого, соблюдать абсолютную грамотность во всех текстах физически невозможно.

**Comment by oleedd** [comment]
Пока что не имел дела с Pull Request-ами. Можно просто сделать поиск по этим словосочетаниям, тщательно пересматривать не нужно. Ссылки на 2 параграфа с этими ошибками есть выше.

**Comment by Alexandre887** [comment]
Словом, пунктуация в статьях, которые вы указали, будет исправлена. Эта issue будет снова открытой до того момента, как будут внесены корректировки. 
А насчет остальных статей, как я уже сказал, — присылайте свои Pull Request'ы с правками.

**Comment by oleedd** [comment]
Эту тоже надо убрать. Одна даже хуже, чем две.

![image](https://user-images.githubusercontent.com/36125949/186521522-2437c19c-6efa-413c-b2e2-1578ce34937c.png)

**Comment by oleedd** [comment]
>Так что, если мы создадим глобальную переменную в одном скрипте, она станет доступна и в других.

А в этом предложении запятая нужна, она же ставится перед союзом "если".

**Comment by oleedd** [comment]
>Так что если мы создадим глобальную переменную в одном скрипте, она станет доступна и в других.

А в этом предложении запятая нужна, она же ставится перед союзом "если".

**Comment by Alexandre887** [comment]
> Эту тоже надо убрать. Одна даже хуже, чем две.
> 
> ![image](https://user-images.githubusercontent.com/36125949/186521522-2437c19c-6efa-413c-b2e2-1578ce34937c.png)

Исправлено:

![image](https://user-images.githubusercontent.com/74434545/186522589-ef2073ca-3e43-4e7b-9dc4-8843951e7c32.png)

**Comment by Alexandre887** [comment]
> > Так что если мы создадим глобальную переменную в одном скрипте, она станет доступна и в других.
> 
> А в этом предложении запятая нужна, она же ставится перед союзом "если".

Исправлено:

![image](https://user-images.githubusercontent.com/74434545/186523121-bb7f2915-a8e4-478a-996b-96d7d1e8b812.png)

**Comment by Alexandre887** [comment]
Есть еще замечания?

**Comment by oleedd** [comment]
Здесь надо поставить запятую:

![image](https://user-images.githubusercontent.com/36125949/186523239-0ba44aed-cbcb-4a5b-a8f1-a786f3b3928c.png)
Там сложно. Из-за слова "все", оно способствует присоединению.

**Comment by oleedd** [comment]
>То есть чтобы вместо функции, мы просто писали `byField(fieldName)`.

Здесь, по ходу, какого-то слова не хватает. Некорректное предложение. Ну и запятая ставится перед "чтобы".

**Comment by Alexandre887** [comment]
Готово.
![image](https://user-images.githubusercontent.com/74434545/186524449-e0d332ef-76e0-43fa-ac4c-ffba3f34d06c.png)

**Comment by oleedd** [comment]
>То есть чтобы вместо функции, мы просто писали `byField(fieldName)`.

Здесь, по ходу, какого-то слова не хватает. Некорректное предложение. Ну и запятая ставится перед "чтобы".

**Comment by Alexandre887** [comment]
Вполне корректное предложение, на мой взгляд. Чем вы предлагаете его заменить?

**Comment by oleedd** [comment]
>чтобы вместо функции

Это как? Это не по-русски?

**Comment by oleedd** [comment]
Всё, понял уже его. Тогда там запятые не нужны вообще. Оборот с "вместо" обособлять не нужно.

**Comment by oleedd** [comment]
>Можем ли мы сделать его короче, скажем, вот таким?

Вводное слово не отделяется запятой от обособленного оборота. Вторую запятую надо убрать. "Скажем" плохо подходит в плане стилистики, его лучше заменить на "например".

**Comment by Alexandre887** [comment]
Как раз таки запятых там и нет, я еще в первом коммите убрал их.

**Comment by oleedd** [comment]
Да, уже видел, что на сайте нет, но здесь есть: https://github.com/javascript-tutorial/ru.javascript.info/pull/1718/commits/1735d7279cc39decbb5b1511e413963731a77f0c
Неважно.

**Comment by oleedd** [comment]
Да, видел, что на сайте нет, но здесь есть: https://github.com/javascript-tutorial/ru.javascript.info/pull/1718/commits/1735d7279cc39decbb5b1511e413963731a77f0c. Неважно.

>Можем ли мы сделать его короче, скажем, вот таким?

Вводное слово не отделяется запятой от обособленного оборота. Вторую запятую надо убрать. "Скажем" плохо подходит в плане стилистики, его лучше заменить на "например".

**Comment by Alexandre887** [comment]
> > Можем ли мы сделать его короче, скажем, вот таким?
> 
> Вводное слово не отделяется запятой от обособленного оборота. Вторую запятую надо убрать. "Скажем" плохо подходит в плане стилистики, его лучше заменить на "например".

Насколько я понял, у вас еще много подобных замечаний. Поэтому, заниматься исправлением на ходу я сейчас не буду. Пишите обо всем, что нужно исправить **конкретно в этих двух статьях (в плане пунктуации)**, позже я внесу изменения.

**Comment by oleedd** [comment]
У меня ещё одно. Всё не проверяю, просто глянул, как вы исправили. Мне было бы просто, если можно было бы править, как в Википедии.
![image](https://user-images.githubusercontent.com/36125949/186527696-431c0b6c-60af-4e7a-aa2c-f3d1e941f60b.png)
Где кодовое выделение?

**Comment by Alexandre887** [comment]
> Мне было бы просто, если можно было бы править, как в Википедии.

А что конкретно вызывает затруднения в Github?

**Comment by oleedd** [comment]
Не знаю. Просто, когда читаешь статью, чтобы освежить знания, и правишь заодно.

**Comment by oleedd** [comment]
Нажал на кнопку "Редактировать на GitHub" — какие-то папки, файлы. Кто захочет в этом разбираться, чтобы добавить/убрать запятую?

**Comment by Alexandre887** [comment]
Как я уже отвечал вам в другом issue, практика показывает, что это очень эффективный способ исправления статей. На момент написания этого комментария принято уже **1283** правки. Видимо, кто-то хочет "в этом разбираться, чтобы что-то добавить".

![image](https://user-images.githubusercontent.com/74434545/186530357-61a54546-ad58-43b4-9c52-902dedcc5dfa.png)

> Нажал на кнопку "Редактировать на GitHub" — какие-то папки, файлы.

В папках находятся задачи к статье, а в файле _article.md_ — содержание статьи. Не вижу ничего сложного.
Хотите отредактировать задание? Выбираете папку, название которой соответствует названию задачи на сайте, и редактируете файлы. _solution.md_ — текст решения задачи, _task.md_ — текст самой задачи.
Хотите отредактировать текст статьи? Открываете _article.md_ и редактируете.

**Comment by oleedd** [comment]
Ладно, выше два замечания. Пока это всё. Статьи уже читаю редко. И не целиком, а фрагментарно.

**Comment by oleedd** [comment]
Ладно, выше два замечания. Пока это всё. Статьи уже читаю редко. И не целиком, а выборочно.

**Comment by Alexandre887** [comment]
> У меня ещё одно. Всё не проверяю, просто глянул, как вы исправили. Мне было бы просто, если можно было бы править, как в Википедии. ![image](https://user-images.githubusercontent.com/36125949/186527696-431c0b6c-60af-4e7a-aa2c-f3d1e941f60b.png) Где кодовое выделение?

Кодовое выделение присутствует:

![image](https://user-images.githubusercontent.com/74434545/186534533-84954508-0327-4ee3-a29e-7ce2e9ad7ffa.png)
Возможно, у вас просто неполностью прогрузилась страница.

**Comment by oleedd** [comment]
А здесь нет: https://learn.javascript.ru/task/sort-by-field
Баг?
Ну и это: https://github.com/javascript-tutorial/ru.javascript.info/issues/989#issuecomment-1226394327

**Comment by Alexandre887** [comment]
Да, скорее всего это баг.

https://github.com/javascript-tutorial/ru.javascript.info/issues/989#issuecomment-1226394327 исправил.

**Comment by Alexandre887** [comment]
Могу закрывать issue?

**Comment by oleedd** [comment]
Да. Не забывайте про "то есть", фактически и "так что", когда читаете.
