### ISSUE TITLE
1-js/05-data-types/05-array-methods/

### ISSUE THREAD

**Issue by shchegol** [javascript-tutorial/ru.javascript.info#99]
Начал перевод.

Есть вопрос по этой строке:
`The [arr.splice(str)](mdn:js/Array/splice) method is a swiss army knife for arrays. It can do everything: add, remove and insert elements.`

Вот это место меня беспокоит: add, remove and **insert** elements.
Это перевести как: добавлять, удалять и вставлять элементы?
Или всё же: добавлять, удалять и заменять элементы?

**Comment by shchegol** [comment]
Как лучше перевести: `nothing prevents from alerting them`
... ничто не мешает вывести их на экран, норм?

**Comment by lex111** [comment]
@shchegol да, хорошо.

**Comment by shchegol** [comment]
Есть такой кусок:
```js
let result = arr.find(function(item, index, array) {
  // if true is returned, item is returned and iteration is stopped
  // for falsy scenario returns undefined
});
```
Никак не могу сообразить как лучше это перевести.
Пока остановился на таком варианте:

```js
let result = arr.find(function(item, index, array) {
  // если функция вернёт true, то метод отдаст текущий элемент и перебор остановится
  // если на всех итерациях возвратится false, метод вернёт undefined
});
```

**Comment by shchegol** [comment]
Переведено: #196
